//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class TFNTwitterCardContext, TFNTwitterCardImageSpec;

@interface _TtC9T1Twitter36NativeWebCardMediaViewModelBaseClass : NSObject
{
    // Error parsing type: , name: cardContext
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) TFNTwitterCardImageSpec *imageSpec;
@property(nonatomic, readonly) long long mediaType;
- (id)initWithCardContext:(id)arg1;
@property(nonatomic, readonly) TFNTwitterCardContext *cardContext; // @synthesize cardContext;

@end

