//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1TypeaheadTableViewController.h>

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter24UserPickerViewController : T1TypeaheadTableViewController
{
    // Error parsing type: , name: userPickerDelegate
    // Error parsing type: , name: searchView.storage
    // Error parsing type: , name: typeaheadSourceType
    // Error parsing type: , name: searchResultCache
    // Error parsing type: , name: pickedUserReferences
    // Error parsing type: , name: pickerDescription
    // Error parsing type: , name: searchPlaceholder
    // Error parsing type: , name: displayedSearchResult
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithAccount:(id)arg1;
- (void)typeaheadTableViewController:(id)arg1 didSelectUser:(id)arg2 index:(long long)arg3;
- (void)tokenField:(id)arg1 didAddToken:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)tokenField:(id)arg1 didRemoveToken:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)viewDidLayoutSubviews;
- (void)searchTokenFieldEditingChanged;
- (void)update:(_Bool)arg1;
- (void)viewDidLoad;

@end

