//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC9T1TwitterP33_043C94438D46392785DBC88A2875DC0E27NewsCameraGeoPickerCellData : SwiftObject
{
    // Error parsing type: , name: itemKind
    // Error parsing type: , name: item
}

@end

