//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <T1Twitter/T1UserBadgeable-Protocol.h>

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter15SimpleBadgeable : NSObject <T1UserBadgeable>
{
    // Error parsing type: , name: isVerified
    // Error parsing type: , name: isProtectedUser
    // Error parsing type: , name: isUsernameless
    // Error parsing type: , name: translatorType
}

- (id)init;
@property(nonatomic, readonly) long long translatorType; // @synthesize translatorType;
@property(nonatomic, readonly) _Bool isUsernameless; // @synthesize isUsernameless;
@property(nonatomic, readonly) _Bool isProtectedUser; // @synthesize isProtectedUser;
@property(nonatomic, readonly) _Bool isVerified; // @synthesize isVerified;

@end

