//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter15MomentScoreView : UIView
{
    // Error parsing type: , name: scoreView
    // Error parsing type: , name: viewModel
    // Error parsing type: , name: topSeparatorHidden
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)sportEventsDataManager:(id)arg1 didUpdateEvent:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

