//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITapGestureRecognizer.h>

__attribute__((visibility("hidden")))
@interface _TtC9T1TwitterP33_6743AC1DD6E9E901C2AFEA00526CE9AE16TabTapRecognizer : UITapGestureRecognizer
{
    // Error parsing type: , name: tabEntry
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;

@end

