//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter32URTTimelineEventSummaryViewModel : NSObject
{
    // Error parsing type: , name: accountID
    // Error parsing type: , name: eventSummary
    // Error parsing type: , name: clientEventInfo
    // Error parsing type: , name: url
    // Error parsing type: , name: authorUser
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)scribeElement;
- (id)scribeComponent;
@property(nonatomic, readonly) NSDictionary *scribeItem;
@property(nonatomic, readonly) NSString *scribeItemImpressionID;

@end

