//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNTwitterAvatarImageView.h>

@class UIImage;

@interface _TtC9T1Twitter19DashAvatarImageView : TFNTwitterAvatarImageView
{
    // Error parsing type: , name: account
    // Error parsing type: , name: selected
    // Error parsing type: , name: fullColorImage
    // Error parsing type: , name: desaturatedImage
}

- (CDUnknownBlockType).cxx_destruct;
- (void)updateUserFromAccount;
@property(nonatomic, retain) UIImage *image;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

