//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/_TtC9T1Twitter21URTEndpointAPICommand.h>

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter29URTInternalEndpointAPICommand : _TtC9T1Twitter21URTEndpointAPICommand
{
}

- (id)request;

@end

