//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter10MomentView : UIView
{
    // Error parsing type: , name: contentStackView
    // Error parsing type: , name: bodyStackView
    // Error parsing type: , name: bodyContentStackView
    // Error parsing type: , name: headerView
    // Error parsing type: , name: descriptionView
    // Error parsing type: , name: imageView
    // Error parsing type: , name: socialProofView
    // Error parsing type: , name: promotedView
    // Error parsing type: , name: scoreView
    // Error parsing type: , name: subscribeView
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutMetricsDidChange:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
@property(nonatomic, readonly) UIView *presentationSourceView;

@end

