//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIApplication.h>

#import <T1Twitter/TFNApplicationWithEffectiveStatusBarOrientationSupport-Protocol.h>

@interface _TtC9T1Twitter13T1Application : UIApplication <TFNApplicationWithEffectiveStatusBarOrientationSupport>
{
    // Error parsing type: , name: isWarmStart
    // Error parsing type: , name: taskIds
    // Error parsing type: , name: backgroundStopwatch
    // Error parsing type: , name: account
    // Error parsing type: , name: previousBackgroundTime
    // Error parsing type: , name: effectiveStatusBarOrientation
}

- (CDUnknownBlockType).cxx_destruct;
- (void)tfn_performWithEffectiveStatusBarOrientation:(long long)arg1 block:(CDUnknownBlockType)arg2;
- (void)accountDidBecomeActiveWithNotification:(id)arg1;
- (void)willEnterForegroundWithNotification:(id)arg1;
- (void)didEnterBackgroundWithNotification:(id)arg1;
- (void)endBackgroundTask:(long long)arg1;
- (long long)beginBackgroundTaskWithName:(id)arg1 expirationHandler:(CDUnknownBlockType)arg2;
- (long long)beginBackgroundTaskWithExpirationHandler:(CDUnknownBlockType)arg1;
@property(nonatomic) long long statusBarOrientation;
- (id)init;
@property(nonatomic) _Bool isWarmStart; // @synthesize isWarmStart;

@end

