//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString;

@interface _TtC8TFSModel15ModelCacheEntry : NSObject
{
    // Error parsing type: , name: cacheableModel
    // Error parsing type: , name: cacheEncoder
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSArray *cacheKeysToWarmAfterFetch;
@property(nonatomic, readonly) NSDictionary *cacheSearchKeyToScore;
@property(nonatomic, readonly) NSDictionary *cacheSearchKeyToValues;
@property(nonatomic, readonly) NSArray *ownedCacheKeys;
@property(nonatomic, readonly) _Bool isAutomaticUncachingEnabled;
@property(nonatomic, readonly) NSString *cacheKey;

@end

