//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC9T1Twitter39InteractiveSegmentedTabSelectionContext : SwiftObject
{
    // Error parsing type: , name: startSelectedIndex
    // Error parsing type: , name: endSelectedIndex
    // Error parsing type: , name: startContentOffsetX
    // Error parsing type: , name: endContentOffsetX
    // Error parsing type: , name: scrollDirection
}

@end

