//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@protocol NSCopying;

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter36UploadContactsOperationChunkProgress : NSObject
{
    // Error parsing type: , name: excludeFromProgressCenter
    // Error parsing type: , name: uniqueID
    // Error parsing type: , name: progressWeight
    // Error parsing type: , name: progress
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic) double progress; // @synthesize progress;
@property(nonatomic, readonly) unsigned long long progressWeight; // @synthesize progressWeight;
@property(nonatomic, readonly) id <NSCopying> uniqueID; // @synthesize uniqueID;
@property(nonatomic, readonly) _Bool excludeFromProgressCenter; // @synthesize excludeFromProgressCenter;

@end

