//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFSModel/_TtC8TFSModel14DependencyNode.h>

@interface _TtC8TFSModel16DependencySource : _TtC8TFSModel14DependencyNode
{
    // Error parsing type: , name: model
    // Error parsing type: , name: graph
    // Error parsing type: , name: sourceNodes
    // Error parsing type: , name: privateState
}

@end

