//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNTableViewCell.h>

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter22FollowSearchPromptCell : TFNTableViewCell
{
    // Error parsing type: , name: promptView
    // Error parsing type: , name: accessoryButtonTappedBlock
    // Error parsing type: , name: dismissButtonTappedBlock
    // Error parsing type: , name: followsSearch
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)didTapDismissButton;
- (void)didTapFollowButton;
- (id)initWithCoder:(id)arg1;

@end

