//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/_TtC9T1Twitter25VideoHeaderViewController.h>

@interface _TtC9T1Twitter25VideoHeaderViewController (T1Twitter)
- (_Bool)avPlayerControllerShouldManagePlayerVolume:(id)arg1;
- (void)avPlayerControllerPlaybackDidStart:(id)arg1;
- (void)avPlayerController:(id)arg1 didFailToLoadWithError:(id)arg2;
- (void)avPlayerControllerDidCompletePreparingForPlayback:(id)arg1;
- (double)avPlayerController:(id)arg1 visibilityPercentageForPlayerView:(id)arg2;
- (void)avPlayerController:(id)arg1 detachPlayerView:(id)arg2 animated:(_Bool)arg3;
- (void)avPlayerController:(id)arg1 attachPlayerView:(id)arg2 animated:(_Bool)arg3;
@end

