//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC9T1Twitter38URTTimelineUpdateEndpointRequestAction : SwiftObject
{
    // Error parsing type: , name: started
    // Error parsing type: , name: context
    // Error parsing type: , name: parameters
    // Error parsing type: , name: requestCursor
    // Error parsing type: , name: accountID
    // Error parsing type: , name: urtTimelineUID
    // Error parsing type: , name: apiCommandFactory
}

@end

