//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC9T1Twitter40StandardSegmentedViewTabLayoutCalculator : SwiftObject
{
    // Error parsing type: , name: tabEntries
    // Error parsing type: , name: minimumWidthThreshold
    // Error parsing type: , name: preferredWidthThreshold
}

@end

