//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter37DirectMessageQuickShareViewController : TFNViewController
{
    // Error parsing type: , name: isModalSheetsEnabled
    // Error parsing type: , name: account
    // Error parsing type: , name: addressingToolbar
    // Error parsing type: , name: addressingToolbarTopConstraint.storage
    // Error parsing type: , name: composeBarController
    // Error parsing type: , name: composeBarBottomConstraint.storage
    // Error parsing type: , name: composeBarTopBorderView
    // Error parsing type: , name: composeBarContainerView
    // Error parsing type: , name: pickerBottomBorderView
    // Error parsing type: , name: pickerViewController
    // Error parsing type: , name: pickerViewHeightConstraint.storage
    // Error parsing type: , name: scrollView
    // Error parsing type: , name: shouldShowDismissButton
    // Error parsing type: , name: selectionBehavior.storage
    // Error parsing type: , name: sharedItem
    // Error parsing type: , name: validator
    // Error parsing type: , name: dataSource
    // Error parsing type: , name: didDismissBlock
    // Error parsing type: , name: resultsObserver
    // Error parsing type: , name: addressingToolbarFormattedForEditing
    // Error parsing type: , name: expectedKeyboardFrame
    // Error parsing type: , name: keyboardShouldBeShown
    // Error parsing type: , name: suppressTokenFieldDelegateUpdates
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)scribeSection;
- (id)scribePage;
- (void)keyboardDidChangeFrame:(id)arg1;
- (void)keyboardWillChangeFrame:(id)arg1;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)searchTokenFieldEditingChanged:(id)arg1;
- (void)layoutMetricsDidChange:(id)arg1;
- (double)lengthOfLayoutGuide:(long long)arg1 forEnvironment:(id)arg2;
- (void)layoutGuidesDidChange:(long long)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewDidFullyAppear:(_Bool)arg1;
- (void)updateSelectionStates;
- (void)dismissAnimated;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;

@end

