//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter19SurveyCardViewModel : NSObject
{
    // Error parsing type: , name: survey
    // Error parsing type: , name: cardContext
    // Error parsing type: , name: fullScreen
    // Error parsing type: , name: completedInFullScreen
    // Error parsing type: , name: surveyCardView
    // Error parsing type: , name: delegate
    // Error parsing type: , name: numberOfPages.storage
    // Error parsing type: , name: surveyPages.storage
    // Error parsing type: , name: response.storage
    // Error parsing type: , name: cardPersistedStateManager.storage
    // Error parsing type: , name: didCompleteSurvey.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithCardContext:(id)arg1;

@end

