//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNCollectionViewCell.h>

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter16CardCarouselCell : TFNCollectionViewCell
{
    // Error parsing type: , name: cardContainerView
    // Error parsing type: , name: cardDelegate
    // Error parsing type: , name: cardContext
}

- (CDUnknownBlockType).cxx_destruct;
- (void)cleanup;
- (id)calculatedLayoutMetrics;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

