//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFSUtilities/TFSConcurrentOperation.h>

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter23DeleteContactsOperation : TFSConcurrentOperation
{
    // Error parsing type: , name: account
    // Error parsing type: , name: contacts
    // Error parsing type: , name: settings
    // Error parsing type: , name: operationQueue.storage
    // Error parsing type: , name: delegate
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)run;

@end

