//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/_TtC9T1Twitter38SurveyCardFullScreenPageViewController.h>

@interface _TtC9T1Twitter38SurveyCardFullScreenPageViewController (T1Twitter)
@property(nonatomic, readonly) _Bool tfn_logoTitleViewShown;
@property(nonatomic, readonly) long long tfn_preferredToolbarVisibility;
@property(nonatomic, readonly) _Bool tfn_prefersNavigationBarShadowHidden;
@end

