//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/_TtC9T1Twitter48DirectMessageConversationTypingIndicatorBehavior.h>

#import <T1Twitter/T1DirectMessageTypingIndicatorViewDelegate-Protocol.h>

@interface _TtC9T1Twitter48DirectMessageConversationTypingIndicatorBehavior (T1Twitter) <T1DirectMessageTypingIndicatorViewDelegate>
- (void)typingIndicatorView:(id)arg1 didTapUser:(id)arg2;
@end

