//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray, _TtC9T1Twitter24UserPickerViewController;

@protocol _TtP9T1Twitter32UserPickerViewControllerDelegate_

@optional
- (void)userPickerViewController:(_TtC9T1Twitter24UserPickerViewController *)arg1 didUpdatePickedUserReferences:(NSArray *)arg2;
@end

