//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AVFoundation/AVAssetImageGenerator.h>

@interface AVAssetImageGenerator (TFNAdditions)
+ (void)tfn_generateImageAsynchronouslyWithAsset:(id)arg1 maxSize:(long long)arg2 time:(CDStruct_198678f7)arg3 completion:(CDUnknownBlockType)arg4;
@end

