//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class UIPanGestureRecognizer, UIView;
@protocol AVRInteractionControllerDelegate;

@protocol AVRInteractionController
@property(nonatomic) _Bool enabled;
@property(readonly, nonatomic) union _GLKMatrix4 viewMatrix;
@property(nonatomic) __weak id <AVRInteractionControllerDelegate> delegate;
- (void)handlePan:(UIPanGestureRecognizer *)arg1;
- (void)beginTransitionFromMatrix:(union _GLKMatrix4)arg1;
- (void)updateWithDeltaTime:(float)arg1;
- (void)detach;
- (void)attachToView:(UIView *)arg1;
@end

