//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <AVRKit/AVRInternalRenderView-Protocol.h>

@class AVRInternalRenderState, AVRMetalRenderer, AVRMetalTextureCache, CAMetalLayer, NSObject;
@protocol MTLCommandQueue, MTLDevice, OS_dispatch_queue;

@interface AVRMetalRenderView : UIView <AVRInternalRenderView>
{
    _Bool _rendering;
    _Bool _needsClear;
    _Bool _processOnGPU;
    id <MTLDevice> _device;
    CAMetalLayer *_metalLayer;
    AVRMetalRenderer *_renderer;
    AVRMetalTextureCache *_textureCache;
    AVRInternalRenderState *_lastRenderState;
    id <MTLCommandQueue> _mtlCommandQueue;
    NSObject<OS_dispatch_queue> *_renderSyncQueue;
    long long _drawablePresentedHandlerAvailability;
}

+ (_Bool)metalSupported;
+ (Class)layerClass;
@property _Bool processOnGPU; // @synthesize processOnGPU=_processOnGPU;
@property _Bool needsClear; // @synthesize needsClear=_needsClear;
@property _Bool rendering; // @synthesize rendering=_rendering;
@property(nonatomic) long long drawablePresentedHandlerAvailability; // @synthesize drawablePresentedHandlerAvailability=_drawablePresentedHandlerAvailability;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *renderSyncQueue; // @synthesize renderSyncQueue=_renderSyncQueue;
@property(retain, nonatomic) id <MTLCommandQueue> mtlCommandQueue; // @synthesize mtlCommandQueue=_mtlCommandQueue;
@property(retain, nonatomic) AVRInternalRenderState *lastRenderState; // @synthesize lastRenderState=_lastRenderState;
@property(retain, nonatomic) AVRMetalTextureCache *textureCache; // @synthesize textureCache=_textureCache;
@property(retain, nonatomic) AVRMetalRenderer *renderer; // @synthesize renderer=_renderer;
@property(retain, nonatomic) CAMetalLayer *metalLayer; // @synthesize metalLayer=_metalLayer;
@property(retain, nonatomic) id <MTLDevice> device; // @synthesize device=_device;
- (void).cxx_destruct;
- (void)flushGPUOnQueue:(id)arg1;
- (void)flushGPU;
- (void)renderWithPixelBuffer:(struct __CVBuffer *)arg1 state:(id)arg2;
@property(readonly, nonatomic) _Bool canRender;
- (void)removeFromSuperview;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

