//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PeriscopeViewer/NSObject-Protocol.h>

@class DJICamera, DJICameraExposureParameters, DJICameraLensState, DJICameraSDCardState, DJICameraSSDState, DJICameraSystemState, DJIMedia, UIImage;

@protocol DJICameraDelegate <NSObject>

@optional
- (void)camera:(DJICamera *)arg1 didUpdateTemperatureData:(float)arg2;
- (void)camera:(DJICamera *)arg1 didUpdateCurrentExposureValues:(DJICameraExposureParameters *)arg2;
- (void)camera:(DJICamera *)arg1 didUpdateSSDState:(DJICameraSSDState *)arg2;
- (void)camera:(DJICamera *)arg1 didUpdateSDCardState:(DJICameraSDCardState *)arg2;
- (void)camera:(DJICamera *)arg1 didGenerateTimeLapsePreview:(UIImage *)arg2;
- (void)camera:(DJICamera *)arg1 didGenerateNewMediaFile:(DJIMedia *)arg2;
- (void)camera:(DJICamera *)arg1 didUpdateLensState:(DJICameraLensState *)arg2;
- (void)camera:(DJICamera *)arg1 didUpdateSystemState:(DJICameraSystemState *)arg2;
- (void)camera:(DJICamera *)arg1 didReceiveVideoData:(char *)arg2 length:(unsigned long long)arg3;
@end

