//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PeriscopeViewer/NSObject-Protocol.h>

@class NSError;

@protocol INSLiveDataSourceProtocol <NSObject>
- (void)sourceOnAACData:(const char *)arg1 size:(unsigned long long)arg2 timestamp:(long long)arg3;
- (void)sourceOnAACHeader:(const char *)arg1 size:(unsigned long long)arg2;
- (void)sourceOnH264Nalu:(const char *)arg1 size:(unsigned long long)arg2 keyFrame:(_Bool)arg3 timestamp:(long long)arg4;
- (void)sourceOnH264Header:(const char *)arg1 spsSize:(unsigned long long)arg2 pps:(const char *)arg3 ppsSize:(unsigned long long)arg4;
- (void)sourceOnError:(NSError *)arg1;

@optional
- (void)sourceOnRawPixelBuffer:(struct __CVBuffer *)arg1 timestamp:(long long)arg2;
- (void)sourceOnStitchPixelBuffer:(struct __CVBuffer *)arg1 timestamp:(long long)arg2;
@end

