//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <ZipUtilities/NOZDecoderContext-Protocol.h>

@class NSString;

@interface NOZDeflateDecoderContext : NSObject <NOZDecoderContext>
{
    struct z_stream_s _zStream;
    _Bool _zStreamOpen;
    _Bool _hasFinished;
    CDUnknownBlockType _flushCallback;
    char *_decompressedDataBuffer;
    unsigned long long _decompressedDataBufferSize;
}

@property(readonly, nonatomic) unsigned long long decompressedDataBufferSize; // @synthesize decompressedDataBufferSize=_decompressedDataBufferSize;
@property(readonly, nonatomic) char *decompressedDataBuffer; // @synthesize decompressedDataBuffer=_decompressedDataBuffer;
@property(nonatomic) _Bool hasFinished; // @synthesize hasFinished=_hasFinished;
@property(nonatomic) _Bool zStreamOpen; // @synthesize zStreamOpen=_zStreamOpen;
@property(copy, nonatomic) CDUnknownBlockType flushCallback; // @synthesize flushCallback=_flushCallback;
- (void).cxx_destruct;
- (void)doubleDecompressDataBuffer;
@property(readonly, nonatomic) struct z_stream_s *zStream;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

