//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDate.h>

@interface NSDate (TFNLocalizedAdditions)
- (id)tfn_remainingDurationString;
- (id)tfn_friendlyRelativeTimestampString;
- (id)tfn_mediumOrTinyRelativeTimeAgoString;
- (id)relativeTimeAgoAccessibilityString;
- (id)relativeTimeAgoString;
- (id)_tfn_relativeTimeAgoStringWithinDays;
- (id)fullRelativeTimeUntilString;
- (id)fullRelativeTimeAgoString;
- (id)_tfn_tinyRelativeTimeAgoString;
- (id)_tfn_relativeTimeUntilStringWithFormatForSeconds:(id)arg1 second:(id)arg2 minutes:(id)arg3 minute:(id)arg4 hours:(id)arg5 hour:(id)arg6 days:(id)arg7 day:(id)arg8;
- (id)_tfn_relativeTimeAgoStringWithFormatForSeconds:(id)arg1 second:(id)arg2 minutes:(id)arg3 minute:(id)arg4 hours:(id)arg5 hour:(id)arg6 days:(id)arg7 day:(id)arg8;
- (id)tfn_accessibilityTimestampString;
@end

