//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (TFSWordRange)
- (struct _NSRange)wordRangeIncludingUnderscoreForIndex:(unsigned long long)arg1;
- (struct _NSRange)wordRangeForIndex:(long long)arg1;
- (struct _NSRange)_tfs_wordRangeExpandRight:(struct _NSRange)arg1;
- (struct _NSRange)_tfs_wordRangeExpandLeft:(struct _NSRange)arg1;
@end

