//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PeriscopeViewer/NSObject-Protocol.h>

@class PTVBroadcastDetailsViewController, PTVMergeParticipantUser;

@protocol PTVBroadcastDetailsViewControllerDelegate <NSObject>

@optional
- (void)broadcastDetailsViewController:(PTVBroadcastDetailsViewController *)arg1 didSelectViewer:(PTVMergeParticipantUser *)arg2;
- (void)broadcastDetailsViewControllerDidSelectMap:(PTVBroadcastDetailsViewController *)arg1;
@end

