//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PeriscopeViewer/NSObject-Protocol.h>

@class NSString, PTVBroadcastOverflowMenuView;

@protocol PTVBroadcastOverflowMenuViewDelegate <NSObject>

@optional
- (void)broadcastOverflowMenuTitleViewDidTapHashtag:(NSString *)arg1;
- (void)broadcastOverflowMenuViewDidTapEmptySpace:(PTVBroadcastOverflowMenuView *)arg1;
@end

