//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PeriscopeViewer/PTVExtendedButton.h>

@class NSMutableDictionary, UIImage, UIImageView;

@interface PTVButton : PTVExtendedButton
{
    UIImageView *_trailingImageView;
    NSMutableDictionary *_trailingImagesByState;
    unsigned long long _previousState;
    struct UIEdgeInsets _trailingImageEdgeInsets;
}

@property(nonatomic) struct UIEdgeInsets trailingImageEdgeInsets; // @synthesize trailingImageEdgeInsets=_trailingImageEdgeInsets;
- (void).cxx_destruct;
- (void)updateTrailingImageView;
- (void)setTrailingImage:(id)arg1 forState:(unsigned long long)arg2;
- (id)trailingImageForState:(unsigned long long)arg1;
@property(readonly, nonatomic) UIImage *currentTrailingImage;
- (struct CGRect)trailingImageRectForContentRect:(struct CGRect)arg1;
- (void)ptv_controlStateDidChange;
- (void)detectWhetherStateChanged;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)setHighlighted:(_Bool)arg1;
- (void)setSelected:(_Bool)arg1;
- (void)setEnabled:(_Bool)arg1;
- (struct CGRect)shiftOriginOfRect:(struct CGRect)arg1 toAccountForTrailingImage:(id)arg2;
- (struct CGRect)imageRectForContentRect:(struct CGRect)arg1;
- (struct CGRect)maxTitleRectForContentRect:(struct CGRect)arg1;
- (struct CGRect)titleRectForContentRect:(struct CGRect)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

