//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, PTVChatSender;

@interface PTVChatControlMessage : NSObject
{
    unsigned long long _kind;
    PTVChatSender *_sender;
    NSString *_body;
    NSString *_payload;
}

+ (id)rosterMessageWithRoom:(id)arg1;
+ (id)leaveMessageWithRoom:(id)arg1;
+ (id)joinMessageWithRoom:(id)arg1;
+ (id)controlMessageFromWireMessage:(id)arg1;
@property(readonly, nonatomic) NSString *payload; // @synthesize payload=_payload;
@property(readonly, nonatomic) NSString *body; // @synthesize body=_body;
@property(readonly, nonatomic) PTVChatSender *sender; // @synthesize sender=_sender;
@property(readonly, nonatomic) unsigned long long kind; // @synthesize kind=_kind;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (id)initWithKind:(unsigned long long)arg1 bodyDictionary:(id)arg2;
- (id)initWithKind:(unsigned long long)arg1 sender:(id)arg2 body:(id)arg3 payload:(id)arg4;

@end

