//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class PTVChatFollowBroadcasterTableViewCellKVO;

@protocol PTVChatFollowBroadcasterTableViewCellKVODelegate
- (void)chatFollowBroadcasterTableViewCellDidTapFollow:(PTVChatFollowBroadcasterTableViewCellKVO *)arg1;
@end

