//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <PeriscopeViewer/DJISDKManagerDelegate-Protocol.h>
#import <PeriscopeViewer/PTVExternalCameraDetector-Protocol.h>

@class NSSet, NSString;

@interface PTVDJIDetector : NSObject <DJISDKManagerDelegate, PTVExternalCameraDetector>
{
    _Bool _hasInitializedSDK;
    NSString *_deviceName;
    NSSet *_DJIProtocols;
    _Bool _isRegistered;
    _Bool _isConnected;
}

+ (_Bool)IsEnabled;
@property _Bool isConnected; // @synthesize isConnected=_isConnected;
@property _Bool isRegistered; // @synthesize isRegistered=_isRegistered;
@property(readonly) NSString *deviceName; // @synthesize deviceName=_deviceName;
- (void).cxx_destruct;
- (void)setProductName:(id)arg1;
- (id)acquireCameraForSize:(struct CGSize)arg1;
- (void)sdkManagerProductDidChangeFrom:(id)arg1 to:(id)arg2;
- (void)sdkManagerDidRegisterAppWithError:(id)arg1;
- (void)startConnection;
- (void)releaseConnection;
- (void)checkPresence:(_Bool)arg1;
- (void)startDJISDKIfNecessary;
@property(readonly) _Bool is360;
@property(readonly) int audioRate;
@property(readonly) _Bool hasFixedAudio;
@property(readonly) struct CGSize defaultDimensions;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

