//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PeriscopeViewer/PTVGiftingContributorTableViewCell.h>

@class PTVMergeParticipantUser, PTVVirtualGiftContributor;

@interface PTVGiftingContributorTableViewCellKVO : PTVGiftingContributorTableViewCell
{
    PTVMergeParticipantUser *_user;
    PTVGiftingContributorTableViewCellKVO *_weakSelf;
    PTVVirtualGiftContributor *_contributor;
    long long _maxContribution;
    _Bool _isActiveContributor;
}

- (void).cxx_destruct;
- (void)unobserveUser;
- (void)observeUser;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)updateFollowButton;
- (void)updateBlockingState;
- (void)setContributor:(id)arg1 maxContribution:(long long)arg2 isActiveContributor:(_Bool)arg3;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

@end

