//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <PeriscopeViewer/PTVDismissButtonDelegate-Protocol.h>
#import <PeriscopeViewer/UIGestureRecognizerDelegate-Protocol.h>

@class NSMutableArray, NSString, POPSpringAnimation, PTVStatusWindow, UIPanGestureRecognizer, UIViewController;
@protocol PTVInteractiveDismissalTransitionDelegate, PTVInteractiveModalControllerDelegate;

@interface PTVInteractiveDismissalTransition : NSObject <UIGestureRecognizerDelegate, PTVDismissButtonDelegate>
{
    PTVStatusWindow *_statusWindow;
    double _endingVelocity;
    _Bool _presenting;
    _Bool _switchingToControllers;
    POPSpringAnimation *_translate;
    _Bool _interactiveTransitionEnabled;
    _Bool _useShade;
    _Bool _shouldControlStatusBarAppearance;
    _Bool _cancelling;
    _Bool _dropNewPresentationRequests;
    _Bool _dropNewDismissalRequests;
    unsigned long long _presentationAnimationOptions;
    id <PTVInteractiveDismissalTransitionDelegate> _delegate;
    UIViewController<PTVInteractiveModalControllerDelegate> *_toViewController;
    UIViewController *_fromViewController;
    UIPanGestureRecognizer *_pan;
    NSMutableArray *_dismissalCompletionBlocks;
}

@property(readonly, nonatomic) NSMutableArray *dismissalCompletionBlocks; // @synthesize dismissalCompletionBlocks=_dismissalCompletionBlocks;
@property(nonatomic) _Bool dropNewDismissalRequests; // @synthesize dropNewDismissalRequests=_dropNewDismissalRequests;
@property(nonatomic) _Bool dropNewPresentationRequests; // @synthesize dropNewPresentationRequests=_dropNewPresentationRequests;
@property(nonatomic) _Bool cancelling; // @synthesize cancelling=_cancelling;
@property(nonatomic) _Bool shouldControlStatusBarAppearance; // @synthesize shouldControlStatusBarAppearance=_shouldControlStatusBarAppearance;
@property(retain, nonatomic) UIPanGestureRecognizer *pan; // @synthesize pan=_pan;
@property(retain, nonatomic) UIViewController *fromViewController; // @synthesize fromViewController=_fromViewController;
@property(retain, nonatomic) UIViewController<PTVInteractiveModalControllerDelegate> *toViewController; // @synthesize toViewController=_toViewController;
@property(nonatomic) __weak id <PTVInteractiveDismissalTransitionDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long presentationAnimationOptions; // @synthesize presentationAnimationOptions=_presentationAnimationOptions;
@property(nonatomic) _Bool useShade; // @synthesize useShade=_useShade;
@property(nonatomic) _Bool interactiveTransitionEnabled; // @synthesize interactiveTransitionEnabled=_interactiveTransitionEnabled;
- (void).cxx_destruct;
- (void)handleState:(long long)arg1 location:(struct CGPoint)arg2 velocity:(struct CGPoint)arg3 translation:(struct CGPoint)arg4 bounds:(struct CGRect)arg5;
- (void)animationEnded:(_Bool)arg1;
- (void)cancelInteractiveTransition;
- (void)finishInteractiveTransition;
- (void)updateInteractiveTransition:(double)arg1;
- (void)startInteractiveTransition;
- (void)popTranslate:(struct CGRect)arg1 alphaToValue:(double)arg2 orUseStandardOption:(unsigned long long)arg3 duration:(double)arg4 withCompletion:(CDUnknownBlockType)arg5;
- (void)switchToViewController:(id)arg1;
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dismissViewController;
- (void)presentViewController:(id)arg1;
- (void)handlePanGesture:(id)arg1;
- (double)durationForEndFrame:(struct CGRect)arg1;
- (_Bool)shouldCancelWithVelocity:(struct CGPoint)arg1 translation:(struct CGPoint)arg2 location:(struct CGPoint)arg3 bounds:(struct CGRect)arg4;
- (struct CGRect)mainScreenBounds;
- (void)setStatusWindowToMainScreenBounds;
- (void)createAnimations;
- (id)initWithFromController:(id)arg1 statusWindow:(id)arg2 useShade:(_Bool)arg3 controlStatusBarAppearance:(_Bool)arg4 delegate:(id)arg5;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)didPressDismissButton:(struct CGPoint)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

