//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface PTVLockScreenControlLayoutSpecs : NSObject
{
}

+ (struct CGRect)FrameForLabelButtonWithSuperviewSize:(struct CGSize)arg1 IsLocked:(_Bool)arg2;
+ (id)LabelAttributedTextLocked;
+ (id)LabelAttributedTextUnlocked;
+ (id)LabelFont;
+ (struct CGRect)FrameForLockIconWithSuperviewSize:(struct CGSize)arg1;
+ (id)LockImagePressDown;
+ (id)LockImageActive;
+ (id)LockImageInactive;
+ (struct CGRect)FrameForBackgroundBarWithSuperViewSize:(struct CGSize)arg1;
+ (struct CGSize)MinimumFullSize;
+ (double)HorizontalPadding;

@end

