//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PeriscopeViewer/PTVLoadingImageView.h>

@class UIColor, UIImage, UITapGestureRecognizer;
@protocol PTVProfileImageEntity, PTVProfileImageViewDelegate;

@interface PTVProfileImageView : PTVLoadingImageView
{
    id <PTVProfileImageViewDelegate> _profileImageViewDelegate;
    UIImage *_profileImagePlaceholder;
    UITapGestureRecognizer *_defaultImageTapRecognizer;
    unsigned long long _formatType;
    _Bool _usePlaceholder;
    UIColor *_overlayColor;
    _Bool _useCircularCrop;
    id <PTVProfileImageEntity> _entity;
}

@property(readonly, nonatomic) id <PTVProfileImageEntity> entity; // @synthesize entity=_entity;
- (void).cxx_destruct;
- (id)cacheKeyPrefix;
- (void)setEntity:(id)arg1 formatType:(unsigned long long)arg2;
- (void)handleDefaultTap;
- (id)initWithDelegate:(id)arg1 placeholderImage:(id)arg2;
- (id)initWithDelegate:(id)arg1 usingPlaceholder:(_Bool)arg2;
- (id)initUsingPlaceholder:(_Bool)arg1;
- (CDUnknownBlockType)processor;
- (void)setImageURL:(id)arg1 overlayColor:(id)arg2 useCircularCrop:(_Bool)arg3;
- (void)setImageURL:(id)arg1 useCircularCrop:(_Bool)arg2;
- (void)setState:(int)arg1;
- (id)context;
- (void)load:(long long)arg1;

@end

