//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class PTVExtendedButton, UILabel;
@protocol PTVDismissButtonDelegate;

@interface PTVReadOnlyModalView : UIView
{
    PTVExtendedButton *_dismissButton;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    id <PTVDismissButtonDelegate> _dismissDelegate;
}

@property(nonatomic) __weak id <PTVDismissButtonDelegate> dismissDelegate; // @synthesize dismissDelegate=_dismissDelegate;
- (void).cxx_destruct;
- (void)dismissPressed;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

