//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PeriscopeViewer/PTVModalViewController.h>

@class NSString, PTVTitleSubtitleModalView;

@interface PTVReportBroadcastModalViewController : PTVModalViewController
{
    long long _reportType;
    CDUnknownBlockType _reportConfirmationHandler;
    PTVTitleSubtitleModalView *_modalView;
    NSString *_broadcasterUsername;
}

- (void).cxx_destruct;
- (id)initWithBroadcasterUsername:(id)arg1 reportType:(long long)arg2 reportConfirmationHandler:(CDUnknownBlockType)arg3;
- (id)modalView;
- (void)modalViewDidSelectMainActionButton;
- (unsigned long long)canPresentModalController:(id)arg1;

@end

