//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PeriscopeViewer/NSObject-Protocol.h>

@class NSArray, NSError, PTVModalViewController, PTVShareBroadcastCoordinator;

@protocol PTVShareBroadcastCoordinatorDelegate <NSObject>

@optional
- (void)shareBroadcastCoordinator:(PTVShareBroadcastCoordinator *)arg1 didShareWithSpecificFollowerIDs:(NSArray *)arg2 channelIDs:(NSArray *)arg3;
- (void)shareBroadcastCoordinator:(PTVShareBroadcastCoordinator *)arg1 didShareWithAllFollowersWithSuccess:(_Bool)arg2 error:(NSError *)arg3;
- (void)shareBroadcastCoordinatorDidRetweetBroadcast:(PTVShareBroadcastCoordinator *)arg1 withSuccess:(_Bool)arg2 error:(NSError *)arg3 canRetry:(_Bool)arg4;
- (void)shareBroadcastCoordinatorWillRetweetBroadcast:(PTVShareBroadcastCoordinator *)arg1;
- (void)shareBroadcastCoordinator:(PTVShareBroadcastCoordinator *)arg1 didCompleteShareOnTwitterWithSuccess:(_Bool)arg2 error:(NSError *)arg3;
- (void)shareBroadcastCoordinator:(PTVShareBroadcastCoordinator *)arg1 didCompleteShareOnFacebookWithSuccess:(_Bool)arg2 error:(NSError *)arg3;
- (void)shareBroadcastCoordinator:(PTVShareBroadcastCoordinator *)arg1 failedToAssociateAccountWithModal:(PTVModalViewController *)arg2;
- (void)shareBroadcastCoordinator:(PTVShareBroadcastCoordinator *)arg1 mustFirstAssociateAccountWithModal:(PTVModalViewController *)arg2;
@end

