//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PeriscopeViewer/NSObject-Protocol.h>

@class PTVTooltipButton;

@protocol PTVTooltipButtonGroup <NSObject>

@optional
- (struct CGRect)fittingFrameForTooltipButton:(PTVTooltipButton *)arg1;
- (void)tooltipButtonDidHideTooltip:(PTVTooltipButton *)arg1;
- (void)tooltipButtonWillHideTooltip:(PTVTooltipButton *)arg1;
- (void)tooltipButtonDidShowTooltip:(PTVTooltipButton *)arg1;
- (void)tooltipButtonWillShowTooltip:(PTVTooltipButton *)arg1;
@end

