//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <YOLayout/YOView.h>

@interface PTVVipBadgeTooltip : YOView
{
    PTVVipBadgeTooltip *_weakSelf;
    double _arrowXOffset;
}

@property(nonatomic) double arrowXOffset; // @synthesize arrowXOffset=_arrowXOffset;
- (void).cxx_destruct;
- (void)learnMoreButtonDidTap;
- (void)closeButtonDidTap;
- (void)hide:(_Bool)arg1;
- (void)show;
- (void)viewInit;

@end

