//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface StallStatsCollection : NSObject
{
    _Bool _congestion;
    double _latency;
    double _watchTime;
    double _transitTime;
}

@property _Bool congestion; // @synthesize congestion=_congestion;
@property double transitTime; // @synthesize transitTime=_transitTime;
@property double watchTime; // @synthesize watchTime=_watchTime;
@property double latency; // @synthesize latency=_latency;
- (id)getStatisticsWithTag:(id)arg1;

@end

