//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNAdaptiveWizardStep.h>

#import <T1Twitter/T1AccountCreator-Protocol.h>
#import <T1Twitter/T1EnterEmailViewControllerDelegate-Protocol.h>
#import <T1Twitter/T1EnterPhoneViewControllerDelegate-Protocol.h>
#import <T1Twitter/T1VerifyPhoneViewControllerDelegate-Protocol.h>

@class NSString, TFNPhoneNumberFormatter;

@interface T1AdaptiveWizardSignUpWithPhoneOrEmailStep : TFNAdaptiveWizardStep <T1EnterEmailViewControllerDelegate, T1EnterPhoneViewControllerDelegate, T1VerifyPhoneViewControllerDelegate, T1AccountCreator>
{
    _Bool _poppedFirstViewController;
    _Bool _isVoiceSignUpEnabled;
    _Bool _byVoice;
    CDUnknownBlockType _didAddAccountBlock;
    TFNPhoneNumberFormatter *_phoneNumberFormatter;
}

@property(nonatomic) _Bool byVoice; // @synthesize byVoice=_byVoice;
@property(nonatomic) _Bool isVoiceSignUpEnabled; // @synthesize isVoiceSignUpEnabled=_isVoiceSignUpEnabled;
@property(nonatomic) _Bool poppedFirstViewController; // @synthesize poppedFirstViewController=_poppedFirstViewController;
@property(readonly, nonatomic) TFNPhoneNumberFormatter *phoneNumberFormatter; // @synthesize phoneNumberFormatter=_phoneNumberFormatter;
@property(copy, nonatomic) CDUnknownBlockType didAddAccountBlock; // @synthesize didAddAccountBlock=_didAddAccountBlock;
- (void).cxx_destruct;
- (id)_signUpErrorMessage:(id)arg1;
- (id)_autogeneratedPassword;
- (void)_createAccountWithPhoneSignUp:(_Bool)arg1;
- (void)_popAndPushEnterEmailViewController;
- (void)handleFailureWithError:(id)arg1;
- (void)handleSuccessWithMissingLoginToken;
- (void)handleSuccessWithAccount:(id)arg1;
@property(readonly, nonatomic) NSString *scribeSection;
- (void)_handleCompletePhoneVerificationError:(id)arg1 withScribeComponent:(id)arg2 scribeParameters:(id)arg3;
- (void)verifyPhoneViewController:(id)arg1 verifyPhoneWithForm:(id)arg2;
- (void)_resendVerificationCodeWithInfo:(id)arg1 byVoice:(_Bool)arg2;
- (void)didTapDidNotReceiveSMS:(id)arg1 sender:(id)arg2;
- (void)_handleBeginPhoneVerificationError:(id)arg1 scribePage:(id)arg2 scribeComponent:(id)arg3;
- (void)_beginPhoneVerification:(id)arg1;
- (void)enterPhoneViewControllerDidTapUseEmailInstead:(id)arg1;
- (void)enterPhoneViewController:(id)arg1 didTapShowAdvancedOptions:(id)arg2;
- (void)enterPhoneViewController:(id)arg1 enteredPhone:(id)arg2 normalizedPhone:(id)arg3 uiMetricResult:(id)arg4;
- (void)enterEmailViewController:(id)arg1 didTapShowAdvancedOptions:(id)arg2;
- (void)enterEmailViewControllerDidTapUsePhoneInstead:(id)arg1;
- (void)enterEmailViewController:(id)arg1 enteredEmail:(id)arg2 uiMetricResult:(id)arg3;
- (id)_signUpInfoProvider;
- (void)_scribeSimCardInformationWithCarrier:(id)arg1 scribePage:(id)arg2;
- (_Bool)_shouldShowEmailSignUpForCountryCode:(id)arg1;
- (void)evaluateWithController:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

