//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <T1Twitter/T1AmbientNotificationCenterDelegate-Protocol.h>

@class NSMutableSet, NSString, T1AmbientNotificationCenter, TFNTwitterAccount, UIView;
@protocol T1AmbientNotificationDelegate;

@interface T1AmbientNotificationViewController : UIViewController <T1AmbientNotificationCenterDelegate>
{
    struct CGRect _tabBarFrame;
    _Bool _keyboardIsVisible;
    TFNTwitterAccount *_account;
    id <T1AmbientNotificationDelegate> _delegate;
    T1AmbientNotificationCenter *_notificationCenter;
    UIView *_notificationContainerView;
    id _notificationCenterToken;
    NSMutableSet *_composeBars;
}

@property(retain, nonatomic) NSMutableSet *composeBars; // @synthesize composeBars=_composeBars;
@property(nonatomic) _Bool keyboardIsVisible; // @synthesize keyboardIsVisible=_keyboardIsVisible;
@property(retain, nonatomic) id notificationCenterToken; // @synthesize notificationCenterToken=_notificationCenterToken;
@property(retain, nonatomic) UIView *notificationContainerView; // @synthesize notificationContainerView=_notificationContainerView;
@property(retain, nonatomic) T1AmbientNotificationCenter *notificationCenter; // @synthesize notificationCenter=_notificationCenter;
@property(nonatomic) __weak id <T1AmbientNotificationDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)_t1_scribeNotificationCenterAction:(id)arg1;
- (void)ambientNotificationCenterMissingNotificationViewWindow:(id)arg1;
- (void)ambientNotificationCenterDidDropNotification:(id)arg1;
- (_Bool)ambientNotificationCenterContainerRequiresShortNotificationBanner:(id)arg1;
- (void)ambientNotificationCenterDidHide:(id)arg1;
- (void)ambientNotificationCenterWillShow:(id)arg1;
- (void)ambientNotificationCenterWillUpdateBanner:(id)arg1;
- (void)ambientNotificationCenterDidShow:(id)arg1;
- (_Bool)ambientNotificationCenterShouldNotify:(id)arg1;
- (void)ambientNotificationCenter:(id)arg1 rehostNotificationView:(id)arg2;
- (void)_t1_handleAmbientEvent:(id)arg1;
- (double)_t1_bottomLayoutGuideHeight;
- (id)_t1_composeBarsAtBottomLayoutGuide;
- (void)_t1_updatePositionAnimated:(_Bool)arg1;
- (_Bool)_t1_containerRequiresShortAmbientNotificationBanner;
- (void)_keyboardDidHide:(id)arg1;
- (void)_keyboardWillShow:(id)arg1;
- (void)_applicationWillEnterForeground;
- (void)_applicationDidEnterBackground;
- (void)clearQueueAndHide;
- (void)_removeComposeBar:(id)arg1;
- (void)_addComposeBar:(id)arg1 animated:(_Bool)arg2;
- (void)_inlineComposeBarWillHide:(id)arg1;
- (void)_inlineComposeBarWillShow:(id)arg1;
- (void)_inlineComposeBarDidMoveToWindow:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)didMoveToParentViewController:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)initWithNotificationCenter:(id)arg1 account:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

