//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class T1BroadcastGeoblockingController, TFNTwitterAccount, TFNTwitterBroadcast;
@protocol T1BroadcastContainerViewModelDelegate, T1PlayerFactoryIdentifiable, TFNTwitterCardDataSource;

@interface T1BroadcastContainerViewModel : NSObject
{
    _Bool _shouldAutoplay;
    _Bool _requestingLocationUpdate;
    TFNTwitterBroadcast *_broadcast;
    TFNTwitterAccount *_account;
    id <T1BroadcastContainerViewModelDelegate> _delegate;
    id <TFNTwitterCardDataSource> _cardDataSource;
    T1BroadcastGeoblockingController *_geoblockingController;
}

@property(nonatomic) _Bool requestingLocationUpdate; // @synthesize requestingLocationUpdate=_requestingLocationUpdate;
@property(retain, nonatomic) T1BroadcastGeoblockingController *geoblockingController; // @synthesize geoblockingController=_geoblockingController;
@property(retain, nonatomic) id <TFNTwitterCardDataSource> cardDataSource; // @synthesize cardDataSource=_cardDataSource;
@property(nonatomic) __weak id <T1BroadcastContainerViewModelDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool shouldAutoplay; // @synthesize shouldAutoplay=_shouldAutoplay;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(readonly, nonatomic) TFNTwitterBroadcast *broadcast; // @synthesize broadcast=_broadcast;
- (void).cxx_destruct;
- (void)_t1_postUpdate;
- (double)timecodeForPlaybackState:(id)arg1;
- (void)requestLocationUpdate;
@property(readonly, nonatomic) id <T1PlayerFactoryIdentifiable> playerFactoryIdentifiable;
- (id)playerCacheEntryWithInitialScribeContext:(id)arg1;
@property(readonly, nonatomic) long long state;
- (_Bool)isEqualToBroadcastContainerViewModel:(id)arg1;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithBroadcast:(id)arg1 account:(id)arg2 cardDataSource:(id)arg3;
- (id)init;

@end

