//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface T1CarouselStatusViewLayoutSpec : NSObject
{
}

+ (double)bottomPaddingForOptions:(unsigned long long)arg1 layoutMetrics:(id)arg2;
+ (double)photoVideoAspectRatio;
+ (struct UIEdgeInsets)authorEdgeInsetsForAvatarShowing:(_Bool)arg1;
+ (struct UIEdgeInsets)inlineActionsEdgeInsets;
+ (struct UIEdgeInsets)infoTextEdgeInsets;
+ (struct UIEdgeInsets)bodyTextEdgeInsets;
+ (struct UIEdgeInsets)avatarEdgeInsets;
+ (struct UIEdgeInsets)cardContentEdgeInsets;
+ (struct UIEdgeInsets)contentEdgeInsets;
+ (struct UIEdgeInsets)displayAreaEdgeInsetsForLayoutMetrics:(id)arg1;
+ (_Bool)isEmbeddedStatusForOptions:(unsigned long long)arg1;
+ (id)infoTextFont;
+ (struct CGSize)infoTextBadgeSize;
+ (unsigned long long)carouselDisplayTextOptionsForStatusOptions:(unsigned long long)arg1 attachmentType:(unsigned long long)arg2;
+ (unsigned long long)bodyTextLinesForOptions:(unsigned long long)arg1 attachmentType:(unsigned long long)arg2;

@end

