//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNCollectionViewCell.h>

@class T1CombinedSignUpHeaderView;

@interface T1CombinedSignUpHeaderCollectionViewCell : TFNCollectionViewCell
{
    T1CombinedSignUpHeaderView *_headerView;
}

@property(retain, nonatomic) T1CombinedSignUpHeaderView *headerView; // @synthesize headerView=_headerView;
- (void).cxx_destruct;
- (void)cleanup;
- (void)layoutSubviews;

@end

