//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UILabel;

@interface T1CombinedSignUpHeaderView : UIView
{
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
}

+ (id)tfn_defaultDataViewAdapter;
+ (double)heightForTitle:(id)arg1 subtitle:(id)arg2 layoutMetrics:(id)arg3;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)private_applyFonts;
@property(readonly, nonatomic) NSString *subtitle;
@property(readonly, nonatomic) NSString *title;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2;

@end

