//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TwitterAVCore/TAVControlBarItem.h>

@class UIButton, UIImage;

@interface T1ControlBarMuteButton : TAVControlBarItem
{
    UIButton *_button;
    UIImage *_muteImage;
    UIImage *_unmuteImage;
}

@property(retain, nonatomic) UIImage *unmuteImage; // @synthesize unmuteImage=_unmuteImage;
@property(retain, nonatomic) UIImage *muteImage; // @synthesize muteImage=_muteImage;
@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
- (void).cxx_destruct;
- (void)_t1_didTapMuteButton;
- (void)t1_updateButtonState;
- (void)player:(id)arg1 didUpdatePlaybackState:(id)arg2;
- (id)view;
- (id)initWithIdentifier:(id)arg1;

@end

