//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNItemsTableRowAdapter.h>

@interface T1CustomTimelineTableRowAdapter : TFNItemsTableRowAdapter
{
    _Bool _showsLongPressContextMenu;
    _Bool _showsAuthor;
    _Bool _showsDescription;
    CDUnknownBlockType _tapBlock;
}

@property(copy, nonatomic) CDUnknownBlockType tapBlock; // @synthesize tapBlock=_tapBlock;
@property(nonatomic) _Bool showsDescription; // @synthesize showsDescription=_showsDescription;
@property(nonatomic) _Bool showsAuthor; // @synthesize showsAuthor=_showsAuthor;
@property(nonatomic) _Bool showsLongPressContextMenu; // @synthesize showsLongPressContextMenu=_showsLongPressContextMenu;
- (void).cxx_destruct;
- (void)dataViewController:(id)arg1 didSelectItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (id)dataViewController:(id)arg1 tableViewCellForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (double)dataViewController:(id)arg1 tableViewHeightForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;

@end

