//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class T1DirectMessageEntryStickerCell;
@protocol TFNDirectMessageEntry, TFNDirectMessageStickerAttachment;

@protocol T1DirectMessageEntryStickerCellDelegate
- (void)cell:(T1DirectMessageEntryStickerCell *)arg1 didLongPressStickerAttachment:(id <TFNDirectMessageStickerAttachment>)arg2 ofMessage:(id <TFNDirectMessageEntry>)arg3 rect:(struct CGRect)arg4;
- (void)cell:(T1DirectMessageEntryStickerCell *)arg1 didTapStickerAttachment:(id <TFNDirectMessageStickerAttachment>)arg2 ofMessage:(id <TFNDirectMessageEntry>)arg3 rect:(struct CGRect)arg4;
@end

