//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@protocol T1DirectMessageConversationAddPeopleBehaviorDelegate;

@interface T1DirectMessageConversationAddPeopleBehavior : NSObject
{
    // Error parsing type: , name: account
    // Error parsing type: , name: conversation
    // Error parsing type: , name: sourceViewController
    // Error parsing type: , name: presentedUserPicker
    // Error parsing type: , name: showAmbientNotificationOnSuccess
    // Error parsing type: , name: delegate
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)presentAddPeople:(id)arg1;
- (id)initWithViewController:(id)arg1 conversation:(id)arg2 account:(id)arg3;
@property(nonatomic) __weak id <T1DirectMessageConversationAddPeopleBehaviorDelegate> delegate; // @synthesize delegate;
@property(nonatomic) _Bool showAmbientNotificationOnSuccess; // @synthesize showAmbientNotificationOnSuccess;

@end

