//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

#import <T1Twitter/T1DirectMessageAvatarCellActions-Protocol.h>
#import <T1Twitter/T1DirectMessageConversationCellActions-Protocol.h>
#import <T1Twitter/T1DirectMessageConversationHost-Protocol.h>
#import <T1Twitter/T1DirectMessageConversationParticipantsListViewControllerDelegate-Protocol.h>
#import <T1Twitter/T1DirectMessageInboxAddressBookPromptModuleDelegate-Protocol.h>
#import <T1Twitter/T1DirectMessageInboxConversationActions-Protocol.h>
#import <T1Twitter/T1DirectMessageInboxHeaderActions-Protocol.h>
#import <T1Twitter/T1DirectMessageMasterSplitView-Protocol.h>
#import <T1Twitter/T1DirectMessageTopUsersViewControllerDelegate-Protocol.h>
#import <T1Twitter/T1JumpBackToHomeTimelineBehavior-Protocol.h>
#import <T1Twitter/T1PeopleAddressBookViewControllerDelegate-Protocol.h>
#import <T1Twitter/TFNPushedSplitViewControllerDelegate-Protocol.h>
#import <T1Twitter/TFNScopedContainerViewControllerDelegate-Protocol.h>

@class NSArray, NSString, T1DirectMessageConversation, T1DirectMessageInbox, T1DirectMessageInboxModulesViewController, T1DirectMessagePrefetchUsersDataSource, T1DirectMessageTopUsersViewController, T1EmptyContentViewController, TFNFloatingActionButtonItem, TFNItemsDataViewController, TFNScopedContainerViewController, TFNTwitterAccount, UIBarButtonItem;

@interface T1DirectMessageInboxViewController : TFNViewController <T1DirectMessageTopUsersViewControllerDelegate, T1DirectMessageConversationHost, T1DirectMessageInboxConversationActions, T1DirectMessageConversationCellActions, T1DirectMessageAvatarCellActions, T1DirectMessageInboxAddressBookPromptModuleDelegate, T1PeopleAddressBookViewControllerDelegate, T1DirectMessageInboxHeaderActions, TFNScopedContainerViewControllerDelegate, T1DirectMessageConversationParticipantsListViewControllerDelegate, T1JumpBackToHomeTimelineBehavior, TFNPushedSplitViewControllerDelegate, T1DirectMessageMasterSplitView>
{
    _Bool _didShowAddressBookFollowAmbientNotification;
    _Bool _clearsSelectionOnViewWillAppear;
    _Bool _scopeBarHidden;
    NSArray *_prefetchUsers;
    TFNTwitterAccount *_account;
    UIBarButtonItem *_composeBarButtonItem;
    T1DirectMessageInbox *_messageInbox;
    T1DirectMessageConversation *_selectedConversation;
    T1DirectMessagePrefetchUsersDataSource *_prefetchUsersDataSource;
    id _prefetchUsersObserver;
    TFNScopedContainerViewController *_contentViewController;
    T1DirectMessageInboxModulesViewController *_trustedConversationInboxModulesViewController;
    T1DirectMessageInboxModulesViewController *_trustedConversationsViewController;
    T1DirectMessageInboxModulesViewController *_untrustedConversationsViewController;
    T1DirectMessageTopUsersViewController *_topUsersViewController;
    T1EmptyContentViewController *_emptyInboxViewController;
    T1EmptyContentViewController *_untrustedConversationsEmptyViewController;
    T1EmptyContentViewController *_emptyDetailViewController;
    TFNItemsDataViewController *_loadingViewController;
    TFNFloatingActionButtonItem *_composeNewDMFABItem;
}

@property(nonatomic) _Bool scopeBarHidden; // @synthesize scopeBarHidden=_scopeBarHidden;
@property(retain, nonatomic) TFNFloatingActionButtonItem *composeNewDMFABItem; // @synthesize composeNewDMFABItem=_composeNewDMFABItem;
@property(nonatomic) __weak TFNItemsDataViewController *loadingViewController; // @synthesize loadingViewController=_loadingViewController;
@property(nonatomic) __weak T1EmptyContentViewController *emptyDetailViewController; // @synthesize emptyDetailViewController=_emptyDetailViewController;
@property(nonatomic) __weak T1EmptyContentViewController *untrustedConversationsEmptyViewController; // @synthesize untrustedConversationsEmptyViewController=_untrustedConversationsEmptyViewController;
@property(nonatomic) __weak T1EmptyContentViewController *emptyInboxViewController; // @synthesize emptyInboxViewController=_emptyInboxViewController;
@property(nonatomic) __weak T1DirectMessageTopUsersViewController *topUsersViewController; // @synthesize topUsersViewController=_topUsersViewController;
@property(nonatomic) __weak T1DirectMessageInboxModulesViewController *untrustedConversationsViewController; // @synthesize untrustedConversationsViewController=_untrustedConversationsViewController;
@property(nonatomic) __weak T1DirectMessageInboxModulesViewController *trustedConversationsViewController; // @synthesize trustedConversationsViewController=_trustedConversationsViewController;
@property(nonatomic) __weak T1DirectMessageInboxModulesViewController *trustedConversationInboxModulesViewController; // @synthesize trustedConversationInboxModulesViewController=_trustedConversationInboxModulesViewController;
@property(retain, nonatomic) TFNScopedContainerViewController *contentViewController; // @synthesize contentViewController=_contentViewController;
@property(nonatomic) _Bool clearsSelectionOnViewWillAppear; // @synthesize clearsSelectionOnViewWillAppear=_clearsSelectionOnViewWillAppear;
@property(nonatomic) _Bool didShowAddressBookFollowAmbientNotification; // @synthesize didShowAddressBookFollowAmbientNotification=_didShowAddressBookFollowAmbientNotification;
@property(retain, nonatomic) id prefetchUsersObserver; // @synthesize prefetchUsersObserver=_prefetchUsersObserver;
@property(retain, nonatomic) T1DirectMessagePrefetchUsersDataSource *prefetchUsersDataSource; // @synthesize prefetchUsersDataSource=_prefetchUsersDataSource;
@property(retain, nonatomic) T1DirectMessageConversation *selectedConversation; // @synthesize selectedConversation=_selectedConversation;
@property(retain, nonatomic) T1DirectMessageInbox *messageInbox; // @synthesize messageInbox=_messageInbox;
@property(retain, nonatomic) UIBarButtonItem *composeBarButtonItem; // @synthesize composeBarButtonItem=_composeBarButtonItem;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)_presentUserProfile:(id)arg1;
- (id)tfn_floatingActionButtonItems;
- (void)scopedContainerViewController:(id)arg1 didSelectViewControllerAtIndex:(long long)arg2;
- (id)scopedContainerViewController:(id)arg1 titleForSegmentAtIndex:(long long)arg2;
- (void)avatarCellDidTapAvatar:(id)arg1;
- (void)didTapAvatarForConversation:(id)arg1 sender:(id)arg2;
- (void)loadMoreConversationsWithCursor:(id)arg1;
- (void)showContextMenuForConversation:(id)arg1 sender:(id)arg2;
- (void)_showMuteOptions:(id)arg1;
- (void)markConversationAsSeen:(id)arg1;
- (void)disableNotificationsForConversation:(id)arg1;
- (void)enableNotificationsForConversation:(id)arg1;
- (void)reportConversation:(id)arg1;
- (void)deleteConversation:(id)arg1;
- (id)previewConversation:(id)arg1;
- (void)viewConversation:(id)arg1;
- (void)presentConversation:(id)arg1 text:(id)arg2 welcomeMessageID:(id)arg3 fromRect:(struct CGRect)arg4 inView:(id)arg5 options:(unsigned long long)arg6 animated:(_Bool)arg7 completion:(CDUnknownBlockType)arg8;
- (void)_presentConversation:(id)arg1 text:(id)arg2 welcomeMessageID:(id)arg3 fromRect:(struct CGRect)arg4 inView:(id)arg5 options:(unsigned long long)arg6 animated:(_Bool)arg7 completion:(CDUnknownBlockType)arg8;
- (void)pushedSplitViewController:(id)arg1 didPopDetailViewController:(id)arg2;
- (void)pushedSplitViewController:(id)arg1 didChangeToDisplayMode:(long long)arg2;
- (void)pushedSplitViewController:(id)arg1 willChangeToDisplayMode:(long long)arg2;
- (void)scrollToTop;
- (void)showDetailViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (id)_viewControllerForTab:(unsigned long long)arg1;
- (void)_unseenCountDidChange:(id)arg1;
- (void)_userDidLoad:(id)arg1;
- (void)_updateButtons;
- (void)_updateScopeBar;
- (void)_updateContentViewControllers;
- (void)_showSelectedConversation;
- (_Bool)_shouldShowEmptyDetailViewForDisplayMode:(long long)arg1;
- (void)_showEmptyDetailViewIfNecessaryForDisplayMode:(long long)arg1;
- (void)_hideEmptyDetailViewIfNecessaryForDisplayMode:(long long)arg1;
- (void)_updateEmptyDetailView;
- (_Bool)_shouldShowScopeBar;
- (void)_refresh;
- (void)_directMessageContextDidReset:(id)arg1;
- (void)_inboxDidReset:(id)arg1;
- (void)_inboxDidRefresh:(id)arg1;
- (void)_inboxDidRemoveConversation:(id)arg1;
- (void)_inboxDidAddConversation:(id)arg1;
- (id)_loadLoadingViewController;
- (id)_loadEmptyDetailViewController;
- (id)_loadUntrustedConversationsEmptyViewController;
- (id)_loadEmptyInboxViewController;
- (id)_loadTopUsersViewController;
- (id)_loadUntrustedConversationsViewController;
- (id)_loadTrustedConversationsViewController;
- (id)_loadTrustedConversationInboxModulesViewController;
- (void)_composeNewDirectMessage:(id)arg1;
- (void)_contextDidBecomeInactive:(id)arg1;
- (void)_contextDidBecomeActive:(id)arg1;
- (void)_clearInvalidSelectedConversation;
- (void)handleComposeMessageKeyCommand;
- (id)keyCommands;
- (_Bool)canBecomeFirstResponder;
- (void)headerDidTapInlineAction;
- (void)peopleAddressBookViewController:(id)arg1 didFollowUser:(id)arg2;
- (void)addressBookPromptModuleDidTapNavigateToContacts;
- (void)setTfn_sendContentScrollEventsToParentViewController:(_Bool)arg1;
- (_Bool)t1_showsSearchAction;
- (_Bool)t1_showsComposeAction;
- (void)directMessageConversationParticipantsListViewController:(id)arg1 didSelectUser:(id)arg2;
- (void)directMessageTopUsersViewController:(id)arg1 didSelectUser:(id)arg2 atIndexPath:(id)arg3;
- (id)scribeParameters:(id)arg1;
- (id)scribeComponent;
- (id)scribeSection;
- (id)scribePage;
- (id)scribe;
- (void)tfn_addDirectlyOwnedViewControllersToMutableArray:(id)arg1;
- (_Bool)tfn_prefersNavigationBarShadowHidden;
- (void)tfn_contentScrollViewWillBeginDragging:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewWillFullyDisappear:(_Bool)arg1;
- (void)viewWillFullyAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)didMoveToParentViewController:(id)arg1;
@property(readonly, nonatomic) NSArray *loadedInboxModulesViewControllers;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) NSArray *prefetchUsers; // @synthesize prefetchUsers=_prefetchUsers;
- (void)composeNewDirectMessage;
- (void)_removeMessageInboxNotificationObserver;
- (id)initWithAccount:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

