//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class T1DirectMessageComposerInterstitialView;

@protocol T1DirectMessageComposerInterstitialViewDelegate
- (void)directMessageComposerInterstitialViewDidTapReport:(T1DirectMessageComposerInterstitialView *)arg1;
- (void)directMessageComposerInterstitialViewDidTapDelete:(T1DirectMessageComposerInterstitialView *)arg1;
- (void)directMessageComposerInterstitialViewDidTapAccept:(T1DirectMessageComposerInterstitialView *)arg1;
@end

