//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface T1DirectMessageTypeaheadDataSource : NSObject
{
    // Error parsing type: , name: account
    // Error parsing type: , name: suggestionsDataSource
    // Error parsing type: , name: searchDataSource
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)itemsWithLimit:(long long)arg1 query:(id)arg2 allowedItemTypes:(unsigned long long)arg3 updateBlock:(CDUnknownBlockType)arg4;
- (id)initWithNewConversationSuggestionsForAccount:(id)arg1 existingUserReferences:(id)arg2;

@end

