//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1DirectMessageConversationHostViewController.h>

#import <T1Twitter/T1DirectMessageComposeViewControllerDelegate-Protocol.h>

@interface T1DirectMessageConversationHostViewController (T1Twitter) <T1DirectMessageComposeViewControllerDelegate>
- (void)directMessageComposeViewControllerTextViewDidChange:(id)arg1;
- (void)directMessageComposeViewControllerDidEndEditing:(id)arg1;
- (void)directMessageComposeViewControllerDidTapSend:(id)arg1;
@end

