//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <T1Twitter/TFNLayoutMetricsEnvironment-Protocol.h>

@class NSString, T1DirectMessageAvatarImageView, TFNSpacerView, UIImageView, UILabel, UIStackView;

@interface T1DirectMessageTypeaheadView : UIView <TFNLayoutMetricsEnvironment>
{
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UILabel *_socialTextLabel;
    T1DirectMessageAvatarImageView *_avatarImageView;
    UIImageView *_userBadgeImageView;
    UIStackView *_socialTextRow;
    UIStackView *_resultRow;
    TFNSpacerView *_containerView;
}

+ (_Bool)requiresConstraintBasedLayout;
+ (double)heightForLayoutMetrics:(id)arg1 includingSocialText:(_Bool)arg2;
@property(readonly, nonatomic) TFNSpacerView *containerView; // @synthesize containerView=_containerView;
@property(readonly, nonatomic) UIStackView *resultRow; // @synthesize resultRow=_resultRow;
@property(readonly, nonatomic) UIStackView *socialTextRow; // @synthesize socialTextRow=_socialTextRow;
@property(readonly, nonatomic) UIImageView *userBadgeImageView; // @synthesize userBadgeImageView=_userBadgeImageView;
@property(readonly, nonatomic) T1DirectMessageAvatarImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(readonly, nonatomic) UILabel *socialTextLabel; // @synthesize socialTextLabel=_socialTextLabel;
@property(readonly, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)layoutMetricsDidChange:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

