//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

@class T1DirectMessageComposeQuotedStatusPreviewView, TFNTwitterAccount, TFNTwitterStatus;
@protocol T1DirectMessageComposeQuotedStatusPreviewControllerDelegate;

@interface T1DirectMessageComposeQuotedStatusPreviewController : TFNViewController
{
    // Error parsing type: , name: account
    // Error parsing type: , name: delegate
    // Error parsing type: , name: previewView
    // Error parsing type: , name: status
    // Error parsing type: , name: textChangeDetectionTimer
    // Error parsing type: , name: pendingRequest
    // Error parsing type: , name: lastDetectedStatusIDs
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)cancelPendingQuotedStatusPreviewRequest;
- (void)changeQuotedStatusPreviewIfNeeded:(id)arg1;
- (void)loadView;
- (id)initWithCoder:(id)arg1;
- (id)initWithAccount:(id)arg1;
@property(nonatomic, retain) TFNTwitterStatus *status; // @synthesize status;
@property(nonatomic, readonly) T1DirectMessageComposeQuotedStatusPreviewView *previewView; // @synthesize previewView;
@property(nonatomic) __weak id <T1DirectMessageComposeQuotedStatusPreviewControllerDelegate> delegate; // @synthesize delegate;
@property(nonatomic, retain) TFNTwitterAccount *account; // @synthesize account;

@end

