//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1DirectMessageEntryBaseCell.h>

@class T1DirectMessageAbstractConversationEntryViewModel;
@protocol T1DirectMessageAbstractEntryCellDelegate;

@interface T1DirectMessageEntryStickerCell : T1DirectMessageEntryBaseCell
{
    // Error parsing type: , name: stickerDelegate
    // Error parsing type: , name: sticker
    // Error parsing type: , name: stickerView
    // Error parsing type: , name: stickerLoadingView
    // Error parsing type: , name: stickerViewContainer
    // Error parsing type: , name: stickerHeightConstraint
    // Error parsing type: , name: bounceAnimation
}

- (CDUnknownBlockType).cxx_destruct;
- (void)didLongPressSticker:(id)arg1;
- (void)didTapSticker:(id)arg1;
- (void)performEntranceAnimationWithCompletion:(CDUnknownBlockType)arg1;
- (void)updateConstraints;
@property(nonatomic, retain) T1DirectMessageAbstractConversationEntryViewModel *entryViewModel;
@property(nonatomic) __weak id <T1DirectMessageAbstractEntryCellDelegate> delegate;
- (id)initWithFrame:(struct CGRect)arg1;

@end

