//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFSUtilities/TFSConcurrentOperation.h>

@class TFNTwitter;

@interface T1ExternallyBlockedUserContentEradicationOperation : TFSConcurrentOperation
{
    TFNTwitter *_twitter;
}

@property(retain, nonatomic) TFNTwitter *twitter; // @synthesize twitter=_twitter;
- (void).cxx_destruct;
- (void)private_updateBlockIDsAndEradicate:(id)arg1;
- (void)run;
- (id)initWithTwitterApp:(id)arg1;

@end

