//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNItemsDataViewSectionController.h>

@class NSMutableArray, TFNTwitterFeedbackModule;
@protocol TFNTwitterDismissibleItem;

@interface T1FeedbackSectionController : TFNItemsDataViewSectionController
{
    id <TFNTwitterDismissibleItem> _itemToDismiss;
    NSMutableArray *_prompts;
}

@property(retain, nonatomic) NSMutableArray *prompts; // @synthesize prompts=_prompts;
@property(readonly, nonatomic) id <TFNTwitterDismissibleItem> itemToDismiss; // @synthesize itemToDismiss=_itemToDismiss;
- (void).cxx_destruct;
- (void)_sendFeedbackForAccountIfNeeded:(id)arg1;
- (id)calculatedLayoutMetricsForItem:(id)arg1 atIndexPath:(id)arg2;
- (void)showConfirmationForFeedback:(id)arg1;
- (unsigned long long)sectionBreaksForItem:(id)arg1 atIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (_Bool)isLogicalSectionController;
- (void)didMoveToDataViewController:(id)arg1;
@property(readonly, nonatomic) TFNTwitterFeedbackModule *feedbackModule;
- (id)initWithItemToDismiss:(id)arg1;

@end

