//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

#import <T1Twitter/TFNPresented-Protocol.h>
#import <T1Twitter/TFNTwitterAuthenticated-Protocol.h>
#import <T1Twitter/UIScrollViewDelegate-Protocol.h>

@class NSString, T1AnimatedGIFImageView, T1FoundMediaImagePreviewOverlayView, T1FoundMediaItemAttributionView, T1MediaAttachmentProgressView, TFNAnimatedGifImage, TFNAnimatedGifImageView, TFNButton, TFNFoundMediaFetchOperation, TFNFoundMediaItem, TFNFullscreenMediaTransition, TFNPaddedButton, TFNTwitterAccount, UIImage, UILongPressGestureRecognizer, UIScrollView, UITapGestureRecognizer, UIView, UIViewController;
@protocol T1FoundMediaImagePreviewViewControllerDelegate, TFNImageTransitionDelegate;

@interface T1FoundMediaImagePreviewViewController : TFNViewController <TFNPresented, UIScrollViewDelegate, TFNTwitterAuthenticated>
{
    _Bool _imageFetchOperationFailed;
    TFNTwitterAccount *_account;
    id <T1FoundMediaImagePreviewViewControllerDelegate> _delegate;
    TFNFoundMediaItem *_item;
    T1AnimatedGIFImageView *_imagePreviewView;
    T1MediaAttachmentProgressView *_progressView;
    double _imageFetchOperationProgress;
    TFNPaddedButton *_closeButton;
    TFNButton *_addButton;
    T1FoundMediaItemAttributionView *_attributionView;
    T1FoundMediaImagePreviewOverlayView *_overlayView;
    UITapGestureRecognizer *_imagePreviewViewTapGestureRecognizer;
    UILongPressGestureRecognizer *_attributionLongPressGestureRecognizer;
    TFNFullscreenMediaTransition *_transition;
    TFNAnimatedGifImageView *_presentingTransitionImageView;
    UIViewController *_dismissingFromInHierarchyPresentingViewController;
    TFNFoundMediaFetchOperation *_imageFetchOperation;
    TFNAnimatedGifImage *_fullAnimatedGIFImage;
    UIImage *_previewImage;
    UIView *_backgroundView;
    UIScrollView *_scrollView;
    struct CGPoint _initialContentOffset;
}

@property(nonatomic) struct CGPoint initialContentOffset; // @synthesize initialContentOffset=_initialContentOffset;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIImage *previewImage; // @synthesize previewImage=_previewImage;
@property(retain, nonatomic) TFNAnimatedGifImage *fullAnimatedGIFImage; // @synthesize fullAnimatedGIFImage=_fullAnimatedGIFImage;
@property(retain, nonatomic) TFNFoundMediaFetchOperation *imageFetchOperation; // @synthesize imageFetchOperation=_imageFetchOperation;
@property(retain, nonatomic) UIViewController *dismissingFromInHierarchyPresentingViewController; // @synthesize dismissingFromInHierarchyPresentingViewController=_dismissingFromInHierarchyPresentingViewController;
@property(retain, nonatomic) TFNAnimatedGifImageView *presentingTransitionImageView; // @synthesize presentingTransitionImageView=_presentingTransitionImageView;
@property(retain, nonatomic) TFNFullscreenMediaTransition *transition; // @synthesize transition=_transition;
@property(retain, nonatomic) UILongPressGestureRecognizer *attributionLongPressGestureRecognizer; // @synthesize attributionLongPressGestureRecognizer=_attributionLongPressGestureRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *imagePreviewViewTapGestureRecognizer; // @synthesize imagePreviewViewTapGestureRecognizer=_imagePreviewViewTapGestureRecognizer;
@property(retain, nonatomic) T1FoundMediaImagePreviewOverlayView *overlayView; // @synthesize overlayView=_overlayView;
@property(retain, nonatomic) T1FoundMediaItemAttributionView *attributionView; // @synthesize attributionView=_attributionView;
@property(retain, nonatomic) TFNButton *addButton; // @synthesize addButton=_addButton;
@property(retain, nonatomic) TFNPaddedButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) double imageFetchOperationProgress; // @synthesize imageFetchOperationProgress=_imageFetchOperationProgress;
@property(nonatomic) _Bool imageFetchOperationFailed; // @synthesize imageFetchOperationFailed=_imageFetchOperationFailed;
@property(retain, nonatomic) T1MediaAttachmentProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) T1AnimatedGIFImageView *imagePreviewView; // @synthesize imagePreviewView=_imagePreviewView;
@property(retain, nonatomic) TFNFoundMediaItem *item; // @synthesize item=_item;
@property(nonatomic) __weak id <T1FoundMediaImagePreviewViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)dismissAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)presentFromViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)_setOverlayViewHidden:(_Bool)arg1 animated:(_Bool)arg2;
- (void)_handleImagePreviewViewTap:(id)arg1;
- (void)_handleAttributionLongPress:(id)arg1;
- (void)_didTapAdd:(id)arg1;
- (void)_cancelWithTransitionAnimated:(_Bool)arg1;
- (void)_didTapCancel:(id)arg1;
- (void)_updateImagePreviewView;
- (void)_updateProgressView;
- (void)_stopUpdating;
- (void)_updateFullAnimatedGIFImage;
- (void)_updateAttributionView;
@property(retain, nonatomic) TFNAnimatedGifImageView *transitionSourceAnimatedGIFImageView;
@property(nonatomic) __weak id <TFNImageTransitionDelegate> transitionDelegate;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

