//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class TFNTwitterPushNotificationPayload, TFNTwitterStatus, TFNTwitterUser;

@interface T1HydratedPushNotificationPayload : NSObject
{
    TFNTwitterPushNotificationPayload *_pushPayload;
    TFNTwitterUser *_senderUser;
    TFNTwitterStatus *_targetStatus;
}

@property(readonly, nonatomic) TFNTwitterStatus *targetStatus; // @synthesize targetStatus=_targetStatus;
@property(readonly, nonatomic) TFNTwitterUser *senderUser; // @synthesize senderUser=_senderUser;
@property(readonly, nonatomic) TFNTwitterPushNotificationPayload *pushPayload; // @synthesize pushPayload=_pushPayload;
- (void).cxx_destruct;
- (id)ambientMessage;
- (id)navigationContext;
- (id)initWithPushNotificationPayload:(id)arg1 senderUser:(id)arg2 targetStatus:(id)arg3;

@end

