//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@protocol T1InlineMediaViewModel <NSObject>
- (unsigned long long)viewCount;
- (double)pillViewTimeInterval;
- (unsigned long long)playerIconViewTypeWithStickerBadgeEnabled:(_Bool)arg1 threeSixtyVideoEnabled:(_Bool)arg2 bumperPrerollEnabled:(_Bool)arg3 isVideoAd:(_Bool)arg4;
@end

