//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <T1Twitter/TFNCellVisibilityListener-Protocol.h>

@class NSDate, NSDictionary, NSString, TFNTwitterScribe, TFSTimer, TFSTwitterScribeContext;
@protocol TFNTwitterScribeImpressionCache, TFSTwitterScribableItem;

@interface T1LingerScriber : NSObject <TFNCellVisibilityListener>
{
    id <TFNTwitterScribeImpressionCache> _impressionCache;
    TFNTwitterScribe *_scribe;
    TFSTwitterScribeContext *_scribeContext;
    id <TFSTwitterScribableItem> _target;
    NSDictionary *_itemParameters;
    NSDate *_lingerStart;
    _Bool _didLinger;
    _Bool _forceFirstImpression;
    TFSTimer *_lingerTimer;
    TFSTimer *_updateImpressionDurationTimer;
    unsigned long long _updateImpressionDuration;
}

- (void).cxx_destruct;
- (void)_resetLingerStart;
- (void)_resetUpdateImpressionDurationTimer;
- (void)_resetLingerTimer;
- (void)_updateImpressionDuration;
- (void)_recordLingerInImpressionCache;
- (id)_cacheEntryForItem:(id)arg1 startTime:(id)arg2 fallbackImpressionDuration:(unsigned long long)arg3;
- (void)_invokeLingerIfNeeded;
- (_Bool)_visibilityCriteriaMetForCell:(id)arg1 withVisibilityPercentage:(double)arg2;
- (void)cellDidEndDisplaying:(id)arg1 inDataViewController:(id)arg2;
- (void)cellDidDisplay:(id)arg1 inDataViewController:(id)arg2 withVisibilityPercentage:(double)arg3 visibilityState:(unsigned long long)arg4;
- (void)dealloc;
- (id)initWithScribe:(id)arg1 target:(id)arg2 scribeContext:(id)arg3 impressionCache:(id)arg4 itemParameters:(id)arg5 updateImpressionDurationAfter:(unsigned long long)arg6;
- (id)initWithScribe:(id)arg1 target:(id)arg2 scribeContext:(id)arg3 impressionCache:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

