//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSDictionary, T1LiveVideoTimelineViewController, TFNTwitterLiveVideoEvent;

@protocol T1LiveVideoTimelineViewControllerDelegate <NSObject>
- (void)liveVideoTimelineViewController:(T1LiveVideoTimelineViewController *)arg1 didUpdateWithPrompts:(NSDictionary *)arg2;
- (void)liveVideoTimelineViewController:(T1LiveVideoTimelineViewController *)arg1 didUpdateWithNewEvent:(TFNTwitterLiveVideoEvent *)arg2;

@optional
- (void)liveVideoTimelineViewController:(T1LiveVideoTimelineViewController *)arg1 didRequestCurrentVideoTimestampMSWithCompletion:(void (^)(NSNumber *))arg2;
- (_Bool)liveVideoTimelineShouldStopPollingWhenDisappearing:(T1LiveVideoTimelineViewController *)arg1;
- (void)liveVideoTimelineLoadTopDidEnd:(T1LiveVideoTimelineViewController *)arg1;
@end

