//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1LiveVideoContentViewTheme.h>

@interface T1LiveVideoContentViewTileTheme : T1LiveVideoContentViewTheme
{
}

- (id)badgeBackgroundColorInLiveState;
- (id)badgeBackgroundColor;
- (id)badgeFontInLiveState;
- (id)badgeFont;
- (id)badgeTextColorInLiveState;
- (id)badgeTextColor;

@end

