//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1ResizableHeaderView.h>

#import <T1Twitter/T1LiveVideoPlayerChromeControllerDataSource-Protocol.h>
#import <T1Twitter/UIGestureRecognizerDelegate-Protocol.h>

@class NSString, T1LiveVideoContentView, T1LiveVideoPlayerChromeController, TFNTwitterAVControlBar, UIButton, UITapGestureRecognizer;
@protocol T1LiveVideoContentViewLayoutDelegate, T1LiveVideoHeaderViewDelegate;

@interface T1LiveVideoHeaderView : T1ResizableHeaderView <UIGestureRecognizerDelegate, T1LiveVideoPlayerChromeControllerDataSource>
{
    _Bool _shouldShowNavBarDockButton;
    T1LiveVideoPlayerChromeController *_chromeController;
    T1LiveVideoContentView *_liveVideoContentView;
    TFNTwitterAVControlBar *_controlBar;
    UIButton *_navBarDockButton;
    double _topMargin;
    UITapGestureRecognizer *_headerTapGestureRecognizer;
    id <T1LiveVideoContentViewLayoutDelegate> _liveVideoContentViewLayoutDelegate;
}

@property(retain, nonatomic) id <T1LiveVideoContentViewLayoutDelegate> liveVideoContentViewLayoutDelegate; // @synthesize liveVideoContentViewLayoutDelegate=_liveVideoContentViewLayoutDelegate;
@property(retain, nonatomic) UITapGestureRecognizer *headerTapGestureRecognizer; // @synthesize headerTapGestureRecognizer=_headerTapGestureRecognizer;
@property(nonatomic) double topMargin; // @synthesize topMargin=_topMargin;
@property(nonatomic) _Bool shouldShowNavBarDockButton; // @synthesize shouldShowNavBarDockButton=_shouldShowNavBarDockButton;
@property(readonly, nonatomic) UIButton *navBarDockButton; // @synthesize navBarDockButton=_navBarDockButton;
@property(readonly, nonatomic) TFNTwitterAVControlBar *controlBar; // @synthesize controlBar=_controlBar;
@property(readonly, nonatomic) T1LiveVideoContentView *liveVideoContentView; // @synthesize liveVideoContentView=_liveVideoContentView;
@property(readonly, nonatomic) T1LiveVideoPlayerChromeController *chromeController; // @synthesize chromeController=_chromeController;
- (void).cxx_destruct;
- (void)liveVideoPlayerChromeController:(id)arg1 setPlayerControlsHidden:(_Bool)arg2;
- (void)liveVideoPlayerChromeController:(id)arg1 setPlayerControlsAlpha:(double)arg2;
- (void)liveVideoPlayerChromeController:(id)arg1 setNavigationBarHidden:(_Bool)arg2;
- (void)liveVideoPlayerChromeController:(id)arg1 setNavigationBarAlpha:(double)arg2;
- (void)liveVideoPlayerChromeController:(id)arg1 setStatusBarHidden:(_Bool)arg2;
- (_Bool)liveVideoPlayerChromeControllerWillShowDockButtonTooltip:(id)arg1;
- (_Bool)liveVideoPlayerChromeController:(id)arg1 shouldSetPlayerControlsToHidden:(_Bool)arg2;
- (_Bool)liveVideoPlayerChromeController:(id)arg1 shouldSetNavigationBarToHidden:(_Bool)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)_t1_headerTapGestureRecognized:(id)arg1;
- (void)_t1_dockButtonTapped;
- (void)_t1_expandButtonTapped;
- (_Bool)_t1_videoPlayerExplicitlyHidden;
- (double)_t1_hiddenVideoBannerHeight;
- (double)_t1_expansionPercentage;
- (void)_t1_retryLoadingVideo;
- (double)resizableHeaderBannerMinimumHeight;
- (double)bannerBlurPercent;
- (double)bannerAspectRatioForTraitCollection:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)bannerOverlayGradient;
- (void)addPlayerView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <T1LiveVideoHeaderViewDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

