//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <T1Twitter/T1AppNavigationProvider-Protocol.h>

@interface T1MainAppNavigationProvider : NSObject <T1AppNavigationProvider>
{
}

- (id)init;
- (id)appNavigationControllerForAccount:(id)arg1;

@end

