//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class UIImage;

@interface T1MediaHeaderImageCardViewModel : NSObject
{
    // Error parsing type: , name: mediaAspectRatio
    // Error parsing type: , name: backgroundImage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithBackgroundImage:(id)arg1 imageAspectRatio:(double)arg2;
@property(nonatomic, readonly) UIImage *backgroundImage; // @synthesize backgroundImage;
@property(nonatomic, readonly) double mediaAspectRatio; // @synthesize mediaAspectRatio;

@end

