//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNDataViewController.h>

#import <T1Twitter/T1FreshContentIndicatorViewDelegate-Protocol.h>
#import <T1Twitter/T1MediaSearchCellDelegate-Protocol.h>
#import <T1Twitter/T1SlideshowViewControllerDelegate-Protocol.h>
#import <T1Twitter/T1SlideshowViewControllerLoadingDelegate-Protocol.h>
#import <T1Twitter/T1StatusMediaHandlerSlideshowPresenter-Protocol.h>
#import <T1Twitter/TFNImageTransitionDelegate-Protocol.h>
#import <T1Twitter/TFNTwitterCompositionSource-Protocol.h>

@class NSArray, NSString, T1FreshContentIndicatorView, T1SlideshowViewController, T1StatusMediaHandler, T1StatusMediaTimelineObserver, TFNTwitterAccount, TFSTwitterScribeContext;
@protocol TFNTwitterBasicStreamSupport><TFNTwitterPollableStream><TFNTwitterMutableMediaStream;

@interface T1MediaStreamViewController : TFNDataViewController <T1StatusMediaHandlerSlideshowPresenter, T1SlideshowViewControllerDelegate, T1SlideshowViewControllerLoadingDelegate, TFNImageTransitionDelegate, T1MediaSearchCellDelegate, T1FreshContentIndicatorViewDelegate, TFNTwitterCompositionSource>
{
    _Bool _isStreamLoadedOnce;
    NSArray *_mediaInfos;
    NSArray *_rows;
    double _targetRatio;
    struct CGPoint _freshContentOffset;
    T1FreshContentIndicatorView *_freshContentView;
    TFSTwitterScribeContext *_scribeContext;
    _Bool _showsSearchButton;
    _Bool _presentsSlideShow;
    _Bool _showsUpdateIndicator;
    _Bool _supportsInfiniteScrollingSlideshow;
    _Bool _supportsMultipleStatusesPerRow;
    _Bool _supportsSmartCropping;
    _Bool _slideLoaderHasUpdatedStream;
    T1StatusMediaHandler *_mediaHandler;
    TFNTwitterAccount *_account;
    id <TFNTwitterBasicStreamSupport><TFNTwitterPollableStream><TFNTwitterMutableMediaStream> _stream;
    unsigned long long _freshCount;
    T1SlideshowViewController *_slideLoaderSlideshow;
    CDUnknownBlockType _slideLoaderCompletionBlock;
    T1StatusMediaTimelineObserver *_dynamicAdsPrefetcher;
    T1StatusMediaTimelineObserver *_videoPrefetcher;
}

@property(readonly, nonatomic) T1StatusMediaTimelineObserver *videoPrefetcher; // @synthesize videoPrefetcher=_videoPrefetcher;
@property(readonly, nonatomic) T1StatusMediaTimelineObserver *dynamicAdsPrefetcher; // @synthesize dynamicAdsPrefetcher=_dynamicAdsPrefetcher;
@property(nonatomic) _Bool slideLoaderHasUpdatedStream; // @synthesize slideLoaderHasUpdatedStream=_slideLoaderHasUpdatedStream;
@property(copy, nonatomic) CDUnknownBlockType slideLoaderCompletionBlock; // @synthesize slideLoaderCompletionBlock=_slideLoaderCompletionBlock;
@property(nonatomic) __weak T1SlideshowViewController *slideLoaderSlideshow; // @synthesize slideLoaderSlideshow=_slideLoaderSlideshow;
@property(nonatomic) unsigned long long freshCount; // @synthesize freshCount=_freshCount;
@property(nonatomic) _Bool supportsSmartCropping; // @synthesize supportsSmartCropping=_supportsSmartCropping;
@property(nonatomic) _Bool supportsMultipleStatusesPerRow; // @synthesize supportsMultipleStatusesPerRow=_supportsMultipleStatusesPerRow;
@property(nonatomic) _Bool supportsInfiniteScrollingSlideshow; // @synthesize supportsInfiniteScrollingSlideshow=_supportsInfiniteScrollingSlideshow;
@property(nonatomic) _Bool showsUpdateIndicator; // @synthesize showsUpdateIndicator=_showsUpdateIndicator;
@property(nonatomic) _Bool presentsSlideShow; // @synthesize presentsSlideShow=_presentsSlideShow;
@property(nonatomic) _Bool showsSearchButton; // @synthesize showsSearchButton=_showsSearchButton;
@property(retain, nonatomic) id <TFNTwitterBasicStreamSupport><TFNTwitterPollableStream><TFNTwitterMutableMediaStream> stream; // @synthesize stream=_stream;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingViewControllerForLocation:(struct CGPoint)arg1 inCell:(id)arg2 atIndexPath:(id)arg3 outSourceRect:(out struct CGRect *)arg4;
- (id)presentSlideshowFromPlayerViewContainerCell:(id)arg1 status:(id)arg2 previewing:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_scribeStreamResultsForMediaPreviewInfos:(id)arg1;
- (void)_scribeStreamResultsForRows:(id)arg1;
- (id)scribeImpressionParameters;
- (id)scribeComponent;
- (id)scribeSection;
- (id)scribePage;
- (id)scribe;
- (id)scribeContext;
- (void)imageTransitionViewController:(id)arg1 willTransition:(_Bool)arg2 object:(id)arg3;
- (struct CGRect)imageTransitionViewController:(id)arg1 previewImageHostViewFrameInWindow:(id)arg2 forObject:(id)arg3;
- (struct CGRect)imageTransitionViewController:(id)arg1 previewImageContentsRectForObject:(id)arg2;
- (void)setPreviewImageHidden:(_Bool)arg1 forImageTransitionViewController:(id)arg2 object:(id)arg3;
- (_Bool)imageTransitionViewController:(id)arg1 previewImageFrameIsAspectFillForObject:(id)arg2;
- (struct CGRect)imageTransitionViewController:(id)arg1 previewImageFrameInWindow:(id)arg2 forObject:(id)arg3;
- (void)_slideLoaderCompleted;
- (_Bool)slideshowCanRequestLoadingMoreSlides:(id)arg1;
- (void)slideshowDidRequestLoadingMoreSlides:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)_shouldDisplayActivityViewControllerForMediaPreviewInfo:(id)arg1;
- (void)slideshow:(id)arg1 dismissAndPresentViewController:(id)arg2;
- (void)slideshow:(id)arg1 didSelectSticker:(id)arg2;
- (void)slideshow:(id)arg1 status:(id)arg2 didSelectActiveRange:(id)arg3;
- (void)slideshow:(id)arg1 didSelectUser:(id)arg2;
- (void)slideshow:(id)arg1 didSelectStatus:(id)arg2;
- (void)slideshow:(id)arg1 didDeleteStatus:(id)arg2;
- (id)_presentSlideshowFromMediaPreviewInfo:(id)arg1 atIndexPath:(id)arg2 previewing:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (id)_generateSlideshowDataSource;
- (id)_slideshowMediaPreviewInfos;
- (void)freshContentIndicatorViewDidHide:(id)arg1;
- (void)_showFreshContentIndicatorAutohide:(_Bool)arg1;
- (void)didTapFreshContentIndicatorView:(id)arg1;
- (void)_resetFreshContentOffset;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (_Bool)_loadBottom;
- (_Bool)_canLoadBottom;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)indexPathForElementWithScrollPositionIdentifier:(id)arg1 inView:(id)arg2;
- (id)scrollPositionIdentifierForElementAtIndexPath:(id)arg1 inView:(id)arg2;
- (id)_indexPathForMediaPreviewInfo:(id)arg1;
- (id)indexPathForItem:(id)arg1;
- (id)itemAtIndexPath:(id)arg1;
- (void)mediaSearchCell:(id)arg1 didLongPress:(id)arg2 mediaPreviewInfo:(id)arg3;
- (void)mediaSearchCell:(id)arg1 didTapMediaPreviewInfo:(id)arg2;
- (void)update:(_Bool)arg1;
- (void)_didReportStatusAsSpam:(id)arg1;
- (void)_streamDidUpdate:(id)arg1;
- (unsigned long long)_numberOfMediaInfosInRows;
- (void)_reloadAllRowsUpdatingMediaInfos:(_Bool)arg1;
- (id)_rowsWithMediaPreviewInfos:(id)arg1;
- (double)_targetAspectRatioForWidth:(double)arg1;
- (_Bool)isLoadingTop;
- (void)loadTop:(id)arg1;
- (id)composition;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)setSupportsMultipleStatusesPerRow:(_Bool)arg1 updateRows:(_Bool)arg2;
@property(readonly, nonatomic) T1StatusMediaHandler *mediaHandler; // @synthesize mediaHandler=_mediaHandler;
- (id)initWithScribeContext:(id)arg1 account:(id)arg2;
- (id)initWithCollectionViewLayout:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

