//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <T1Twitter/T1NativePlayerCardPlayerContainerViewDelegate-Protocol.h>
#import <T1Twitter/TAVPlaybackObserver-Protocol.h>

@class NSString, T1MomentCapsulePageImageView, T1MomentCapsuleViewConfiguration, T1NativeMomentsCardViewModel, T1NativePlayerCardPlayerContainerView, TFNTwitterAccount;
@protocol T1MomentViewModel;

@interface T1MomentCapsuleMediaView : UIView <T1NativePlayerCardPlayerContainerViewDelegate, TAVPlaybackObserver>
{
    _Bool _registeredForPlaybackObservation;
    TFNTwitterAccount *_account;
    T1MomentCapsuleViewConfiguration *_configuration;
    T1NativePlayerCardPlayerContainerView *_playerContainerView;
    id <T1MomentViewModel> _momentViewModel;
    T1MomentCapsulePageImageView *_capsuleImageView;
    T1NativeMomentsCardViewModel *_viewModel;
    NSString *_currentVideoStatusID;
}

@property(nonatomic) _Bool registeredForPlaybackObservation; // @synthesize registeredForPlaybackObservation=_registeredForPlaybackObservation;
@property(retain, nonatomic) NSString *currentVideoStatusID; // @synthesize currentVideoStatusID=_currentVideoStatusID;
@property(retain, nonatomic) T1NativeMomentsCardViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) T1MomentCapsulePageImageView *capsuleImageView; // @synthesize capsuleImageView=_capsuleImageView;
@property(retain, nonatomic) id <T1MomentViewModel> momentViewModel; // @synthesize momentViewModel=_momentViewModel;
@property(retain, nonatomic) T1NativePlayerCardPlayerContainerView *playerContainerView; // @synthesize playerContainerView=_playerContainerView;
@property(retain, nonatomic) T1MomentCapsuleViewConfiguration *configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)_reloadConfiguration;
- (void)_createPlayerWithStatus:(id)arg1;
- (void)_viewModelCoverStatusDidUpdate:(id)arg1;
- (void)_playVideoWithMomentViewModel:(id)arg1 coverPageType:(long long)arg2 coverStatusID:(id)arg3 account:(id)arg4;
- (void)player:(id)arg1 didUpdatePlaybackState:(id)arg2;
- (void)cleanup;
- (void)unregisterForPlaybackObservation;
- (void)registerForPlaybackObservation;
- (void)setMomentViewModel:(id)arg1 coverPageType:(long long)arg2 coverStatusID:(id)arg3 account:(id)arg4;
- (void)cardPlayerContainerView:(id)arg1 didTapPlayButtonOverlayWithEvent:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 configuration:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

