//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

#import <T1Twitter/T1CachedImageColorExtractorDelegate-Protocol.h>
#import <T1Twitter/TFNTwitterImageViewFetchHelperDelegate-Protocol.h>
#import <T1Twitter/UIScrollViewDelegate-Protocol.h>

@class NSString, T1CachedImageColorExtractor, T1MomentCapsuleController, T1MomentMakerCropButton, T1MomentMakerScribeDelegate, TFNTwitterAccount, TFNTwitterMomentPage, TFNTwitterMomentRender, UIImageView, UIScrollView, UIView;

@interface T1MomentMakerCropViewController : TFNViewController <UIScrollViewDelegate, T1CachedImageColorExtractorDelegate, TFNTwitterImageViewFetchHelperDelegate>
{
    _Bool _isCoverPage;
    _Bool _appliedInitialLayout;
    double _bottomFixedContentLength;
    double _topFixedContentLength;
    UIView *_contentView;
    UIScrollView *_scrollView;
    UIView *_borderView;
    UIView *_containerView;
    UIImageView *_imageView;
    UIView *_maskView;
    UIView *_viewportMask;
    T1MomentCapsuleController *_controller;
    TFNTwitterMomentPage *_momentPage;
    TFNTwitterAccount *_account;
    T1CachedImageColorExtractor *_colorExtractor;
    T1MomentMakerCropButton *_letterboxButton;
    T1MomentMakerScribeDelegate *_scribeDelegate;
}

@property(retain, nonatomic) T1MomentMakerScribeDelegate *scribeDelegate; // @synthesize scribeDelegate=_scribeDelegate;
@property(retain, nonatomic) T1MomentMakerCropButton *letterboxButton; // @synthesize letterboxButton=_letterboxButton;
@property(nonatomic) _Bool appliedInitialLayout; // @synthesize appliedInitialLayout=_appliedInitialLayout;
@property(retain, nonatomic) T1CachedImageColorExtractor *colorExtractor; // @synthesize colorExtractor=_colorExtractor;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(retain, nonatomic) TFNTwitterMomentPage *momentPage; // @synthesize momentPage=_momentPage;
@property(retain, nonatomic) T1MomentCapsuleController *controller; // @synthesize controller=_controller;
@property(retain, nonatomic) UIView *viewportMask; // @synthesize viewportMask=_viewportMask;
@property(retain, nonatomic) UIView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIView *borderView; // @synthesize borderView=_borderView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) _Bool isCoverPage; // @synthesize isCoverPage=_isCoverPage;
@property(nonatomic) double topFixedContentLength; // @synthesize topFixedContentLength=_topFixedContentLength;
@property(nonatomic) double bottomFixedContentLength; // @synthesize bottomFixedContentLength=_bottomFixedContentLength;
- (void).cxx_destruct;
- (void)imageColorExtractor:(id)arg1 didFinishExtractingMostDominantColor:(id)arg2 image:(id)arg3 identifier:(id)arg4;
- (void)tfn_fetchHelper:(id)arg1 didUpdateImageFromSource:(long long)arg2 isFinal:(_Bool)arg3;
- (void)_updateImageViewFetchHelper;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(double)arg3;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_snapToScrollPosition:(id)arg1 animated:(_Bool)arg2;
- (double)_minimumCropScale;
@property(readonly, nonatomic) TFNTwitterMomentRender *currentRender;
- (void)_toggleLetterbox:(id)arg1;
- (void)_cancelButtonTapped:(id)arg1;
- (void)_doneButtonTapped:(id)arg1;
- (void)_animateImageViewDownIfNeeded;
- (void)_animateImageViewUpIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (double)_calculatedLetterboxOriginYDelta;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithCapsuleController:(id)arg1 momentPage:(id)arg2 account:(id)arg3 scribeDelegate:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

