//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1MomentPageBackgroundViewController.h>

#import <T1Twitter/TAVPlaybackObserver-Protocol.h>
#import <T1Twitter/TFNTwitterAmplifyPlayerDelegate-Protocol.h>

@class NSString, T1AmplifyContentControlBar, T1AmplifyUIEventHandler, TAVPlaybackState, TAVPlayer, TAVPlayerView, TAVPlayerViewConfiguration, TAVScribeContext, TFNGradientView, TFNTwitterAVAutoplayPlayerController, TFNTwitterStatus;

@interface T1MomentPageVideoStreamElementViewController : T1MomentPageBackgroundViewController <TFNTwitterAmplifyPlayerDelegate, TAVPlaybackObserver>
{
    _Bool _playbackFailed;
    _Bool _useTAVPlayer;
    _Bool _stalled;
    _Bool _preloading;
    TAVPlayer *_tavPlayer;
    TAVPlaybackState *_playbackState;
    TAVPlayerView *_tavPlayerView;
    TAVScribeContext *_tavScribeContext;
    TFNTwitterAVAutoplayPlayerController *_deprecatedPlayer;
    T1AmplifyContentControlBar *_mediaControlsBar;
    TFNTwitterStatus *_status;
    long long _stallCount;
    long long _mediaControlsVisibilityState;
    T1AmplifyUIEventHandler *_amplifyActionHandler;
    TFNGradientView *_mediaControlsGradientView;
}

+ (id)_avConfigurationWithAccount:(id)arg1;
+ (id)backgroundViewControllerForMomentPage:(id)arg1 account:(id)arg2 scribeContext:(id)arg3;
@property(retain, nonatomic) TFNGradientView *mediaControlsGradientView; // @synthesize mediaControlsGradientView=_mediaControlsGradientView;
@property(retain, nonatomic) T1AmplifyUIEventHandler *amplifyActionHandler; // @synthesize amplifyActionHandler=_amplifyActionHandler;
@property(nonatomic) long long mediaControlsVisibilityState; // @synthesize mediaControlsVisibilityState=_mediaControlsVisibilityState;
@property(nonatomic) long long stallCount; // @synthesize stallCount=_stallCount;
@property(nonatomic) _Bool preloading; // @synthesize preloading=_preloading;
@property(nonatomic) _Bool stalled; // @synthesize stalled=_stalled;
@property(retain, nonatomic) TFNTwitterStatus *status; // @synthesize status=_status;
@property(retain, nonatomic) T1AmplifyContentControlBar *mediaControlsBar; // @synthesize mediaControlsBar=_mediaControlsBar;
@property(retain, nonatomic) TFNTwitterAVAutoplayPlayerController *deprecatedPlayer; // @synthesize deprecatedPlayer=_deprecatedPlayer;
@property(readonly, nonatomic) _Bool useTAVPlayer; // @synthesize useTAVPlayer=_useTAVPlayer;
@property(retain, nonatomic) TAVScribeContext *tavScribeContext; // @synthesize tavScribeContext=_tavScribeContext;
@property(retain, nonatomic) TAVPlayerView *tavPlayerView; // @synthesize tavPlayerView=_tavPlayerView;
@property(retain, nonatomic) TAVPlaybackState *playbackState; // @synthesize playbackState=_playbackState;
@property(retain, nonatomic) TAVPlayer *tavPlayer; // @synthesize tavPlayer=_tavPlayer;
@property(nonatomic) _Bool playbackFailed; // @synthesize playbackFailed=_playbackFailed;
- (void).cxx_destruct;
- (double)_t1_radiansToDegrees:(double)arg1;
- (double)_t1_degreesToRadians:(double)arg1;
- (double)_t1_standardizeRotationForDegrees:(double)arg1;
- (void)_t1_periscopeVideoDidRotate:(double)arg1;
- (void)_deatachMediaControls;
- (void)_attachMediaControlsToView:(id)arg1;
- (void)animateContentViewRotationToOrientation:(long long)arg1 withCompletionHandler:(CDUnknownBlockType)arg2 additionalAnimations:(CDUnknownBlockType)arg3;
- (void)deviceDidRotateToOrientation:(long long)arg1;
- (void)playerDidReceiveTimedMetadata:(id)arg1 timedMetadata:(id)arg2;
- (void)avPlayerController:(id)arg1 didTapPlayerView:(id)arg2;
- (void)avPlayerController:(id)arg1 playbackDidProgressToTime:(double)arg2;
- (void)avPlayerControllerPlaybackDidResume:(id)arg1;
- (void)avPlayerControllerPlaybackDidStart:(id)arg1;
- (void)avPlayerControllerPlaybackDidStall:(id)arg1;
- (void)avPlayerControllerPlaybackDidRecoverFromStall:(id)arg1;
- (void)avPlayerControllerDidDispose:(id)arg1;
- (void)avPlayerController:(id)arg1 didFailToLoadWithError:(id)arg2;
- (void)avPlayerControllerDidCompletePreparingForPlayback:(id)arg1;
- (double)avPlayerController:(id)arg1 visibilityPercentageForPlayerView:(id)arg2;
- (void)avPlayerController:(id)arg1 detachPlayerView:(id)arg2 animated:(_Bool)arg3;
- (void)avPlayerController:(id)arg1 attachPlayerView:(id)arg2 animated:(_Bool)arg3;
- (void)player:(id)arg1 didUpdatePlaybackState:(id)arg2;
- (void)handlePlayerViewTap;
- (void)handlePlaybackDidStart;
- (void)setUpPlayerView:(id)arg1;
- (void)handleErrorState;
- (_Bool)updateMediaDimensionsIfNecessary;
- (void)_playVideo;
- (void)_playVideoWithTAVPlayer;
- (void)_playVideoWithDeprecatedPlayer;
- (void)purgeMedia;
- (void)_cleanupPlayer;
- (void)resumeMedia;
- (_Bool)_isPlayerCreated;
- (void)pauseMedia;
- (void)preloadMediaForDisplaySize:(struct CGSize)arg1;
- (id)errorString;
- (_Bool)hasErrors;
- (_Bool)needsActivityIndicator;
- (_Bool)isPlayingMedia;
- (void)setVolume:(double)arg1;
- (void)performCallToAction;
- (id)accessoryBadgeText;
- (id)callToActionText;
- (void)viewDidLayoutSubviews;
- (void)dealloc;
- (id)initWithPage:(id)arg1 account:(id)arg2 referenceMediaDimensions:(struct CGSize)arg3 scribeContext:(id)arg4;
@property(readonly, nonatomic) TAVPlayerViewConfiguration *playerViewConfiguration;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

