//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1NativeCardClassicHighlightableView.h>

@class NSString, TFNAttributedTextView;

@interface T1NativeCardClassicHighlightableTextView : T1NativeCardClassicHighlightableView
{
    _Bool _hiddenOnNilText;
    TFNAttributedTextView *_attributedTextView;
    NSString *_text;
}

+ (id)_textModel;
+ (struct CGSize)_sizeForTextModel:(id)arg1 forWidth:(double)arg2;
+ (id)attributedStringForText:(id)arg1;
+ (struct CGSize)sizeForText:(id)arg1 width:(double)arg2;
+ (void)applyDefaultsForAttributedTextView:(id)arg1;
+ (int)maxLines;
@property(nonatomic, getter=isHiddenOnNilText) _Bool hiddenOnNilText; // @synthesize hiddenOnNilText=_hiddenOnNilText;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) TFNAttributedTextView *attributedTextView; // @synthesize attributedTextView=_attributedTextView;
- (void).cxx_destruct;
- (void)layoutSubviewsWithinHighlightViewBounds:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

