//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, T1NativeVideoEndScreenViewModel;
@protocol T1NativeVideoEndScreenViewEventHandler;

@interface T1NativeVideoEndScreenView : UIView
{
    // Error parsing type: , name: viewModel
    // Error parsing type: , name: eventHandler
    // Error parsing type: , name: ctaContainerView.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (void)callToActionsContainerView:(id)arg1 didSelectView:(id)arg2 atIndex:(unsigned long long)arg3 withEvent:(id)arg4;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) NSArray *buttonList;
@property(nonatomic) __weak id <T1NativeVideoEndScreenViewEventHandler> eventHandler; // @synthesize eventHandler;
@property(nonatomic, retain) T1NativeVideoEndScreenViewModel *viewModel; // @synthesize viewModel;

@end

