//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNTwitterCardViewLayoutState.h>

#import <T1Twitter/T1NativeLeadGenCardImageInfoViewLayoutState-Protocol.h>
#import <T1Twitter/TFNTwitterCardViewLayoutStateValidation-Protocol.h>

@class NSString, T1NativeLeadGenCardSubmitViewLayoutState, T1NativeLeadGenCardSuccessViewLayoutState, TFNLayoutMetrics, TFNTwitterCardContext, TFNTwitterCardStateManager;

@interface T1NativeLeadGenCardFullViewLayoutState : TFNTwitterCardViewLayoutState <TFNTwitterCardViewLayoutStateValidation, T1NativeLeadGenCardImageInfoViewLayoutState>
{
    TFNLayoutMetrics *layoutMetrics;
    TFNTwitterCardContext *cardContext;
    T1NativeLeadGenCardFullViewLayoutState *_fullViewLayoutState;
    T1NativeLeadGenCardSubmitViewLayoutState *_submitViewLayoutState;
    T1NativeLeadGenCardSuccessViewLayoutState *_successViewLayoutState;
    TFNTwitterCardStateManager *_cardStateManager;
    struct CGSize size;
    struct CGRect imageViewFrame;
    struct CGRect titleFrame;
    struct CGRect imagePartitionFrame;
    struct CGRect imageHighlightViewFrame;
    struct CGRect callToActionButtonFrame;
    struct CGRect callToActionHighlightViewFrame;
    struct CGRect _imageInfoAreaBorderFrame;
    struct CGRect _submitViewFrame;
    struct CGRect _successViewFrame;
}

@property(retain, nonatomic) TFNTwitterCardStateManager *cardStateManager; // @synthesize cardStateManager=_cardStateManager;
@property(retain, nonatomic) T1NativeLeadGenCardSuccessViewLayoutState *successViewLayoutState; // @synthesize successViewLayoutState=_successViewLayoutState;
@property(retain, nonatomic) T1NativeLeadGenCardSubmitViewLayoutState *submitViewLayoutState; // @synthesize submitViewLayoutState=_submitViewLayoutState;
@property(retain, nonatomic) T1NativeLeadGenCardFullViewLayoutState *fullViewLayoutState; // @synthesize fullViewLayoutState=_fullViewLayoutState;
@property(nonatomic) struct CGRect successViewFrame; // @synthesize successViewFrame=_successViewFrame;
@property(nonatomic) struct CGRect submitViewFrame; // @synthesize submitViewFrame=_submitViewFrame;
@property(nonatomic) struct CGRect imageInfoAreaBorderFrame; // @synthesize imageInfoAreaBorderFrame=_imageInfoAreaBorderFrame;
@property(nonatomic) struct CGRect callToActionHighlightViewFrame; // @synthesize callToActionHighlightViewFrame;
@property(nonatomic) struct CGRect callToActionButtonFrame; // @synthesize callToActionButtonFrame;
@property(nonatomic) struct CGRect imageHighlightViewFrame; // @synthesize imageHighlightViewFrame;
@property(nonatomic) struct CGRect imagePartitionFrame; // @synthesize imagePartitionFrame;
- (void)setSize:(struct CGSize)arg1;
- (struct CGSize)size;
- (void)setCardContext:(id)arg1;
- (id)cardContext;
@property(nonatomic) struct CGRect titleFrame; // @synthesize titleFrame;
@property(nonatomic) struct CGRect imageViewFrame; // @synthesize imageViewFrame;
- (void)setLayoutMetrics:(id)arg1;
- (id)layoutMetrics;
- (void).cxx_destruct;
- (_Bool)isLayoutStateValidForCardContext:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

