//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNTwitterCardViewLayoutDelegate.h>

@interface T1NativeBroadcastCardViewLayoutDelegate : TFNTwitterCardViewLayoutDelegate
{
}

+ (_Bool)_t1_useCompactVerticalLayoutWithLayoutMetrics:(id)arg1 account:(id)arg2;
+ (id)viewModelWithCardContext:(id)arg1;
+ (id)sharedLayoutDelegate;
- (void)layoutSubviewsForCardView:(id)arg1 withState:(id)arg2;
- (struct CGSize)targetBroadcastContainerViewSizeForViewModel:(id)arg1 layoutMetrics:(id)arg2;
- (id)layoutForViewModel:(id)arg1 layoutMetrics:(id)arg2;

@end

