//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNTwitterCardView.h>

#import <T1Twitter/T1NativeLeadGenCardSuccessViewDelegate-Protocol.h>

@class NSString, T1NativeLeadGenCardFullViewEventRegistry, T1NativeLeadGenCardSubmitView, T1NativeLeadGenCardSuccessView, T1NativeLeadGenCardViewModel, TFNTwitterCardStateManager, UIImageView, UILabel, UIView;
@protocol TFNTwitterCardViewDelegate;

@interface T1NativeLeadGenCardFullView : TFNTwitterCardView <T1NativeLeadGenCardSuccessViewDelegate>
{
    id <TFNTwitterCardViewDelegate> _delegate;
    T1NativeLeadGenCardViewModel *_viewModel;
    UILabel *_titleLabel;
    UIImageView *_imageView;
    UIView *_imagePartitionView;
    T1NativeLeadGenCardSubmitView *_submitView;
    T1NativeLeadGenCardSuccessView *_successView;
    UIView *_imageInfoAreaBorderView;
    TFNTwitterCardStateManager *_sharedStateManager;
    T1NativeLeadGenCardFullViewEventRegistry *_eventRegistry;
}

@property(retain, nonatomic) T1NativeLeadGenCardFullViewEventRegistry *eventRegistry; // @synthesize eventRegistry=_eventRegistry;
@property(retain, nonatomic) TFNTwitterCardStateManager *sharedStateManager; // @synthesize sharedStateManager=_sharedStateManager;
@property(retain, nonatomic) UIView *imageInfoAreaBorderView; // @synthesize imageInfoAreaBorderView=_imageInfoAreaBorderView;
@property(retain, nonatomic) T1NativeLeadGenCardSuccessView *successView; // @synthesize successView=_successView;
@property(retain, nonatomic) T1NativeLeadGenCardSubmitView *submitView; // @synthesize submitView=_submitView;
@property(retain, nonatomic) UIView *imagePartitionView; // @synthesize imagePartitionView=_imagePartitionView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) T1NativeLeadGenCardViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (id)delegate;
- (void).cxx_destruct;
- (void)tfn_fetchHelper:(id)arg1 readyToConfigureView:(id)arg2 state:(long long)arg3;
- (void)leadGenCardSuccessView:(id)arg1 didTapSubview:(id)arg2;
- (void)_viewModelDidUpdate:(id)arg1;
- (void)_updateTitle;
- (void)_updateCardViewLayout;
- (void)_updateContent;
- (void)fetchImages;
- (id)imageFetchingViews;
- (void)cardContextDidUpdate;
- (void)_cleanup;
- (void)prepareForReuse;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

