//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNTwitterCardView.h>

@class T1NativeAudioCardViewModel, TFNSolidColorView, TFNTappableHighlightView, UIActivityIndicatorView, UIButton, UIImageView, UILabel;

@interface T1NativeAudioCardView : TFNTwitterCardView
{
    UIImageView *_thumbnailView;
    TFNTappableHighlightView *_highlightView;
    UIButton *_playButton;
    UIActivityIndicatorView *_loadingIndicator;
    UILabel *_titleLabel;
    UILabel *_artistNameLabel;
    UIButton *_artistHandleButton;
    UILabel *_partnerLabel;
    T1NativeAudioCardViewModel *_viewModel;
    TFNSolidColorView *_dominantColorView;
}

@property(readonly, nonatomic) TFNSolidColorView *dominantColorView; // @synthesize dominantColorView=_dominantColorView;
@property(readonly, nonatomic) T1NativeAudioCardViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(readonly, nonatomic) UILabel *partnerLabel; // @synthesize partnerLabel=_partnerLabel;
@property(readonly, nonatomic) UIButton *artistHandleButton; // @synthesize artistHandleButton=_artistHandleButton;
@property(readonly, nonatomic) UILabel *artistNameLabel; // @synthesize artistNameLabel=_artistNameLabel;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(readonly, nonatomic) UIActivityIndicatorView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
@property(readonly, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(readonly, nonatomic) TFNTappableHighlightView *highlightView; // @synthesize highlightView=_highlightView;
@property(readonly, nonatomic) UIImageView *thumbnailView; // @synthesize thumbnailView=_thumbnailView;
- (void).cxx_destruct;
- (void)fetchImages;
- (id)imageFetchingViews;
- (void)stopLoadingIndicator;
- (void)startLoadingIndicator;
- (void)_didLongPress:(id)arg1;
- (void)_artistHandleDidTap;
- (void)_didTap:(id)arg1;
- (id)_labelWithDefaultConfigurations;
- (void)_createSubviews;
- (void)_updateSubviews;
- (void)cardContextDidUpdate;
- (void)_cleanup;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

