//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class T1NativeCardMediaView, TIPImageFetchMetrics, UIEvent;

@protocol T1NativeCardMediaViewDelegate
- (void)nativeCardMediaView:(T1NativeCardMediaView *)arg1 didReceivePlayButtonActionWithEvent:(UIEvent *)arg2;

@optional
- (void)nativeCardMediaView:(T1NativeCardMediaView *)arg1 didFinishImageLoadWithMetrics:(TIPImageFetchMetrics *)arg2;
@end

