//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class T1NativeLeadGenCardViewModel;

@interface T1NativeLeadGenCardSubmitViewLayoutState : NSObject
{
    T1NativeLeadGenCardViewModel *_viewModel;
    struct CGSize _size;
    struct CGRect _shareInfoDescriptionFrame;
    struct CGRect _avatarImageFrame;
    struct CGRect _nameFrame;
    struct CGRect _nameTitleFrame;
    struct CGRect _nameValidityImageFrame;
    struct CGRect _emailTitleFrame;
    struct CGRect _emailFrame;
    struct CGRect _emailValidityImageFrame;
    struct CGRect _zipFieldFrame;
    struct CGRect _zipTitleFrame;
    struct CGRect _zipValidityImageFrame;
    struct CGRect _callToActionButtonFrame;
    struct CGRect _advertiserPolicyFrame;
    struct CGRect _firstSeparatorFrame;
    struct CGRect _secondSeparatorFrame;
    struct CGRect _thirdSeparatorFrame;
    struct CGRect _fourthSeparatorFrame;
    struct CGRect _submissionFailureMessageFrame;
}

@property(nonatomic) struct CGRect submissionFailureMessageFrame; // @synthesize submissionFailureMessageFrame=_submissionFailureMessageFrame;
@property(nonatomic) struct CGRect fourthSeparatorFrame; // @synthesize fourthSeparatorFrame=_fourthSeparatorFrame;
@property(nonatomic) struct CGRect thirdSeparatorFrame; // @synthesize thirdSeparatorFrame=_thirdSeparatorFrame;
@property(nonatomic) struct CGRect secondSeparatorFrame; // @synthesize secondSeparatorFrame=_secondSeparatorFrame;
@property(nonatomic) struct CGRect firstSeparatorFrame; // @synthesize firstSeparatorFrame=_firstSeparatorFrame;
@property(nonatomic) struct CGRect advertiserPolicyFrame; // @synthesize advertiserPolicyFrame=_advertiserPolicyFrame;
@property(nonatomic) struct CGRect callToActionButtonFrame; // @synthesize callToActionButtonFrame=_callToActionButtonFrame;
@property(nonatomic) struct CGRect zipValidityImageFrame; // @synthesize zipValidityImageFrame=_zipValidityImageFrame;
@property(nonatomic) struct CGRect zipTitleFrame; // @synthesize zipTitleFrame=_zipTitleFrame;
@property(nonatomic) struct CGRect zipFieldFrame; // @synthesize zipFieldFrame=_zipFieldFrame;
@property(nonatomic) struct CGRect emailValidityImageFrame; // @synthesize emailValidityImageFrame=_emailValidityImageFrame;
@property(nonatomic) struct CGRect emailFrame; // @synthesize emailFrame=_emailFrame;
@property(nonatomic) struct CGRect emailTitleFrame; // @synthesize emailTitleFrame=_emailTitleFrame;
@property(nonatomic) struct CGRect nameValidityImageFrame; // @synthesize nameValidityImageFrame=_nameValidityImageFrame;
@property(nonatomic) struct CGRect nameTitleFrame; // @synthesize nameTitleFrame=_nameTitleFrame;
@property(nonatomic) struct CGRect nameFrame; // @synthesize nameFrame=_nameFrame;
@property(nonatomic) struct CGRect avatarImageFrame; // @synthesize avatarImageFrame=_avatarImageFrame;
@property(nonatomic) struct CGRect shareInfoDescriptionFrame; // @synthesize shareInfoDescriptionFrame=_shareInfoDescriptionFrame;
@property(retain, nonatomic) T1NativeLeadGenCardViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
- (void).cxx_destruct;

@end

