//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UILabel;

@interface T1NewsCameraRoundedPillView : UIView
{
    UILabel *_label;
    _Bool _usingAlertColors;
    NSString *_text;
}

@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (void)useAlertColors:(_Bool)arg1;
- (id)init;

@end

