//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <T1Twitter/T1OnboardingErrorHandler-Protocol.h>
#import <T1Twitter/T1OnboardingSubtaskControllerDelegate-Protocol.h>
#import <T1Twitter/TFNOnboardingSubtaskDataProvider-Protocol.h>

@class NSString, TFNOnboardingTask;
@protocol T1OnboardingTaskControllerDelegate;

@interface T1OnboardingTaskController : NSObject <TFNOnboardingSubtaskDataProvider, T1OnboardingErrorHandler, T1OnboardingSubtaskControllerDelegate>
{
    id <T1OnboardingTaskControllerDelegate> _delegate;
    TFNOnboardingTask *_task;
}

@property(readonly, nonatomic) TFNOnboardingTask *task; // @synthesize task=_task;
- (void).cxx_destruct;
- (_Bool)boolForKey:(id)arg1 inSubtaskWithID:(id)arg2 defaultValue:(_Bool)arg3;
- (long long)integerForKey:(id)arg1 inSubtaskWithID:(id)arg2 defaultValue:(long long)arg3;
- (id)dateForKey:(id)arg1 inSubtaskWithID:(id)arg2;
- (id)stringForKey:(id)arg1 inSubtaskWithID:(id)arg2;
- (void)subtaskController:(id)arg1 setStateValue:(id)arg2 forKey:(id)arg3;
- (id)subtaskController:(id)arg1 stateValueForKey:(id)arg2;
- (id)subtaskDataProviderForSubtaskController:(id)arg1;
- (void)viewCurrentAccountForSubtaskController:(id)arg1;
- (void)subtaskController:(id)arg1 didChangeCurrentAccount:(id)arg2;
- (id)currentAccountForSubtaskController:(id)arg1;
- (void)subtaskController:(id)arg1 didActivateNavigationLink:(id)arg2;
- (void)subtaskController:(id)arg1 waitWithMessage:(id)arg2;
- (id)subtaskControllerWillPresentOverCurrentViewController:(id)arg1;
- (id)subtaskController:(id)arg1 pushViewController:(id)arg2 withPresentationType:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)handleError:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)privateScribeItemForSubtaskID:(id)arg1;
- (id)private_scribe;
- (void)private_startSubtask:(id)arg1 navigationContext:(id)arg2 navigationLink:(id)arg3;
- (void)private_startSubtaskWithID:(id)arg1 navigationContext:(id)arg2 navigationLink:(id)arg3;
- (id)private_subtaskWithID:(id)arg1;
- (id)private_controllerForSubtask:(id)arg1;
- (void)start;
- (id)initWithTask:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

