//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <T1Twitter/T1PeopleAddressBook-Protocol.h>

@class NSArray, NSString;

@interface T1PeopleAddressBook : NSObject <T1PeopleAddressBook>
{
}

@property(readonly, copy, nonatomic) NSArray *contacts;
@property(readonly, nonatomic) long long authorizationStatus;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

