//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

#import <T1Twitter/PHPhotoLibraryChangeObserver-Protocol.h>
#import <T1Twitter/T1CameraContainerViewControllerDelegate-Protocol.h>
#import <T1Twitter/T1FiltersViewControllerDelegate-Protocol.h>
#import <T1Twitter/T1PhotoGalleryCollectionsViewControllerDelegate-Protocol.h>
#import <T1Twitter/T1PhotoGalleryTitleViewDelegate-Protocol.h>
#import <T1Twitter/T1PhotoGalleryViewAssetCellDelegate-Protocol.h>
#import <T1Twitter/T1PhotoGalleryViewCellDelegate-Protocol.h>
#import <T1Twitter/T1PhotoPickerViewControllerDelegate-Protocol.h>
#import <T1Twitter/T1VideoTrimmerViewControllerDelegate-Protocol.h>
#import <T1Twitter/TFNPhotoCachingImageManagerHelperDelegate-Protocol.h>
#import <T1Twitter/TFNTooltipDelegate-Protocol.h>
#import <T1Twitter/TFNTwitterAuthenticated-Protocol.h>
#import <T1Twitter/UICollectionViewDataSource-Protocol.h>
#import <T1Twitter/UICollectionViewDelegate-Protocol.h>
#import <T1Twitter/UICollectionViewDelegateFlowLayout-Protocol.h>

@class NSArray, NSIndexPath, NSPredicate, NSString, PHAssetCollection, PHFetchResult, TFNBarButtonItem, TFNPhotoCachingImageManagerHelper, TFNScrollViewDelegateBroadcaster, TFNTooltip, TFNTwitterAccount, TFNTwitterCompositionAttachments, UICollectionView, UICollectionViewCell;
@protocol T1PhotoGalleryViewControllerDelegate;

@interface T1PhotoGalleryViewController : TFNViewController <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, UICollectionViewDelegate, T1PhotoGalleryTitleViewDelegate, T1PhotoGalleryViewCellDelegate, T1PhotoGalleryCollectionsViewControllerDelegate, T1PhotoGalleryViewAssetCellDelegate, T1CameraContainerViewControllerDelegate, T1PhotoPickerViewControllerDelegate, T1FiltersViewControllerDelegate, T1VideoTrimmerViewControllerDelegate, PHPhotoLibraryChangeObserver, TFNPhotoCachingImageManagerHelperDelegate, TFNTooltipDelegate, TFNTwitterAuthenticated>
{
    _Bool _authorized;
    _Bool _sessionActive;
    _Bool _disablesCellOnSessionEnd;
    _Bool _disableLongPressToEdit;
    _Bool _collectionsFromTitleViewEnabled;
    _Bool _customCameraEnabled;
    _Bool _livePhotoBadgeEnabled;
    _Bool _removeProfileBannerEnabled;
    _Bool _cameraItemHidden;
    _Bool _videoCameraItemHidden;
    _Bool _periscopeGoLiveItemHidden;
    _Bool _collectionsItemHidden;
    _Bool _removeProfileBannerItemHidden;
    _Bool _adding;
    TFNTwitterAccount *_account;
    id <T1PhotoGalleryViewControllerDelegate> _delegate;
    double _referenceItemWidth;
    UICollectionView *_collectionView;
    unsigned long long _sessionMode;
    long long _customCameraPreferredDevice;
    NSArray *_additionalMediaCollectionNames;
    NSString *_collectionName;
    unsigned long long _theme;
    PHAssetCollection *_assetCollection;
    unsigned long long _attachmentTypes;
    PHFetchResult *_fetchResult;
    NSPredicate *_fetchPredicate;
    TFNPhotoCachingImageManagerHelper *_cachingImageManagerHelper;
    TFNScrollViewDelegateBroadcaster *_scrollViewEventBroadcaster;
    NSIndexPath *_collectionsItemIndexPath;
    NSIndexPath *_photoCameraItemIndexPath;
    NSIndexPath *_videoCameraItemIndexPath;
    NSIndexPath *_periscopeGoLiveItemIndexPath;
    NSIndexPath *_removeProfileBannerItemIndexPath;
    unsigned long long _assetItemIndexOffset;
    double _cachedReferenceItemWidth;
    double _cachedCollectionViewWidth;
    TFNTwitterCompositionAttachments *_attachments;
    TFNBarButtonItem *_addBarButtonItem;
    UICollectionViewCell *_trackingLongPressedCell;
    TFNTooltip *_periscopeGoLiveTooltip;
    struct CGSize _cachedItemSize;
    struct UIEdgeInsets _cachedSectionInset;
}

+ (void)requestAuthorizedViewControllerWithAttachmentTypes:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) TFNTooltip *periscopeGoLiveTooltip; // @synthesize periscopeGoLiveTooltip=_periscopeGoLiveTooltip;
@property(retain, nonatomic) UICollectionViewCell *trackingLongPressedCell; // @synthesize trackingLongPressedCell=_trackingLongPressedCell;
@property(readonly, nonatomic) TFNBarButtonItem *addBarButtonItem; // @synthesize addBarButtonItem=_addBarButtonItem;
@property(nonatomic, getter=isAdding) _Bool adding; // @synthesize adding=_adding;
@property(readonly, nonatomic) TFNTwitterCompositionAttachments *attachments; // @synthesize attachments=_attachments;
@property(nonatomic) struct UIEdgeInsets cachedSectionInset; // @synthesize cachedSectionInset=_cachedSectionInset;
@property(nonatomic) struct CGSize cachedItemSize; // @synthesize cachedItemSize=_cachedItemSize;
@property(nonatomic) double cachedCollectionViewWidth; // @synthesize cachedCollectionViewWidth=_cachedCollectionViewWidth;
@property(nonatomic) double cachedReferenceItemWidth; // @synthesize cachedReferenceItemWidth=_cachedReferenceItemWidth;
@property(nonatomic) unsigned long long assetItemIndexOffset; // @synthesize assetItemIndexOffset=_assetItemIndexOffset;
@property(retain, nonatomic) NSIndexPath *removeProfileBannerItemIndexPath; // @synthesize removeProfileBannerItemIndexPath=_removeProfileBannerItemIndexPath;
@property(retain, nonatomic) NSIndexPath *periscopeGoLiveItemIndexPath; // @synthesize periscopeGoLiveItemIndexPath=_periscopeGoLiveItemIndexPath;
@property(retain, nonatomic) NSIndexPath *videoCameraItemIndexPath; // @synthesize videoCameraItemIndexPath=_videoCameraItemIndexPath;
@property(retain, nonatomic) NSIndexPath *photoCameraItemIndexPath; // @synthesize photoCameraItemIndexPath=_photoCameraItemIndexPath;
@property(retain, nonatomic) NSIndexPath *collectionsItemIndexPath; // @synthesize collectionsItemIndexPath=_collectionsItemIndexPath;
@property(readonly, nonatomic) TFNScrollViewDelegateBroadcaster *scrollViewEventBroadcaster; // @synthesize scrollViewEventBroadcaster=_scrollViewEventBroadcaster;
@property(readonly, nonatomic) TFNPhotoCachingImageManagerHelper *cachingImageManagerHelper; // @synthesize cachingImageManagerHelper=_cachingImageManagerHelper;
@property(retain, nonatomic) NSPredicate *fetchPredicate; // @synthesize fetchPredicate=_fetchPredicate;
@property(retain, nonatomic) PHFetchResult *fetchResult; // @synthesize fetchResult=_fetchResult;
@property(readonly, nonatomic) unsigned long long attachmentTypes; // @synthesize attachmentTypes=_attachmentTypes;
@property(retain, nonatomic) PHAssetCollection *assetCollection; // @synthesize assetCollection=_assetCollection;
@property(nonatomic) unsigned long long theme; // @synthesize theme=_theme;
@property(copy, nonatomic) NSString *collectionName; // @synthesize collectionName=_collectionName;
@property(copy, nonatomic) NSArray *additionalMediaCollectionNames; // @synthesize additionalMediaCollectionNames=_additionalMediaCollectionNames;
@property(nonatomic) long long customCameraPreferredDevice; // @synthesize customCameraPreferredDevice=_customCameraPreferredDevice;
@property(nonatomic, getter=isRemoveProfileBannerItemHidden) _Bool removeProfileBannerItemHidden; // @synthesize removeProfileBannerItemHidden=_removeProfileBannerItemHidden;
@property(nonatomic, getter=isCollectionsItemHidden) _Bool collectionsItemHidden; // @synthesize collectionsItemHidden=_collectionsItemHidden;
@property(nonatomic, getter=isPeriscopeGoLiveItemHidden) _Bool periscopeGoLiveItemHidden; // @synthesize periscopeGoLiveItemHidden=_periscopeGoLiveItemHidden;
@property(nonatomic, getter=isVideoCameraItemHidden) _Bool videoCameraItemHidden; // @synthesize videoCameraItemHidden=_videoCameraItemHidden;
@property(nonatomic, getter=isCameraItemHidden) _Bool cameraItemHidden; // @synthesize cameraItemHidden=_cameraItemHidden;
@property(nonatomic, getter=isRemoveProfileBannerEnabled) _Bool removeProfileBannerEnabled; // @synthesize removeProfileBannerEnabled=_removeProfileBannerEnabled;
@property(nonatomic, getter=isLivePhotoBadgeEnabled) _Bool livePhotoBadgeEnabled; // @synthesize livePhotoBadgeEnabled=_livePhotoBadgeEnabled;
@property(nonatomic, getter=isCustomCameraEnabled) _Bool customCameraEnabled; // @synthesize customCameraEnabled=_customCameraEnabled;
@property(nonatomic, getter=isCollectionsFromTitleViewEnabled) _Bool collectionsFromTitleViewEnabled; // @synthesize collectionsFromTitleViewEnabled=_collectionsFromTitleViewEnabled;
@property(nonatomic) _Bool disableLongPressToEdit; // @synthesize disableLongPressToEdit=_disableLongPressToEdit;
@property(nonatomic) _Bool disablesCellOnSessionEnd; // @synthesize disablesCellOnSessionEnd=_disablesCellOnSessionEnd;
@property(readonly, nonatomic, getter=isSessionActive) _Bool sessionActive; // @synthesize sessionActive=_sessionActive;
@property(nonatomic) unsigned long long sessionMode; // @synthesize sessionMode=_sessionMode;
@property(nonatomic, getter=isAuthorized) _Bool authorized; // @synthesize authorized=_authorized;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) double referenceItemWidth; // @synthesize referenceItemWidth=_referenceItemWidth;
@property(nonatomic) __weak id <T1PhotoGalleryViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)scribeElementForIndexPath:(id)arg1;
- (id)scribeComponentForIndexPath:(id)arg1;
- (id)scribeComponent;
- (id)scribeSection;
- (id)scribePage;
- (id)scribe;
- (void)_dismissTooltipIfNeeded:(id)arg1;
- (void)tooltipDidTap:(id)arg1;
- (_Bool)tooltipShouldPresent:(id)arg1;
- (id)_indexPathsInRect:(struct CGRect)arg1;
- (id)cachingImageManagerHelper:(id)arg1 assetsInRect:(struct CGRect)arg2;
- (_Bool)cachingImageManagerHelper:(id)arg1 shouldUpdateForRect:(struct CGRect)arg2 cachedRect:(struct CGRect)arg3;
- (id)_indexPathForAssetIndex:(unsigned long long)arg1 inFetchResult:(id)arg2;
- (id)_indexPathsForAssetIndexSet:(id)arg1 inFetchResult:(id)arg2;
- (void)_photoLibraryDidChange:(id)arg1;
- (void)photoLibraryDidChange:(id)arg1;
- (void)photoPickerDidCancel:(id)arg1;
- (void)photoPicker:(id)arg1 didChooseImageWithInfo:(id)arg2;
- (void)cameraContainerViewControllerDidCancel:(id)arg1;
- (void)cameraContainerViewController:(id)arg1 didAttachVideoAsset:(id)arg2;
- (void)cameraContainerViewController:(id)arg1 didAttachPhotoAsset:(id)arg2;
- (void)videoTrimmerViewControllerDidCancel:(id)arg1;
- (void)videoTrimmerViewController:(id)arg1 didFailWithError:(id)arg2;
- (void)videoTrimmerViewController:(id)arg1 didTrimVideo:(id)arg2;
- (void)_addOrReplaceMediaAsset:(id)arg1;
- (void)filtersViewControllerDidCancel:(id)arg1;
- (void)filtersViewController:(id)arg1 didEditImage:(id)arg2;
- (void)photoGalleryCollectionsViewControllerDidCancel:(id)arg1;
- (void)photoGalleryCollectionsViewController:(id)arg1 didSelectAssetCollection:(id)arg2;
- (void)photoGalleryCollectionsViewController:(id)arg1 didSelectAdditionalCollectionName:(id)arg2;
- (void)photoGalleryViewAssetCellDidTapEditButton:(id)arg1;
- (void)_editAsset:(id)arg1;
- (void)photoGalleryViewCellDidLongPress:(id)arg1;
- (void)photoGalleryViewCellDidEndTrackingLongPressGesture:(id)arg1;
- (_Bool)photoGalleryViewCellShouldBeginTrackingLongPressGesture:(id)arg1;
- (void)photoGalleryTitleViewDidTap:(id)arg1;
- (unsigned long long)_assetIndexForIndexPath:(id)arg1;
- (id)_assetForIndexPath:(id)arg1;
- (void)_canAddAsset:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (_Bool)_shouldEnableCellForSession;
- (void)_updateAssetCell:(id)arg1 animated:(_Bool)arg2;
- (void)_updateButtonCellForGoLive:(id)arg1;
- (void)_updateButtonCellForRemoveProfileBanner:(id)arg1;
- (void)_updateButtonCellForCollections:(id)arg1;
- (void)_updateButtonCellForVideo:(id)arg1;
- (void)_updateButtonCellForPhoto:(id)arg1;
- (_Bool)_shouldHideAssetCellEditButton;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)_updateItemSizeAndSectionInsetForCollectionViewBounds:(struct CGRect)arg1 withLayout:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)_presentVideoEditingViewControllerWithAttachment:(id)arg1 isAddingAttachment:(_Bool)arg2;
- (void)_presentImageEditingViewControllerWithAttachment:(id)arg1 isAddingAttachment:(_Bool)arg2;
- (void)_presentEditingViewControllerWithAttachment:(id)arg1 isAddingAttachment:(_Bool)arg2;
- (void)_addAttachment:(id)arg1 animated:(_Bool)arg2 preferToEndSession:(_Bool)arg3;
- (void)_addMediaAsset:(id)arg1 shouldEditAsset:(_Bool)arg2;
- (void)_addAsset:(id)arg1 shouldEditAsset:(_Bool)arg2;
- (void)_presentModalViewController:(id)arg1 initialPreferredHeight:(double)arg2 shouldPresentInFullScreen:(_Bool)arg3;
- (void)_presentModalViewController:(id)arg1 initialPreferredHeight:(double)arg2;
- (void)_presentModalViewControllerInFullScreen:(id)arg1;
- (void)_presentModalViewController:(id)arg1;
- (void)presentCollectionsViewController;
- (void)_presentCameraViewControllerWithMode:(long long)arg1;
- (void)_presentCameraViewControllerWithAuthorizationAndMode:(long long)arg1;
- (void)_updateCellAtIndexPath:(id)arg1 animated:(_Bool)arg2;
- (void)_updateForSelectionAnimated:(_Bool)arg1;
- (void)_didSelectAsset:(id)arg1;
- (void)_didSelectRemoveProfileBannerItem;
- (void)_didSelectPeriscopeGoLiveItem;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_updateUserInteractionEnabled;
- (void)_updateForSession;
- (void)_endSession;
- (void)_didTapAdd:(id)arg1;
- (void)_cancelSessionOnEvent:(_Bool)arg1;
- (void)_didTapCancel:(id)arg1;
- (void)_updateScrollIndicatorInsets;
- (void)_updateContentInset;
- (void)layoutGuidesDidChange:(long long)arg1;
- (id)tfn_contentScrollView;
- (long long)preferredStatusBarStyle;
- (void)_presentperiscopeGoLiveTooltip;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)_allPhotosAssetCollection;
- (void)_updateFetchResult;
- (void)_updateNavigationBarItems;
- (void)_updateTitle;
- (void)_updateForAssetCollection;
- (_Bool)_shouldShowRemoveProfileBannerItem;
- (_Bool)_shouldShowCollectionsItem;
- (_Bool)_shouldShowPeriscopeGoLiveItem;
- (_Bool)_shouldShowVideoCameraItem;
- (_Bool)_shouldShowPhotoCameraItem;
- (void)_updateIndexPaths;
- (void)_updateTitleView;
@property(nonatomic) _Bool scrollsToTop;
@property(nonatomic, getter=isScrollEnabled) _Bool scrollEnabled;
- (void)_updateTargetSize;
- (void)removeScrollViewDelegate:(id)arg1;
- (void)addScrollViewDelegate:(id)arg1;
- (void)_updateBackgroundColor;
- (void)cancelSession;
- (void)_updateForAttachments;
- (void)beginSessionWithAttachments:(id)arg1;
- (void)dealloc;
- (void)_updateFetchPredicate;
- (id)initWithAttachmentTypes:(unsigned long long)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

