//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView, UILabel;

@interface T1PhotoMediaRailButtonCell : UICollectionViewCell
{
    unsigned long long _buttonType;
    UIImageView *_imageView;
    UILabel *_titleLabel;
}

@property(copy, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) unsigned long long buttonType; // @synthesize buttonType=_buttonType;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)_t1_desiredImageSize;
- (void)_t1_updateImageView;
- (void)_t1_updateAccessibilityLabel;
- (void)_t1_updateTitleLabel;
- (id)initWithFrame:(struct CGRect)arg1;

@end

