//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNItemsTableRowAdapter.h>

@protocol T1PlacePickerDisclaimerRowAdapterDelegate;

@interface T1PlacePickerDisclaimerRowAdapter : TFNItemsTableRowAdapter
{
    _Bool _screenshotInProgress;
    id <T1PlacePickerDisclaimerRowAdapterDelegate> _delegate;
}

@property(nonatomic) _Bool screenshotInProgress; // @synthesize screenshotInProgress=_screenshotInProgress;
@property(nonatomic) __weak id <T1PlacePickerDisclaimerRowAdapterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_startSnapshotForLocation:(id)arg1 size:(struct CGSize)arg2 completionHandle:(CDUnknownBlockType)arg3;
- (void)dataViewController:(id)arg1 willDisplayCell:(id)arg2 forItem:(id)arg3 withOptions:(id)arg4 atIndexPath:(id)arg5;
- (id)dataViewController:(id)arg1 tableViewCellForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (double)dataViewController:(id)arg1 tableViewHeightForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;

@end

