//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

#import <T1Twitter/T1ProfileUserInfoViewDelegate-Protocol.h>
#import <T1Twitter/T1ResizableHeaderSubheader-Protocol.h>
#import <T1Twitter/TFNTwitterAuthenticated-Protocol.h>
#import <T1Twitter/UIViewControllerPreviewingDelegate-Protocol.h>

@class NSString, T1ProfileUserInfoView, TFNFloatingViewAwarePreviewingDelegate, TFNTwitterAccount;
@protocol T1ProfileDataSource;

@interface T1ProfileUserInfoViewController : TFNViewController <T1ProfileUserInfoViewDelegate, UIViewControllerPreviewingDelegate, T1ResizableHeaderSubheader, TFNTwitterAuthenticated>
{
    TFNTwitterAccount *_account;
    CDUnknownBlockType _preferredHeightCheckBlock;
    id _subheaderInfo;
    id <T1ProfileDataSource> _dataSource;
    CDUnknownBlockType _birthdayTapBlock;
    TFNFloatingViewAwarePreviewingDelegate *_previewingDelegate;
}

@property(retain, nonatomic) TFNFloatingViewAwarePreviewingDelegate *previewingDelegate; // @synthesize previewingDelegate=_previewingDelegate;
@property(copy, nonatomic) CDUnknownBlockType birthdayTapBlock; // @synthesize birthdayTapBlock=_birthdayTapBlock;
@property(retain, nonatomic) id <T1ProfileDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) id subheaderInfo; // @synthesize subheaderInfo=_subheaderInfo;
@property(copy, nonatomic) CDUnknownBlockType preferredHeightCheckBlock; // @synthesize preferredHeightCheckBlock=_preferredHeightCheckBlock;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)_muteUser:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_unmuteUser:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)_followersViewControllerWithTab:(unsigned long long)arg1;
- (id)_followingViewController;
- (_Bool)isUserProtectedFromViewingAccount;
- (void)_fontSizeDidChange;
- (void)scribeViewImpressionWithParameters:(id)arg1;
- (id)scribeSection;
- (id)scribePage;
- (id)scribe;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)profileUserInfoView:(id)arg1 didTapStructuredLocation:(id)arg2;
- (void)profileUserInfoView:(id)arg1 didTapBioActiveRange:(id)arg2;
- (void)profileUserInfoView:(id)arg1 didTapContributorLearnMore:(id)arg2;
- (void)profileUserInfoView:(id)arg1 didTapUnmute:(id)arg2;
- (void)profileUserInfoViewDidTapBirthday:(id)arg1;
- (void)profileUserInfoViewDidTapFollowing:(id)arg1;
- (void)profileUserInfoViewDidTapFollowers:(id)arg1;
- (void)profileUserInfoView:(id)arg1 didLongPressURL:(id)arg2 inView:(id)arg3;
- (void)profileUserInfoView:(id)arg1 didTapURL:(id)arg2;
- (double)preferredHeight;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)loadView;
- (void)showFollowersWithTab:(unsigned long long)arg1;
- (void)reloadData;
@property(readonly, nonatomic) T1ProfileUserInfoView *infoView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

