//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSString, TFNTwitterAccount;
@protocol T1ProfileDataSource;

@interface T1ProfileFriendsFollowingViewModel : NSObject
{
    id <T1ProfileDataSource> _profileDataSource;
    TFNTwitterAccount *_account;
    NSString *_displayString;
    NSArray *_previewUsers;
    unsigned long long _othersCount;
    NSString *_othersCountString;
    NSString *_othersCountDisplayString;
}

@property(readonly, nonatomic) NSString *othersCountDisplayString; // @synthesize othersCountDisplayString=_othersCountDisplayString;
@property(readonly, nonatomic) NSString *othersCountString; // @synthesize othersCountString=_othersCountString;
@property(readonly, nonatomic) unsigned long long othersCount; // @synthesize othersCount=_othersCount;
@property(readonly, nonatomic) NSArray *previewUsers; // @synthesize previewUsers=_previewUsers;
@property(readonly, nonatomic) NSString *displayString; // @synthesize displayString=_displayString;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(readonly, nonatomic) id <T1ProfileDataSource> profileDataSource; // @synthesize profileDataSource=_profileDataSource;
- (void).cxx_destruct;
- (_Bool)_t1_willShowPreviewUsers;
- (void)_t1_generateDisplayString;
- (void)_t1_generateOthers;
- (void)_t1_generatePreviewUsers;
- (id)initWithAccount:(id)arg1 profileDataSource:(id)arg2;
- (id)init;

@end

