//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class TFNTwitterAccount, UIViewController;

@interface T1PromptNavigationHelper : NSObject
{
    UIViewController *_controller;
    TFNTwitterAccount *_account;
}

@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(readonly, nonatomic) __weak UIViewController *controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (id)previewURL:(id)arg1;
- (_Bool)handleURL:(id)arg1;
- (id)init;
- (id)initWithController:(id)arg1 account:(id)arg2;

@end

