//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <T1Twitter/TFNTwitterPushNotificationRoute-Protocol.h>

@class NSMapTable, NSString;

@interface T1PushRoute : NSObject <TFNTwitterPushNotificationRoute>
{
    NSMapTable *_homeTimelineRefreshByAccount;
    NSMapTable *_followerRequestsRefreshByAccount;
    NSMapTable *_accountRefreshByAccount;
    NSMapTable *_accountBadgesRefreshByAccount;
}

@property(readonly, nonatomic) NSMapTable *accountBadgesRefreshByAccount; // @synthesize accountBadgesRefreshByAccount=_accountBadgesRefreshByAccount;
@property(readonly, nonatomic) NSMapTable *accountRefreshByAccount; // @synthesize accountRefreshByAccount=_accountRefreshByAccount;
@property(readonly, nonatomic) NSMapTable *followerRequestsRefreshByAccount; // @synthesize followerRequestsRefreshByAccount=_followerRequestsRefreshByAccount;
@property(readonly, nonatomic) NSMapTable *homeTimelineRefreshByAccount; // @synthesize homeTimelineRefreshByAccount=_homeTimelineRefreshByAccount;
- (void).cxx_destruct;
- (id)_t1_ephemeralStateForHighlightsPushPayload:(id)arg1 context:(long long)arg2;
- (id)_t1_urlWithPossibleTargetTabQueryParam:(id)arg1 account:(id)arg2 category:(long long)arg3;
- (id)ephemeralStateForPushPayload:(id)arg1 context:(long long)arg2;
- (void)willRoutePushPayload:(id)arg1 context:(long long)arg2;
- (id)t1_accountBadgesRefreshForAccount:(id)arg1;
- (id)t1_accountRefreshForAccount:(id)arg1;
- (id)t1_followerRequestsRefreshForAccount:(id)arg1;
- (id)t1_homeTimelineRefreshForAccount:(id)arg1;
- (id)t1_throttledBlockForAccountMapping:(id)arg1 account:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)ambientNotificationForPayload:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)handlePushPayload:(id)arg1 context:(long long)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

