//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

@class CAShapeLayer, NSMutableArray, NSString, TFNTwitterAccount, TFNTwitterAvatarImageView, UIColor, UIImage, UILongPressGestureRecognizer, UITapGestureRecognizer, UIView;

@interface T1QRCodeViewController : TFNViewController
{
    int originalQRSize;
    int **qrBitmap;
    TFNTwitterAccount *_account;
    CAShapeLayer *_fillLayer;
    NSString *_qrUrl;
    UIImage *_qrCardImage;
    UIView *_qrCardView;
    TFNTwitterAvatarImageView *_avatarImageView;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    UITapGestureRecognizer *_tapGestureRecognizer;
    NSMutableArray *_qrBackgroundColors;
    UIColor *_qrCurrentBackgroundColor;
}

@property(retain, nonatomic) UIColor *qrCurrentBackgroundColor; // @synthesize qrCurrentBackgroundColor=_qrCurrentBackgroundColor;
@property(retain, nonatomic) NSMutableArray *qrBackgroundColors; // @synthesize qrBackgroundColors=_qrBackgroundColors;
@property(readonly, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(readonly, nonatomic) UILongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
@property(readonly, nonatomic) TFNTwitterAvatarImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(readonly, nonatomic) UIView *qrCardView; // @synthesize qrCardView=_qrCardView;
@property(readonly, nonatomic) UIImage *qrCardImage; // @synthesize qrCardImage=_qrCardImage;
@property(readonly, nonatomic) NSString *qrUrl; // @synthesize qrUrl=_qrUrl;
@property(readonly, nonatomic) CAShapeLayer *fillLayer; // @synthesize fillLayer=_fillLayer;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)scribeSection;
- (void)dealloc;
- (void)_t1_imageDisplayView;
- (void)share;
- (void)_t1_longPressAction:(id)arg1;
- (_Bool)_t1_hasBottomNeighbor:(int)arg1 col:(int)arg2;
- (_Bool)_t1_hasTopNeighbor:(int)arg1 col:(int)arg2;
- (_Bool)_t1_hasRightNeighbor:(int)arg1 col:(int)arg2;
- (_Bool)_t1_hasLeftNeighbor:(int)arg1 col:(int)arg2;
- (unsigned long long)_t1_getCornerOptionForDotAtRow:(int)arg1 col:(int)arg2;
- (id)_t1_drawRoundedQRImageWithColor:(id)arg1;
- (void)_t1_removeAvatarAndBirdBlocksFromQRBitmap;
- (void)_t1_getBitmapFromQRImage:(struct CGImage *)arg1;
- (void)_t1_generateQRCode;
- (void)_t1_obtainCurrentQRImage;
- (void)_t1_updateQRBackgroundColor;
- (void)_t1_tapAction:(id)arg1;
- (void)_t1_addQRCardView;
- (void)_t1_addOverlay;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

@end

