//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

#import <T1Twitter/T1SecurityTOTPCodeGeneratorViewDelegate-Protocol.h>
#import <T1Twitter/TFNTwitterAuthenticated-Protocol.h>

@class NSString, T1SecurityTOTPCodeGeneratorView, TFNTwitterAccount, TFSTimer;

@interface T1SecurityTOTPCodeGeneratorViewController : TFNViewController <TFNTwitterAuthenticated, T1SecurityTOTPCodeGeneratorViewDelegate>
{
    TFSTimer *_loadTotpTimer;
    _Bool _shouldForceUpdate;
    _Bool _shouldSkipUpdate;
    _Bool _warning;
    TFNTwitterAccount *_account;
    NSString *_totpCode;
    T1SecurityTOTPCodeGeneratorView *_generatorView;
    NSString *_TOTPKey;
}

@property(nonatomic) _Bool warning; // @synthesize warning=_warning;
@property(nonatomic) _Bool shouldSkipUpdate; // @synthesize shouldSkipUpdate=_shouldSkipUpdate;
@property(nonatomic) _Bool shouldForceUpdate; // @synthesize shouldForceUpdate=_shouldForceUpdate;
@property(retain, nonatomic) NSString *TOTPKey; // @synthesize TOTPKey=_TOTPKey;
@property(retain, nonatomic) T1SecurityTOTPCodeGeneratorView *generatorView; // @synthesize generatorView=_generatorView;
@property(readonly, nonatomic) NSString *totpCode; // @synthesize totpCode=_totpCode;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (_Bool)tfn_prefersSubtitleInTitleHeaderView;
- (_Bool)t1_showsComposeAction;
- (void)totpCodeGeneratorView:(id)arg1 didTapHereButton:(id)arg2;
- (_Bool)_t1_getTOTPKey;
- (_Bool)_t1_shouldWarn;
- (void)_t1_toggleLabelBlink:(id)arg1;
- (void)_t1_StopWarning;
- (void)_t1_StartWarning;
- (void)_t1_timerCallback:(id)arg1;
- (void)_t1_stopTimer;
- (void)_t1_initTimer;
- (void)_t1_loadTOTPCode:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

