//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNItemsDataViewController.h>

@class NSArray, NSDictionary, NSMutableArray, T1SearchFilterRowAdapter, T1SearchHeaderTableRowAdapter, TFNTwitterAccount, TFNTwitterScribe;
@protocol T1SearchFiltersViewControllerDelegate;

@interface T1SearchFiltersViewController : TFNItemsDataViewController
{
    _Bool _locationFilterEnabled;
    _Bool _followingFilterEnabled;
    _Bool _hideBlockedContent;
    _Bool _searchSettingsNeedsUpdate;
    TFNTwitterAccount *_account;
    id <T1SearchFiltersViewControllerDelegate> _delegate;
    TFNTwitterScribe *_scribe;
    NSDictionary *_scribeParameters;
    NSArray *_initialSelectedIndexes;
    NSMutableArray *_selectedIndexes;
    NSArray *_peopleFilters;
    NSArray *_locationFilters;
    NSArray *_staticSections;
    T1SearchFilterRowAdapter *_selectedFilterAdapter;
    T1SearchHeaderTableRowAdapter *_headerAdapter;
}

@property(nonatomic) _Bool searchSettingsNeedsUpdate; // @synthesize searchSettingsNeedsUpdate=_searchSettingsNeedsUpdate;
@property(nonatomic) _Bool hideBlockedContent; // @synthesize hideBlockedContent=_hideBlockedContent;
@property(retain, nonatomic) T1SearchHeaderTableRowAdapter *headerAdapter; // @synthesize headerAdapter=_headerAdapter;
@property(retain, nonatomic) T1SearchFilterRowAdapter *selectedFilterAdapter; // @synthesize selectedFilterAdapter=_selectedFilterAdapter;
@property(retain, nonatomic) NSArray *staticSections; // @synthesize staticSections=_staticSections;
@property(retain, nonatomic) NSArray *locationFilters; // @synthesize locationFilters=_locationFilters;
@property(retain, nonatomic) NSArray *peopleFilters; // @synthesize peopleFilters=_peopleFilters;
@property(retain, nonatomic) NSMutableArray *selectedIndexes; // @synthesize selectedIndexes=_selectedIndexes;
@property(retain, nonatomic) NSArray *initialSelectedIndexes; // @synthesize initialSelectedIndexes=_initialSelectedIndexes;
@property(nonatomic) _Bool followingFilterEnabled; // @synthesize followingFilterEnabled=_followingFilterEnabled;
@property(nonatomic) _Bool locationFilterEnabled; // @synthesize locationFilterEnabled=_locationFilterEnabled;
@property(retain, nonatomic) NSDictionary *scribeParameters; // @synthesize scribeParameters=_scribeParameters;
@property(retain, nonatomic) TFNTwitterScribe *scribe; // @synthesize scribe=_scribe;
@property(nonatomic) __weak id <T1SearchFiltersViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)scribeComponent;
- (id)scribeSection;
- (id)scribePage;
- (id)_t1_search_hideMutedAndBlockedTimelineDescriptionItem;
- (id)_t1_search_hideMutedAndBlockedTimelineItem;
- (id)_t1_search_searchSettingsSection;
- (id)_t1_search_locationSectionWithCorrectedAdapters;
- (id)_t1_search_peopleSectionWithCorrectedAdapters;
- (id)_t1_search_locationSectionTextEntries;
- (id)_t1_search_peopleSectionTextEntries;
- (void)_requestLocationForIndexPath:(id)arg1;
- (void)didSelectItem:(id)arg1 atIndexPath:(id)arg2;
- (unsigned long long)_t1_search_initialSelectedIndexForSection:(unsigned long long)arg1;
- (void)_t1_search_updateFilters;
- (void)_t1_search_updateSearchSettingsWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)_t1_search_fetchSearchSettings;
- (void)_t1_search_addModalControls;
- (void)_t1_search_updateSections;
- (void)_t1_search_applyFilters;
- (void)_t1_search_applyTapped;
- (void)_t1_search_cancelTapped;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCollectionViewLayout:(id)arg1;
- (id)init;
- (id)initWithAccount:(id)arg1;

@end

