//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface T1SensitiveMediaCellAXHelper : NSObject
{
    NSString *_accessibilityLabel;
    unsigned long long _accessibilityTraits;
    struct CGRect _accessibilityFrame;
}

@property(nonatomic) struct CGRect accessibilityFrame; // @synthesize accessibilityFrame=_accessibilityFrame;
@property(nonatomic) unsigned long long accessibilityTraits; // @synthesize accessibilityTraits=_accessibilityTraits;
@property(copy, nonatomic) NSString *accessibilityLabel; // @synthesize accessibilityLabel=_accessibilityLabel;
- (void).cxx_destruct;
- (_Bool)isAccessibilityElement;

@end

