//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class T1SecurityLoginRequestCell;

@protocol T1SecurityLoginRequestCellDelegate <NSObject>
- (void)loginRequestCell:(T1SecurityLoginRequestCell *)arg1 didMakeSelection:(long long)arg2;
@end

