//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class TFNDataViewController;

@interface T1StatusTableWebManager : NSObject
{
    TFNDataViewController *_controller;
}

- (void).cxx_destruct;
- (id)presentWebViewControllerWithURL:(id)arg1 forVideo:(_Bool)arg2 status:(id)arg3 previewing:(_Bool)arg4;
- (id)initWithTableViewController:(id)arg1;

@end

