//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1StatusInlineActionButton.h>

@interface T1StatusInlineReplyButton : T1StatusInlineActionButton
{
}

+ (id)buttonImageNameForUIControlState:(unsigned long long)arg1;
- (void)statusDidUpdate:(id)arg1 animated:(_Bool)arg2;
- (id)actionSheetTitle;
- (id)initWithOptions:(unsigned long long)arg1 account:(id)arg2;

@end

