//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1UserOrRecommendationTableRowAdapter.h>

@class TFNDataViewController, TFNTwitterSuggestsModule;

@interface T1SuggestsModuleCarouselDataViewAdapterUserOrRecommendationAdapter : T1UserOrRecommendationTableRowAdapter
{
    _Bool _shouldScrollToNextIndexPathOfUserInFollowAction;
    TFNDataViewController *_dataViewController;
    long long _absolutePositionOfSuggestsModule;
    TFNTwitterSuggestsModule *_suggestsModule;
}

@property(readonly, nonatomic) _Bool shouldScrollToNextIndexPathOfUserInFollowAction; // @synthesize shouldScrollToNextIndexPathOfUserInFollowAction=_shouldScrollToNextIndexPathOfUserInFollowAction;
@property(retain, nonatomic) TFNTwitterSuggestsModule *suggestsModule; // @synthesize suggestsModule=_suggestsModule;
@property(nonatomic) long long absolutePositionOfSuggestsModule; // @synthesize absolutePositionOfSuggestsModule=_absolutePositionOfSuggestsModule;
@property(readonly, nonatomic) __weak TFNDataViewController *dataViewController; // @synthesize dataViewController=_dataViewController;
- (void).cxx_destruct;
- (unsigned long long)_bioInclusionModeForSuggestsModuleType:(id)arg1;
- (long long)_cellStyleForSuggestsModuleType:(id)arg1;
- (void)_advanceCollectionViewForFollowActionInUserView:(id)arg1;
- (_Bool)userView:(id)arg1 shouldPerformAction:(unsigned long long)arg2;
- (id)dataViewController:(id)arg1 scribeContextForItem:(id)arg2 atIndexPath:(id)arg3;
- (id)initWithDataViewController:(id)arg1;

@end

