//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNTabbedViewController.h>

#import <T1Twitter/TFNScopeBarSelectionDelegate-Protocol.h>
#import <T1Twitter/TFNTabbedViewControllerDelegate-Protocol.h>

@class NSString, TFNScopeBar, UIColor, UIView;
@protocol T1TabbedTimelinesViewControllerDataSource, T1TabbedTimelinesViewControllerDelegate;

@interface T1TabbedTimelinesViewController : TFNTabbedViewController <TFNTabbedViewControllerDelegate, TFNScopeBarSelectionDelegate>
{
    _Bool _shouldAutoHideNavigationBar;
    _Bool _navigationBarHidden;
    id <T1TabbedTimelinesViewControllerDelegate> _tabbedTimelinesDelegate;
    double _scrollOffset;
    TFNScopeBar *_scopeBar;
    UIView *_emptyBar;
}

@property(nonatomic) _Bool navigationBarHidden; // @synthesize navigationBarHidden=_navigationBarHidden;
@property(retain, nonatomic) UIView *emptyBar; // @synthesize emptyBar=_emptyBar;
@property(retain, nonatomic) TFNScopeBar *scopeBar; // @synthesize scopeBar=_scopeBar;
@property(nonatomic) double scrollOffset; // @synthesize scrollOffset=_scrollOffset;
@property(nonatomic) _Bool shouldAutoHideNavigationBar; // @synthesize shouldAutoHideNavigationBar=_shouldAutoHideNavigationBar;
@property(nonatomic) __weak id <T1TabbedTimelinesViewControllerDelegate> delegate; // @synthesize delegate=_tabbedTimelinesDelegate;
- (void).cxx_destruct;
- (void)_barSelectedItemAtIndex:(long long)arg1;
- (double)_tabBarHeight;
- (void)scopeBarDidSelectMoreItem:(id)arg1;
- (void)scopeBar:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (void)_reloadSegmentData;
- (void)tabbedViewController:(id)arg1 didSelectViewControllerAtIndex:(long long)arg2;
- (void)tabbedViewController:(id)arg1 willSelectViewControllerAtIndex:(long long)arg2;
- (void)_layoutBar;
@property(retain, nonatomic) UIColor *segmentedControlStrokeColor;
@property(readonly, nonatomic) double topPaddingMaximumHeight;
@property(readonly, nonatomic) double topPaddingHeight;
@property(readonly, nonatomic) double navigationBarHeight;
@property(readonly, nonatomic) double barExpansionOffset;
- (double)lengthOfLayoutGuide:(long long)arg1 forEnvironment:(id)arg2;
- (void)layoutGuidesDidChange:(long long)arg1;
- (void)reloadViewControllerData;
- (void)setSelectedIndex:(long long)arg1;
@property(nonatomic) __weak id <T1TabbedTimelinesViewControllerDataSource> dataSource; // @dynamic dataSource;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

