//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSString, T1TabViewGroup;

@protocol T1TabView <NSObject>
@property(copy, nonatomic) NSString *scribePage;

@optional
+ (void)normalizeTabViewsInGroup:(T1TabViewGroup *)arg1;
@end

