//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface T1TimelineUserRelationships : NSObject
{
}

+ (void)loadRelationshipsForUsersInDataViewController:(id)arg1 objects:(id)arg2 account:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)loadRelationshipsForUsersInDataViewController:(id)arg1 objects:(id)arg2 account:(id)arg3;
+ (void)_performRequest:(id)arg1 controller:(id)arg2 usersWithoutRelationship:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)_addModelObjectUsers:(id)arg1 account:(id)arg2 toSet:(id)arg3;

@end

