//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, T1TweetDetailsTweetComposerViewModel, TFNTwitterUser;

@interface T1TweetDetailsTweetComposerItem : NSObject
{
    T1TweetDetailsTweetComposerViewModel *_tweetComposerViewModel;
    NSString *_accountID;
    TFNTwitterUser *_user;
}

+ (id)tfn_defaultDataViewAdapter;
@property(retain, nonatomic) TFNTwitterUser *user; // @synthesize user=_user;
@property(readonly, copy, nonatomic) NSString *accountID; // @synthesize accountID=_accountID;
@property(retain, nonatomic) T1TweetDetailsTweetComposerViewModel *tweetComposerViewModel; // @synthesize tweetComposerViewModel=_tweetComposerViewModel;
- (void).cxx_destruct;
- (id)initWithTweetComposerViewModel:(id)arg1 user:(id)arg2 accountID:(id)arg3;

@end

