//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNActiveTextItemTableRowAdapter.h>

@interface T1TweetDetailsAttributedStringItemTableRowAdapter : TFNActiveTextItemTableRowAdapter
{
    CDUnknownBlockType _shouldShowSocialContextForFocalStatusBlock;
}

@property(copy, nonatomic) CDUnknownBlockType shouldShowSocialContextForFocalStatusBlock; // @synthesize shouldShowSocialContextForFocalStatusBlock=_shouldShowSocialContextForFocalStatusBlock;
- (void).cxx_destruct;
- (id)dataViewController:(id)arg1 previewingViewControllerForItem:(id)arg2 withOptions:(id)arg3 location:(struct CGPoint)arg4 inCell:(id)arg5 atIndexPath:(id)arg6 outSourceRect:(out struct CGRect *)arg7;
- (id)dataViewController:(id)arg1 tableViewCellForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (double)dataViewController:(id)arg1 tableViewHeightForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (id)dataViewController:(id)arg1 calculatedLayoutMetricsForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (id)init;

@end

