//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class TFNTappableHighlightView, UILabel;
@protocol T1TweetstormIndicatorViewDelegate;

@interface T1TweetstormIndicatorView : UIView
{
    UILabel *_label;
    TFNTappableHighlightView *_highlight;
    id <T1TweetstormIndicatorViewDelegate> _delegate;
}

+ (double)defaultHeight;
@property(nonatomic) __weak id <T1TweetstormIndicatorViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TFNTappableHighlightView *highlight; // @synthesize highlight=_highlight;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (void)_t1_highlightViewTapped:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

