//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, TFNTwitterStatus;

@interface T1TweetDetailsSocialProofItem : NSObject
{
    TFNTwitterStatus *_status;
    NSString *_text;
}

+ (id)tfn_defaultDataViewAdapter;
@property(readonly, copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(readonly, nonatomic) TFNTwitterStatus *status; // @synthesize status=_status;
- (void).cxx_destruct;
- (id)initWithStatus:(id)arg1 text:(id)arg2;
- (id)init;

@end

