//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface T1URTResponseModelBuilderBridge : NSObject
{
    // Error parsing type: , name: urtTimelineUID
    // Error parsing type: , name: requestCursor
    // Error parsing type: , name: accountID
    // Error parsing type: , name: buildBridgeDetails
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)modelObjectWithJSONObject:(id)arg1 headerFields:(id)arg2 error:(id *)arg3;
- (id)modelObjectWithJSONData:(id)arg1 headerFields:(id)arg2 error:(id *)arg3;
- (id)initWithURTTimelineUID:(id)arg1 accountID:(id)arg2;

@end

