//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNItemsTableRowAdapter.h>

@protocol T1URTFollowSearchTimelineSource;

@interface T1URTTimelineFollowSearchTableRowAdapter : TFNItemsTableRowAdapter
{
    // Error parsing type: , name: followSearchTimelineSource
    // Error parsing type: , name: kFollowSearchRowHeightDefault
    // Error parsing type: , name: kFollowButtonDimension
    // Error parsing type: , name: kFollowSearchRequestDelay
    // Error parsing type: , name: dismissedEntries
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)dataViewController:(id)arg1 willDisplayCell:(id)arg2 forItem:(id)arg3 withOptions:(id)arg4 atIndexPath:(id)arg5;
- (id)dataViewController:(id)arg1 tableViewCellForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (void)dataViewController:(id)arg1 didSelectItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (double)dataViewController:(id)arg1 tableViewHeightForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
@property(nonatomic, retain) id <T1URTFollowSearchTimelineSource> followSearchTimelineSource; // @synthesize followSearchTimelineSource;

@end

