//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface T1URTTimelineCursorViewModel : NSObject
{
    // Error parsing type: , name: cursor
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *description;
- (_Bool)isSubbranchCursorType;
- (_Bool)isShowMoreThreadCursorType;
- (_Bool)isShowMoreCursorType;

@end

