//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <T1Twitter/T1SocialContextLayoutState-Protocol.h>

@class NSString;

@interface T1UserViewLayoutState : NSObject <T1SocialContextLayoutState>
{
    _Bool socialTextMaxLinesExceeded;
    struct CGRect _userNameLabelFrame;
    struct CGRect _fullNameLabelFrame;
    struct CGRect _followsYouViewFrame;
    struct CGRect _actionControlFrame;
    struct CGRect _bioLabelFrame;
    struct CGRect _socialBadgeFrame;
    struct CGRect _socialTextFrame;
    struct CGRect _bannerImageViewFrame;
    struct CGRect _authorBadgeImageViewFrame;
    struct CGRect _muteBadgeImageViewFrame;
    struct CGRect _infoTextLabelFrame;
    struct CGRect _userInfoButtonFrame;
    struct CGRect _avatarFrame;
    struct CGRect _caretButtonFrame;
    struct CGRect _designatorBadgeFrame;
}

@property(nonatomic) struct CGRect designatorBadgeFrame; // @synthesize designatorBadgeFrame=_designatorBadgeFrame;
@property(nonatomic) struct CGRect caretButtonFrame; // @synthesize caretButtonFrame=_caretButtonFrame;
@property(nonatomic) struct CGRect avatarFrame; // @synthesize avatarFrame=_avatarFrame;
@property(nonatomic) struct CGRect userInfoButtonFrame; // @synthesize userInfoButtonFrame=_userInfoButtonFrame;
@property(nonatomic) struct CGRect infoTextLabelFrame; // @synthesize infoTextLabelFrame=_infoTextLabelFrame;
@property(nonatomic) struct CGRect muteBadgeImageViewFrame; // @synthesize muteBadgeImageViewFrame=_muteBadgeImageViewFrame;
@property(nonatomic) struct CGRect authorBadgeImageViewFrame; // @synthesize authorBadgeImageViewFrame=_authorBadgeImageViewFrame;
@property(nonatomic) struct CGRect bannerImageViewFrame; // @synthesize bannerImageViewFrame=_bannerImageViewFrame;
@property(nonatomic) struct CGRect socialTextFrame; // @synthesize socialTextFrame=_socialTextFrame;
@property(nonatomic) struct CGRect socialBadgeFrame; // @synthesize socialBadgeFrame=_socialBadgeFrame;
@property(nonatomic) struct CGRect bioLabelFrame; // @synthesize bioLabelFrame=_bioLabelFrame;
@property(nonatomic) struct CGRect actionControlFrame; // @synthesize actionControlFrame=_actionControlFrame;
@property(nonatomic) struct CGRect followsYouViewFrame; // @synthesize followsYouViewFrame=_followsYouViewFrame;
@property(nonatomic) struct CGRect fullNameLabelFrame; // @synthesize fullNameLabelFrame=_fullNameLabelFrame;
@property(nonatomic) struct CGRect userNameLabelFrame; // @synthesize userNameLabelFrame=_userNameLabelFrame;
@property(readonly, nonatomic, getter=isSocialTextMaxLinesExceeded) _Bool socialTextMaxLinesExceeded; // @synthesize socialTextMaxLinesExceeded;
@property(readonly, nonatomic, getter=isSocialTextMultipleLines) _Bool socialTextMultipleLines;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

