//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNFormViewController.h>

#import <T1Twitter/T1VerifyPINFormDelegate-Protocol.h>
#import <T1Twitter/TFNTwitterAuthenticated-Protocol.h>

@class NSString, T1VerifyPINForm, TFNBarButtonItem, TFNTwitterAccount, TFNTwitterCallToAction;
@protocol T1VerifyPhoneNumberDelegateProtocol;

@interface T1VerifyPhoneNumberViewController : TFNFormViewController <T1VerifyPINFormDelegate, TFNTwitterAuthenticated>
{
    _Bool _implicitSMSOptInAllowed;
    TFNTwitterAccount *_account;
    TFNTwitterCallToAction *_callToAction;
    id <T1VerifyPhoneNumberDelegateProtocol> _delegate;
    NSString *_phoneNumberString;
    NSString *_scribePage;
    TFNBarButtonItem *_verifyButton;
    unsigned long long _mode;
}

@property(readonly, nonatomic) unsigned long long mode; // @synthesize mode=_mode;
@property(retain, nonatomic) TFNBarButtonItem *verifyButton; // @synthesize verifyButton=_verifyButton;
@property(copy, nonatomic) NSString *scribePage; // @synthesize scribePage=_scribePage;
@property(copy, nonatomic) NSString *phoneNumberString; // @synthesize phoneNumberString=_phoneNumberString;
@property(nonatomic) _Bool implicitSMSOptInAllowed; // @synthesize implicitSMSOptInAllowed=_implicitSMSOptInAllowed;
@property(nonatomic) __weak id <T1VerifyPhoneNumberDelegateProtocol> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)_resendSMS:(id)arg1;
- (void)_verifyTapped;
@property(readonly, nonatomic) T1VerifyPINForm *verifyPINForm;
- (void)verifyPINFormShouldSubmit:(id)arg1;
- (void)submitForm;
- (unsigned long long)inputRequiredBehavior;
- (void)setSections:(id)arg1;
- (id)doneBarButtonItem;
- (struct CGRect)additionalGutterFrame;
- (_Bool)addsDoneBarButtonButtonItemToNavigationBar;
@property(readonly, nonatomic) TFNTwitterCallToAction *callToAction; // @synthesize callToAction=_callToAction;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithPhoneNumber:(id)arg1 mode:(unsigned long long)arg2;
- (id)initWithPhoneNumber:(id)arg1;
- (id)initWithForm:(id)arg1 appearance:(id)arg2 typeaheadStore:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

