//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class T1VideoCaptionsView;
@protocol TAVMediaSelectionOption;

@protocol T1VideoCaptionsViewDelegate
- (void)videoCaptionsView:(T1VideoCaptionsView *)arg1 didSelectMediaSelectionOption:(id <TAVMediaSelectionOption>)arg2;
@end

