//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface T1VideoRecordingDotView : UIView
{
}

- (void)_showAnimated:(_Bool)arg1;
- (void)_hideAnimated:(_Bool)arg1;
- (void)setHidden:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setCurrentTimeInterval:(double)arg1 animated:(_Bool)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

