//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <T1Twitter/PTVBroadcastWatcherObserver-Protocol.h>
#import <T1Twitter/PTVTwitterIntegrationDelegate-Protocol.h>

@class NSString, NSURL, PTVExternalVideoAccessManager, PTVFastImageCacheUtilities, T1PeriscopeAccount, TFNTwitterAccount, TFNTwitterLiveEvent, TFNTwitterStatus, TFNTwitterUser;
@protocol T1WatchBroadcastViewControllerModelDelegate, TFNTwitterCardDataSource, TFNTwitterWatchBroadcastModel;

@interface T1WatchBroadcastViewControllerModel : NSObject <PTVBroadcastWatcherObserver, PTVTwitterIntegrationDelegate>
{
    id <T1WatchBroadcastViewControllerModelDelegate> _delegate;
    id <TFNTwitterWatchBroadcastModel> _broadcast;
    TFNTwitterAccount *_account;
    id <TFNTwitterCardDataSource> _cardDataSource;
    TFNTwitterStatus *_status;
    TFNTwitterStatus *_associatedBroadcastStatus;
    TFNTwitterLiveEvent *_liveEvent;
    TFNTwitterLiveEvent *_associatedLiveEvent;
    NSURL *_shareURL;
    TFNTwitterUser *_broadcastingTwitterUser;
    double _playbackTime;
    T1PeriscopeAccount *_periscopeAccount;
    PTVExternalVideoAccessManager *_externalVideoAccessManager;
    unsigned long long _currentDisplayMode;
    PTVFastImageCacheUtilities *_fastImageCacheUtilities;
    NSString *_refreshIdentifier;
}

@property(copy, nonatomic) NSString *refreshIdentifier; // @synthesize refreshIdentifier=_refreshIdentifier;
@property(retain, nonatomic) PTVFastImageCacheUtilities *fastImageCacheUtilities; // @synthesize fastImageCacheUtilities=_fastImageCacheUtilities;
@property(nonatomic) unsigned long long currentDisplayMode; // @synthesize currentDisplayMode=_currentDisplayMode;
@property(readonly, nonatomic) PTVExternalVideoAccessManager *externalVideoAccessManager; // @synthesize externalVideoAccessManager=_externalVideoAccessManager;
@property(retain, nonatomic) T1PeriscopeAccount *periscopeAccount; // @synthesize periscopeAccount=_periscopeAccount;
@property(readonly, nonatomic) double playbackTime; // @synthesize playbackTime=_playbackTime;
@property(readonly, nonatomic) TFNTwitterUser *broadcastingTwitterUser; // @synthesize broadcastingTwitterUser=_broadcastingTwitterUser;
@property(readonly, nonatomic) NSURL *shareURL; // @synthesize shareURL=_shareURL;
@property(readonly, nonatomic) TFNTwitterLiveEvent *associatedLiveEvent; // @synthesize associatedLiveEvent=_associatedLiveEvent;
@property(readonly, nonatomic) TFNTwitterLiveEvent *liveEvent; // @synthesize liveEvent=_liveEvent;
@property(retain, nonatomic) TFNTwitterStatus *associatedBroadcastStatus; // @synthesize associatedBroadcastStatus=_associatedBroadcastStatus;
@property(readonly, nonatomic) TFNTwitterStatus *status; // @synthesize status=_status;
@property(readonly, nonatomic) id <TFNTwitterCardDataSource> cardDataSource; // @synthesize cardDataSource=_cardDataSource;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(readonly, nonatomic) id <TFNTwitterWatchBroadcastModel> broadcast; // @synthesize broadcast=_broadcast;
@property(readonly, nonatomic) __weak id <T1WatchBroadcastViewControllerModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)broadcastController:(id)arg1 willUpdatePlaybackPointTo:(id)arg2;
- (id)_t1_shareURLWithTimecode:(double)arg1;
- (void)shareURLOfBroadcast:(id)arg1 atTimecode:(double)arg2 initialTimecode:(double)arg3 fromRect:(struct CGRect)arg4 inView:(id)arg5 withCompletion:(CDUnknownBlockType)arg6;
- (void)composeDirectMessageForBroadcast:(id)arg1 atTimecode:(double)arg2 initialTimecode:(double)arg3 fromRect:(struct CGRect)arg4 inView:(id)arg5 withCompletion:(CDUnknownBlockType)arg6;
- (void)composeTweetForBroadcast:(id)arg1 atTimecode:(double)arg2 initialTimecode:(double)arg3 fromRect:(struct CGRect)arg4 inView:(id)arg5 withCompletion:(CDUnknownBlockType)arg6;
- (void)willDismissShareBroadcastScreenWithoutSharingSelectedTimecode:(double)arg1 initialTimecode:(double)arg2;
- (void)willPresentShareBroadcastScreen;
- (_Bool)shouldShowRetweetButton;
- (_Bool)canShareHighlight;
- (_Bool)isSharingHighlightsEnabled;
- (_Bool)isViewingHighlightsEnabled;
- (_Bool)useEdgeTheme;
- (id)retweetGreenColor;
- (id)overrideCopyForPromptingViewerToShareBroadcast;
- (id)blockedTwitterIDs;
- (void)didSetCinemaModeEnabled:(_Bool)arg1;
- (_Bool)shouldHidePeriscopeAppUpsell;
- (id)additionalParametersForStartWatchingLifecycleAPI;
- (void)didSendMessage:(id)arg1;
- (void)deleteBroadcast:(id)arg1;
- (void)didUnblockUser:(id)arg1;
- (void)didBlockUser:(id)arg1;
- (void)retweetBroadcast:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (_Bool)canRetweetBroadcast:(id)arg1;
- (void)reportBroadcast:(id)arg1;
- (void)shareScreenshot:(id)arg1 forBroadcast:(id)arg2;
- (void)shareBroadcast:(id)arg1;
- (void)_t1_processBroadcastUnavailable;
- (void)_t1_processEvents:(id)arg1;
- (void)_t1_processBroadcast:(id)arg1;
- (void)_t1_processGetBroadcastResponse:(id)arg1;
- (void)_t1_disableBlurring;
- (void)_t1_enableBlurring;
- (void)_t1_configureBlurring;
- (void)_t1_configureSSLPinningDelegate;
- (void)_t1_disposeImageCache;
- (void)_t1_configureImageCache;
- (void)_t1_configureStatusesIfNecessary;
- (void)_t1_didReceiveBroadcastingTwitterUser:(id)arg1;
- (void)_t1_requestBroadcastingTwitterUserIfNecessary;
- (id)ptvBroadcast;
- (double)initialPlaybackTimecode;
- (id)scribeParameters;
- (_Bool)shouldBeReadOnlyChatParticipantForDisplayMode:(unsigned long long)arg1;
- (_Bool)canUseTAVCore;
- (id)liveEventOrAssociatedLiveEvent;
- (id)statusOrAssociatedBroadcastStatus;
- (id)playerFactoryIdentifiable;
- (void)setBroadcast:(id)arg1;
- (void)stopRefreshingBroadcast;
- (void)startRefreshingBroadcast;
- (void)authenticatePeriscopeAccountWithCompletion:(CDUnknownBlockType)arg1;
- (void)didUpdateDisplayMode:(unsigned long long)arg1;
- (void)externalVideoPlayerDidReceiveShareURL:(id)arg1;
- (void)externalVideoPlayerDidObservePlaybackStateError:(id)arg1;
- (id)presentationScribeParametersForExternalVideoPlayer:(id)arg1;
- (void)dispose;
- (id)tfs_debugStrings;
- (void)dealloc;
- (id)initWithBroadcast:(id)arg1 account:(id)arg2 cardDataSource:(id)arg3 liveEvent:(id)arg4 playbackTime:(double)arg5 initialDisplayMode:(unsigned long long)arg6 delegate:(id)arg7;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

