//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNAttributedTextView.h>

@interface TFNAttributedTextView (T1Onboarding)
+ (id)onboardingDetailTextViewForText:(id)arg1 activeRanges:(id)arg2;
@end

