//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNActionSheetController.h>

@interface TFNActionSheetController (T1LiveVideo)
+ (id)_t1_updateVideoVisibilityItem:(_Bool)arg1 updateVideoVisibilityBlock:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
+ (id)_t1_trimExcessiveSpacesFromString:(id)arg1;
+ (id)_t1_shareLiveVideoTextForLiveVideoEvent:(id)arg1;
+ (id)shareMenuActionSheetWithLiveVideoEvent:(id)arg1 playerController:(id)arg2 presentingViewController:(id)arg3 sourceView:(id)arg4 account:(id)arg5 canHidePlayer:(_Bool)arg6 updateVideoVisibilityBlock:(CDUnknownBlockType)arg7 completion:(CDUnknownBlockType)arg8;
@end

