//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIColor;

@interface TFNButtonBarView : UIView
{
    _Bool _accentBordersHidden;
    NSArray *_leadingViews;
    NSArray *_trailingViews;
    UIView *_topAccentView;
    UIView *_bottomAccentView;
}

+ (double)trailingViewsSpacing;
+ (double)leadingViewsSpacing;
@property(readonly, nonatomic) UIView *bottomAccentView; // @synthesize bottomAccentView=_bottomAccentView;
@property(readonly, nonatomic) UIView *topAccentView; // @synthesize topAccentView=_topAccentView;
@property(copy, nonatomic) NSArray *trailingViews; // @synthesize trailingViews=_trailingViews;
@property(copy, nonatomic) NSArray *leadingViews; // @synthesize leadingViews=_leadingViews;
@property(nonatomic, getter=isAccentBordersHidden) _Bool accentBordersHidden; // @synthesize accentBordersHidden=_accentBordersHidden;
- (void).cxx_destruct;
- (id)calculatedLayoutMetrics;
- (void)layoutSubviews;
- (struct CGSize)intrinsicContentSize;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(retain, nonatomic) UIColor *bottomAccentColor;
@property(retain, nonatomic) UIColor *topAccentColor;
- (id)initWithFrame:(struct CGRect)arg1;

@end

