//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNDirectMessageModelObject.h>

#import <T1Twitter/NSCoding-Protocol.h>

@class NSMutableArray, NSString, TFNDirectMessageTimelineCursor;
@protocol TFNDirectMessageContext;

@interface TFNDirectMessageInboxTimeline : TFNDirectMessageModelObject <NSCoding>
{
    unsigned long long _countOfUnseenConversations;
    unsigned long long _type;
    TFNDirectMessageTimelineCursor *_cursor;
    long long _lastSeenEventID;
    long long _localLastSeenEventID;
    NSMutableArray *_conversations;
}

+ (_Bool)_validateTransitionFromOldCursor:(id)arg1 toNewCursor:(id)arg2;
@property(retain, nonatomic) NSMutableArray *conversations; // @synthesize conversations=_conversations;
@property(nonatomic) long long localLastSeenEventID; // @synthesize localLastSeenEventID=_localLastSeenEventID;
@property(nonatomic) long long lastSeenEventID; // @synthesize lastSeenEventID=_lastSeenEventID;
@property(retain, nonatomic) TFNDirectMessageTimelineCursor *cursor; // @synthesize cursor=_cursor;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
@property(readonly, nonatomic) unsigned long long countOfUnseenConversations; // @synthesize countOfUnseenConversations=_countOfUnseenConversations;
- (void).cxx_destruct;
- (_Bool)_validateTrustState:(id)arg1;
- (unsigned long long)countOfUnseenConversationsWithLastSeenEventID:(long long)arg1;
- (void)recalculateConversationCounts;
- (unsigned long long)updateConversationPosition:(id)arg1;
- (void)deleteConversation:(id)arg1;
- (void)addConversation:(id)arg1;
@property(readonly, copy) NSString *debugDescription;
- (void)clear;
- (void)pruneOldConversations;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithType:(unsigned long long)arg1;

// Remaining properties
@property(readonly, nonatomic) id <TFNDirectMessageContext> context;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

