//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSNumber, NSString, TFNDirectMessageEntriesResponse;

@interface TFNDirectMessageConversationPageResponse : NSObject
{
    _Bool _hasMore;
    NSNumber *_minID;
    TFNDirectMessageEntriesResponse *_entriesResponse;
}

@property(readonly, nonatomic) TFNDirectMessageEntriesResponse *entriesResponse; // @synthesize entriesResponse=_entriesResponse;
@property(readonly, nonatomic) _Bool hasMore; // @synthesize hasMore=_hasMore;
@property(readonly, nonatomic) NSNumber *minID; // @synthesize minID=_minID;
- (void).cxx_destruct;
- (id)initWithJSONDictionary:(id)arg1 userCache:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

