//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/UITextInput-Protocol.h>

@class NSString, TFNFormField, TFNLayoutMetrics;

@protocol TFNFormTextInput <UITextInput>
+ (double)standardHeightForLayoutMetrics:(TFNLayoutMetrics *)arg1 emphasized:(_Bool)arg2 stacked:(_Bool)arg3;
@property(retain, nonatomic) TFNFormField *formField;
@property(retain, nonatomic) NSString *text;
- (double)baselineYForBounds:(struct CGRect)arg1;
- (struct CGRect)layoutRectInBounds:(struct CGRect)arg1 stacked:(_Bool)arg2;
- (void)updateTextColor;
@end

