//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNFoundMediaObject.h>

@class NSDictionary, NSString, TFNFoundMediaImage, TFNFoundMediaProvider;

@interface TFNFoundMediaItem : TFNFoundMediaObject
{
    NSDictionary *_originDictionary;
    NSString *_URLString;
    TFNFoundMediaProvider *_provider;
    TFNFoundMediaImage *_originalImage;
    TFNFoundMediaImage *_previewImage;
}

+ (id)fetchTrendingItemsWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (id)fetchItemsForKeyword:(id)arg1 withOptions:(id)arg2 completion:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) TFNFoundMediaImage *previewImage; // @synthesize previewImage=_previewImage;
@property(readonly, nonatomic) TFNFoundMediaImage *originalImage; // @synthesize originalImage=_originalImage;
@property(readonly, nonatomic) TFNFoundMediaProvider *provider; // @synthesize provider=_provider;
@property(readonly, copy, nonatomic) NSString *URLString; // @synthesize URLString=_URLString;
@property(readonly, copy, nonatomic) NSDictionary *originDictionary; // @synthesize originDictionary=_originDictionary;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1 parentGroup:(id)arg2;
- (id)initWithJSONDictionary:(id)arg1;
- (id)initWithIdentifier:(id)arg1 originDictionary:(id)arg2 URLString:(id)arg3 provider:(id)arg4 originalImage:(id)arg5 previewImage:(id)arg6 primaryImage:(id)arg7 parentGroup:(id)arg8;
- (id)initWithIdentifier:(id)arg1 primaryImage:(id)arg2 parentGroup:(id)arg3;

@end

