//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class TFSKVODispatcher;
@protocol TFNInputAccessoryViewDelegate;

@interface TFNInputAccessoryView : UIView
{
    id <TFNInputAccessoryViewDelegate> _delegate;
    TFSKVODispatcher *_inputAccessoryFrameKVODispatcher;
}

@property(retain, nonatomic) TFSKVODispatcher *inputAccessoryFrameKVODispatcher; // @synthesize inputAccessoryFrameKVODispatcher=_inputAccessoryFrameKVODispatcher;
@property(nonatomic) __weak id <TFNInputAccessoryViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)willMoveToSuperview:(id)arg1;
- (id)initWithDelegate:(id)arg1;

@end

