//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNOnboardingSubtaskState.h>

@interface TFNOnboardingWaitSpinnerSubtaskState : TFNOnboardingSubtaskState
{
    long long _waitTimeMs;
}

@property(nonatomic) long long waitTimeMs; // @synthesize waitTimeMs=_waitTimeMs;
- (void)addStateToJSONDictionary:(id)arg1;

@end

