//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface TFNOnboardingInterestPickerCustomInterest : NSObject
{
    NSString *_interestName;
    NSString *_contextToken;
}

@property(readonly, nonatomic) NSString *contextToken; // @synthesize contextToken=_contextToken;
@property(readonly, nonatomic) NSString *interestName; // @synthesize interestName=_interestName;
- (void).cxx_destruct;
- (id)initWithInterestName:(id)arg1 contextToken:(id)arg2;

@end

