//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface TFNOnboardingNavigationContext : NSObject
{
    _Bool _error;
    NSString *_action;
}

+ (id)errorNavigationContext;
@property(copy, nonatomic) NSString *action; // @synthesize action=_action;
@property(readonly, nonatomic, getter=isError) _Bool error; // @synthesize error=_error;
- (void).cxx_destruct;

@end

