//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

#import <TFNUI/TFNHapticFeedback-Protocol.h>
#import <TFNUI/TFNPullToLoadTopControl-Protocol.h>

@class NSString, UIActivityIndicatorView, UIColor, UIFont, UIImageView, UIImpactFeedbackGenerator, UILabel, UINotificationFeedbackGenerator, UIScrollView, UISelectionFeedbackGenerator;

@interface TFNPullToRefreshControl : UIControl <TFNPullToLoadTopControl, TFNHapticFeedback>
{
    long long _status;
    _Bool _fromScrolling;
    _Bool _needsContentInsetUpdate;
    _Bool _managesScrollViewContentInset;
    _Bool _hideWhenNotInUse;
    _Bool _shouldTriggerHapticFeedback;
    unsigned long long _animationStyle;
    double _thresholdOffsetY;
    UIImpactFeedbackGenerator *_impactFeedbackGenerator;
    UIColor *_pullToRefreshColor;
    UIScrollView *_savedScrollView;
    UIImageView *_arrowView;
    UIActivityIndicatorView *_activityView;
    UILabel *_textLabel;
    struct CGSize _controlOffset;
    struct UIEdgeInsets _savedScrollInsets;
}

+ (void)setHapticFeedbackEnabled:(_Bool)arg1;
+ (_Bool)isHapticFeedbackEnabled;
+ (void)setPullToRefreshTextFont:(id)arg1;
+ (void)setPullToRefreshTextColor:(id)arg1;
+ (void)setPullToRefreshColor:(id)arg1;
+ (void)setAreSoundEffectsEnabledBlock:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) UIActivityIndicatorView *activityView; // @synthesize activityView=_activityView;
@property(retain, nonatomic) UIImageView *arrowView; // @synthesize arrowView=_arrowView;
@property(readonly, nonatomic) struct UIEdgeInsets savedScrollInsets; // @synthesize savedScrollInsets=_savedScrollInsets;
@property(nonatomic) __weak UIScrollView *savedScrollView; // @synthesize savedScrollView=_savedScrollView;
@property(nonatomic) _Bool shouldTriggerHapticFeedback; // @synthesize shouldTriggerHapticFeedback=_shouldTriggerHapticFeedback;
@property(retain, nonatomic) UIColor *pullToRefreshColor; // @synthesize pullToRefreshColor=_pullToRefreshColor;
@property(readonly, nonatomic) UIImpactFeedbackGenerator *impactFeedbackGenerator; // @synthesize impactFeedbackGenerator=_impactFeedbackGenerator;
@property(nonatomic) double thresholdOffsetY; // @synthesize thresholdOffsetY=_thresholdOffsetY;
@property(nonatomic) unsigned long long animationStyle; // @synthesize animationStyle=_animationStyle;
@property(nonatomic) _Bool hideWhenNotInUse; // @synthesize hideWhenNotInUse=_hideWhenNotInUse;
@property(nonatomic) struct CGSize controlOffset; // @synthesize controlOffset=_controlOffset;
@property(nonatomic) _Bool managesScrollViewContentInset; // @synthesize managesScrollViewContentInset=_managesScrollViewContentInset;
- (void).cxx_destruct;
- (void)performHapticFeedback:(unsigned long long)arg1;
- (void)prepareHapticFeedback:(unsigned long long)arg1;
- (void)_playSoundNamed:(id)arg1;
- (double)_hideWhenNotInUseAlphaForScrollView:(id)arg1;
- (void)_setStatus:(unsigned long long)arg1 fromScrolling:(_Bool)arg2;
- (void)_updateContentInset:(id)arg1 animated:(_Bool)arg2;
- (void)updateScrollViewContentInset:(id)arg1 animated:(_Bool)arg2;
- (void)scrollViewContentInsetDidReset:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setLoading:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
@property(nonatomic) _Bool loading;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(readonly, nonatomic) _Bool isCurrentlyInUse;
@property(retain, nonatomic) UIColor *color;
@property(retain, nonatomic) UIColor *textColor;
@property(retain, nonatomic) UIFont *textFont;
@property(nonatomic) _Bool showsIcon;
@property(retain, nonatomic) NSString *text;
@property(nonatomic) _Bool showsText;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) UINotificationFeedbackGenerator *notificationFeedbackGenerator;
@property(readonly, nonatomic) UISelectionFeedbackGenerator *selectionFeedbackGenerator;
@property(readonly) Class superclass;

@end

