//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSString, TFNPeopleDiscoveryModuleLayoutHeader;

@interface TFNPeopleDiscoveryFeaturedUsersPage : NSObject
{
    TFNPeopleDiscoveryModuleLayoutHeader *_header;
    NSString *_backgroundImageURL;
    NSArray *_userRecommendations;
}

@property(readonly, copy, nonatomic) NSArray *userRecommendations; // @synthesize userRecommendations=_userRecommendations;
@property(readonly, copy, nonatomic) NSString *backgroundImageURL; // @synthesize backgroundImageURL=_backgroundImageURL;
@property(readonly, nonatomic) TFNPeopleDiscoveryModuleLayoutHeader *header; // @synthesize header=_header;
- (void).cxx_destruct;
- (id)initWithUserRecommendations:(id)arg1 backgroundImageURL:(id)arg2 header:(id)arg3;

@end

