//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class PHCachingImageManager, PHImageRequestOptions;
@protocol TFNPhotoCachingImageManagerHelperDelegate;

@interface TFNPhotoCachingImageManagerHelper : NSObject
{
    PHCachingImageManager *_imageManager;
    id <TFNPhotoCachingImageManagerHelperDelegate> _delegate;
    long long _contentMode;
    PHImageRequestOptions *_options;
    struct CGSize _targetSize;
    struct CGRect _cachedRect;
}

@property(retain, nonatomic) PHImageRequestOptions *options; // @synthesize options=_options;
@property(nonatomic) long long contentMode; // @synthesize contentMode=_contentMode;
@property(nonatomic) struct CGSize targetSize; // @synthesize targetSize=_targetSize;
@property(readonly, nonatomic) struct CGRect cachedRect; // @synthesize cachedRect=_cachedRect;
@property(nonatomic) __weak id <TFNPhotoCachingImageManagerHelperDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (int)requestImageForAsset:(id)arg1 resultHandler:(CDUnknownBlockType)arg2;
- (void)updateForRect:(struct CGRect)arg1;
- (void)invalidate;
- (_Bool)_canUseCachingImageManager;
@property(readonly, nonatomic) PHCachingImageManager *imageManager;
- (void)dealloc;

@end

