//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface TFNPeopleDiscoveryShowMore : NSObject
{
    unsigned long long _initialToShow;
    unsigned long long _extraToShow;
    NSString *_text;
}

@property(readonly, nonatomic) NSString *text; // @synthesize text=_text;
@property(readonly, nonatomic) unsigned long long extraToShow; // @synthesize extraToShow=_extraToShow;
@property(readonly, nonatomic) unsigned long long initialToShow; // @synthesize initialToShow=_initialToShow;
- (void).cxx_destruct;
- (id)initWithInitialToShow:(unsigned long long)arg1 extraToShow:(unsigned long long)arg2 text:(id)arg3;
- (id)initWithJSONDictionary:(id)arg1;

@end

