//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface TFNPageSheetRootViewController : UIViewController
{
    CDUnknownBlockType _presentViewControllerBlock;
}

@property(copy, nonatomic) CDUnknownBlockType presentViewControllerBlock; // @synthesize presentViewControllerBlock=_presentViewControllerBlock;
- (void).cxx_destruct;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidAppear:(_Bool)arg1;

@end

