//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSPointerArray, NSString, TFNTwitterAccount, TFNTwitterMomentCapsule;
@protocol TFNTwitterMomentSportEventsDataManager;

@interface TFNTwitterMockMomentsCapsuleDataManager : NSObject
{
    TFNTwitterMomentCapsule *_capsule;
    NSArray *_pivotList;
    id <TFNTwitterMomentSportEventsDataManager> _sportEventsDataManager;
    TFNTwitterAccount *_account;
    NSPointerArray *_capsuleListeners;
}

@property(retain, nonatomic) NSPointerArray *capsuleListeners; // @synthesize capsuleListeners=_capsuleListeners;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(readonly, nonatomic) id <TFNTwitterMomentSportEventsDataManager> sportEventsDataManager; // @synthesize sportEventsDataManager=_sportEventsDataManager;
@property(retain, nonatomic) NSArray *pivotList; // @synthesize pivotList=_pivotList;
@property(retain, nonatomic) TFNTwitterMomentCapsule *capsule; // @synthesize capsule=_capsule;
- (void).cxx_destruct;
- (void)removeCapsuleListener:(id)arg1;
- (void)addCapsuleListener:(id)arg1;
- (void)addDependentCapsuleChange:(id)arg1;
- (void)syncCapsuleChanges:(id)arg1 responseBlock:(CDUnknownBlockType)arg2;
- (void)fetchCapsulePivotList;
- (void)updateMomentLikeStatus:(_Bool)arg1 withCount:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)updateMomentSubscription;
- (void)hydrateMomentCapsule;
- (void)fetchCapsule;
- (id)initWithCapsule:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

