//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface TFNTwitterNumberAbbreviation : NSObject
{
}

+ (id)abbreviationForLanguage:(id)arg1;
+ (id)abbreviatedStringForNumber:(id)arg1 language:(id)arg2;
+ (void)initialize;

@end

