//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <T1Twitter/TFNPickableValue-Protocol.h>

@class NSArray, NSString, UIImage;

@interface TFNTwitterSULCategory : NSObject <TFNPickableValue>
{
    _Bool _isLoadingUsers;
    NSArray *_users;
    NSString *_slug;
    NSString *_name;
    long long _sulID;
}

+ (id)categoryWithJSONData:(id)arg1 error:(id *)arg2;
+ (id)categoriesWithJSONData:(id)arg1 error:(id *)arg2;
@property(nonatomic) _Bool isLoadingUsers; // @synthesize isLoadingUsers=_isLoadingUsers;
@property(nonatomic) long long sulID; // @synthesize sulID=_sulID;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *slug; // @synthesize slug=_slug;
@property(copy, nonatomic) NSArray *users; // @synthesize users=_users;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *valueName;
- (id)initWithJSONDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy, nonatomic) NSString *valueDetail;
@property(readonly, nonatomic) UIImage *valueIcon;
@property(readonly, copy, nonatomic) NSString *valueShortName;

@end

