//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSNumber, NSString, TFNTwitterUser, TFSTwitterUserReference;

@interface TFNTwitterFollowRequest : NSObject
{
    _Bool _isEarned;
    _Bool _supportsChallenges;
    _Bool _challengesCompleted;
    NSString *_impressionID;
    unsigned long long _requestType;
    CDUnknownBlockType _responseBlock;
    TFNTwitterUser *_user;
    TFSTwitterUserReference *_userReference;
}

@property(readonly, nonatomic) TFSTwitterUserReference *userReference; // @synthesize userReference=_userReference;
@property(readonly, nonatomic) TFNTwitterUser *user; // @synthesize user=_user;
@property(readonly, copy, nonatomic) CDUnknownBlockType responseBlock; // @synthesize responseBlock=_responseBlock;
@property(nonatomic) _Bool challengesCompleted; // @synthesize challengesCompleted=_challengesCompleted;
@property(readonly, nonatomic) _Bool supportsChallenges; // @synthesize supportsChallenges=_supportsChallenges;
@property(readonly, nonatomic) unsigned long long requestType; // @synthesize requestType=_requestType;
@property(readonly, nonatomic) _Bool isEarned; // @synthesize isEarned=_isEarned;
@property(readonly, copy, nonatomic) NSString *impressionID; // @synthesize impressionID=_impressionID;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *displayFullName;
@property(readonly, copy, nonatomic) NSString *username;
@property(readonly, nonatomic) NSNumber *userIDNumber;
@property(readonly, nonatomic) long long userID;
- (id)initWithUser:(id)arg1 orUserReference:(id)arg2 requestType:(unsigned long long)arg3 impressionID:(id)arg4 isEarned:(_Bool)arg5 supportsChallenges:(_Bool)arg6 responseBlock:(CDUnknownBlockType)arg7;
- (id)initWithUserReference:(id)arg1 requestType:(unsigned long long)arg2 impressionID:(id)arg3 isEarned:(_Bool)arg4 supportsChallenges:(_Bool)arg5 responseBlock:(CDUnknownBlockType)arg6;
- (id)initWithUser:(id)arg1 requestType:(unsigned long long)arg2 impressionID:(id)arg3 isEarned:(_Bool)arg4 supportsChallenges:(_Bool)arg5 responseBlock:(CDUnknownBlockType)arg6;

@end

