//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <T1Twitter/TFNTwitterCardContextModel-Protocol.h>

@class NSString;

@interface TFNTwitterCardDataPlayerStreamModel : NSObject <TFNTwitterCardContextModel>
{
    _Bool _isAmplify;
    NSString *_mimeType;
    NSString *_URLString;
    NSString *_contentType;
    struct CGSize _dimensionsOrAspectRatio;
}

+ (struct CGSize)playerDimensionsOrAspectRatioForCardData:(id)arg1;
@property(readonly, nonatomic) _Bool isAmplify; // @synthesize isAmplify=_isAmplify;
@property(readonly, nonatomic) struct CGSize dimensionsOrAspectRatio; // @synthesize dimensionsOrAspectRatio=_dimensionsOrAspectRatio;
@property(readonly, copy, nonatomic) NSString *contentType; // @synthesize contentType=_contentType;
@property(readonly, copy, nonatomic) NSString *URLString; // @synthesize URLString=_URLString;
- (void).cxx_destruct;
- (_Bool)_isPlayableContentType:(id)arg1;
- (_Bool)_isPlayableMimeType:(id)arg1;
@property(readonly, copy, nonatomic) NSString *mimeType; // @synthesize mimeType=_mimeType;
- (_Bool)isAudio;
- (_Bool)canPlayStreamInline;
- (id)initWithCardContext:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

