//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNTwitterAVAutoplayPlayerController.h>

#import <T1Twitter/TFNTwitterAVScribeAutoplayPlayerDelegate-Protocol.h>

@class NSMutableArray, NSString, TFNTwitterAVConfiguration, TFNTwitterAmplifyAVPlayer;

@interface TFNTwitterAmplifyPlayer : TFNTwitterAVAutoplayPlayerController <TFNTwitterAVScribeAutoplayPlayerDelegate>
{
    _Bool _attemptingToForcePlayback;
    _Bool _didExternalPause;
    _Bool _didPlayAd;
    _Bool _didScribeShow;
    _Bool _didSeekToInitialContentStartTime;
    _Bool _isReplay;
    _Bool _shouldSkipContent;
    NSMutableArray *_videosToPlay;
    long long _cachedVideoType;
    double _initialContentStartTime;
    id _adObserver;
    struct CGSize _contentSize;
}

@property(nonatomic) struct CGSize contentSize; // @synthesize contentSize=_contentSize;
@property(retain, nonatomic) id adObserver; // @synthesize adObserver=_adObserver;
@property(nonatomic) _Bool shouldSkipContent; // @synthesize shouldSkipContent=_shouldSkipContent;
@property(nonatomic) _Bool isReplay; // @synthesize isReplay=_isReplay;
@property(nonatomic) double initialContentStartTime; // @synthesize initialContentStartTime=_initialContentStartTime;
@property(nonatomic) _Bool didSeekToInitialContentStartTime; // @synthesize didSeekToInitialContentStartTime=_didSeekToInitialContentStartTime;
@property(nonatomic) _Bool didScribeShow; // @synthesize didScribeShow=_didScribeShow;
@property(nonatomic) _Bool didPlayAd; // @synthesize didPlayAd=_didPlayAd;
@property(nonatomic) _Bool didExternalPause; // @synthesize didExternalPause=_didExternalPause;
@property(nonatomic) long long cachedVideoType; // @synthesize cachedVideoType=_cachedVideoType;
@property(nonatomic) _Bool attemptingToForcePlayback; // @synthesize attemptingToForcePlayback=_attemptingToForcePlayback;
@property(retain, nonatomic) NSMutableArray *videosToPlay; // @synthesize videosToPlay=_videosToPlay;
- (void).cxx_destruct;
- (void)_stopPeriscopeLifecycle;
- (void)_startPeriscopeLifecycle;
- (void)_periscopeActionOccured:(id)arg1;
- (long long)_promotedEventForScribeAction:(id)arg1;
- (void)_logPromotedEvent:(long long)arg1 withVideo:(id)arg2 parameters:(id)arg3;
- (void)logPromotedEventIfNeeded:(long long)arg1 withVideo:(id)arg2 parameters:(id)arg3;
- (void)_sendVMAPBeaconForScribeAction:(id)arg1;
- (void)_scribeAction:(id)arg1 withPage:(id)arg2 section:(id)arg3 component:(id)arg4 element:(id)arg5 parameters:(id)arg6;
- (void)scribeAction:(id)arg1 withElement:(id)arg2 parameters:(id)arg3;
- (void)scribeAction:(id)arg1;
- (void)performDispose;
- (void)avScribeAutoplayPlayerDidUpdatePlaybackLikelyToKeepUp:(id)arg1 playbackLikelyToKeepUp:(_Bool)arg2;
- (void)avScribeAutoplayPlayerDidUpdateItemStatus:(id)arg1 itemStatus:(long long)arg2;
- (void)avScribeAutoplayPlayerDidReceiveTimedMetadata:(id)arg1 timedMetadata:(id)arg2;
- (double)visibilityPercentageForAVScribeAutoplayPlayer:(id)arg1;
- (double)viewThresholdForAVScribeAutoplayPlayer:(id)arg1;
- (_Bool)shouldSendTapEventForAVScribeAutoplayPlayer:(id)arg1;
- (_Bool)isPlayerObscuredByOverlappingViewForAVScribeAutoplayPlayer:(id)arg1;
- (_Bool)shouldIncrementVideoViewPlaybackTimeForAVScribeAutoplayPlayer:(id)arg1 forVisibilityThreshold:(double)arg2;
- (void)avScribePlayer:(id)arg1 scribePromotedEvent:(long long)arg2 parameters:(id)arg3;
- (void)avScribePlayer:(id)arg1 scribeAction:(id)arg2 page:(id)arg3 section:(id)arg4 component:(id)arg5 element:(id)arg6 withCurrentPlaybackTime:(double)arg7 parameters:(id)arg8;
- (void)avPlayerDidStall:(id)arg1;
- (void)avPlayerDidRecoverFromStall:(id)arg1;
- (void)_loopContentVideo;
- (_Bool)_shouldLoopContentVideo;
- (void)_allVideosPlaybackDidFinish;
- (void)_playNextVideo;
- (_Bool)skipAd;
- (void)avPlayerDidFinishPlayback:(id)arg1;
- (void)avPlayer:(id)arg1 playbackTimeDidProgress:(double)arg2 withIncrement:(double)arg3;
- (void)avPlayer:(id)arg1 didError:(id)arg2 withMessage:(id)arg3;
- (long long)type;
- (void)setDelegate:(id)arg1;
- (void)replay;
- (void)_resumePlayback;
- (void)performPlay;
- (void)performPause;
- (void)_didFailToLoadPlaylistWithError:(id)arg1;
- (void)_avPlayerRequestDidCompleteWithAVPlayer:(id)arg1 video:(id)arg2 completionHandler:(CDUnknownBlockType)arg3 error:(id)arg4;
- (void)_setupAVPlayerWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)_setupVideosToPlay;
- (void)_didFinishLoadingPlaylist;
- (void)performPrepareForPlayback;
@property(readonly, nonatomic) _Bool shouldSkipAd;
- (_Bool)hasUnplayedAds;
- (void)setCurrentAVPlayer:(id)arg1;
@property(readonly, nonatomic) TFNTwitterAVConfiguration *avConfiguration;
@property(readonly, nonatomic) _Bool allowDynamicAd;
- (void)_removeNotificationObservers;
- (id)initWithSession:(id)arg1 account:(id)arg2 configuration:(id)arg3;

// Remaining properties
@property(readonly, nonatomic) TFNTwitterAmplifyAVPlayer *currentAVPlayer; // @dynamic currentAVPlayer;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) _Bool didCompletePreparingForPlayback; // @dynamic didCompletePreparingForPlayback;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool playbackDidComplete; // @dynamic playbackDidComplete;
@property(readonly) Class superclass;

@end

