//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNTwitterBaseTwitterRecurringTask.h>

@interface TFNTwitterHeartbeatScribeRecurringTask : TFNTwitterBaseTwitterRecurringTask
{
}

- (void)tfs_triggerFromService:(id)arg1 event:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)tfs_priorityForEvent:(id)arg1 complete:(CDUnknownBlockType)arg2;

@end

