//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNTwitterAVPlayerControllerSession.h>

@interface TFNTwitterAmplifyPlayerMediaEntitySession : TFNTwitterAVPlayerControllerSession
{
}

- (id)initWithMediaEntity:(id)arg1 avConfiguration:(id)arg2;
- (id)initWithSource:(id)arg1 avConfiguration:(id)arg2;
- (id)initWithMediaEntity:(id)arg1 videoInfo:(id)arg2 ownerId:(id)arg3 avConfiguration:(id)arg4;
- (id)init;

@end

