//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNTwitterHighlightsWithHeaderStory.h>

@class NSArray, NSString;

@interface TFNTwitterHighlightsTopicStory : TFNTwitterHighlightsWithHeaderStory
{
    NSString *_hashtag;
    NSString *_desc;
    NSArray *_statuses;
    NSArray *_sharedByUsers;
}

@property(readonly, copy, nonatomic) NSArray *sharedByUsers; // @synthesize sharedByUsers=_sharedByUsers;
@property(readonly, copy, nonatomic) NSArray *statuses; // @synthesize statuses=_statuses;
@property(readonly, copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(readonly, copy, nonatomic) NSString *hashtag; // @synthesize hashtag=_hashtag;
- (void).cxx_destruct;
- (id)storyType;
- (id)highlightsStoryByReplacingTweets:(id)arg1 usersDictionary:(id)arg2;
@property(readonly, copy, nonatomic) NSString *showMoreURLString;
- (id)initWithStoryID:(id)arg1 hashtag:(id)arg2 title:(id)arg3 desc:(id)arg4 headerImageURLString:(id)arg5 headerImageOriginalDimensions:(struct CGSize)arg6 statuses:(id)arg7 sharedByUsers:(id)arg8;
- (id)initWithJSONDictionary:(id)arg1 usersDictionary:(id)arg2 tweetsDictionary:(id)arg3;

@end

