//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNTwitterAVScribePlayerDelegate-Protocol.h>

@class NSArray, TFNTwitterAVScribeAutoplayPlayer;

@protocol TFNTwitterAVScribeAutoplayPlayerDelegate <TFNTwitterAVScribePlayerDelegate>
- (double)visibilityPercentageForAVScribeAutoplayPlayer:(TFNTwitterAVScribeAutoplayPlayer *)arg1;
- (double)viewThresholdForAVScribeAutoplayPlayer:(TFNTwitterAVScribeAutoplayPlayer *)arg1;
- (_Bool)shouldSendTapEventForAVScribeAutoplayPlayer:(TFNTwitterAVScribeAutoplayPlayer *)arg1;
- (_Bool)isPlayerObscuredByOverlappingViewForAVScribeAutoplayPlayer:(TFNTwitterAVScribeAutoplayPlayer *)arg1;
- (_Bool)shouldIncrementVideoViewPlaybackTimeForAVScribeAutoplayPlayer:(TFNTwitterAVScribeAutoplayPlayer *)arg1 forVisibilityThreshold:(double)arg2;

@optional
- (void)avScribeAutoplayPlayerDidUpdatePlaybackLikelyToKeepUp:(TFNTwitterAVScribeAutoplayPlayer *)arg1 playbackLikelyToKeepUp:(_Bool)arg2;
- (void)avScribeAutoplayPlayerDidUpdateItemStatus:(TFNTwitterAVScribeAutoplayPlayer *)arg1 itemStatus:(long long)arg2;
- (void)avScribeAutoplayPlayerDidReceiveTimedMetadata:(TFNTwitterAVScribeAutoplayPlayer *)arg1 timedMetadata:(NSArray *)arg2;
@end

