//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <T1Twitter/TFNTwitterUserMomentListFetcher-Protocol.h>

@class NSString, TFNTwitterAccount;

@interface TFNTwitterAPICameraMomentUserMomentListFetcher : NSObject <TFNTwitterUserMomentListFetcher>
{
    TFNTwitterAccount *_account;
}

@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)fetchMomentsForUser:(id)arg1 withCount:(long long)arg2 scrollCursor:(id)arg3 includesPremadeMoments:(_Bool)arg4 responseBlock:(CDUnknownBlockType)arg5;
- (id)initWithAccount:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

