//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSArray, NSDate, NSString, TFSTwitterLiveAuthorizedStreamStatus;

@protocol TFNTwitterWatchBroadcastModel <NSObject>
@property(readonly, copy, nonatomic) NSString *broadcasterDisplayUsername;
@property(readonly, copy, nonatomic) NSString *chatToken;
@property(readonly, copy, nonatomic) NSString *lifecycleToken;
@property(readonly, nonatomic) _Bool isReturningFromFullscreen;
@property(readonly, nonatomic, getter=isUnavailableInPeriscope) _Bool unavailableInPeriscope;
@property(readonly, nonatomic) struct CLLocationCoordinate2D broadcasterCoordinate;
@property(readonly, copy, nonatomic) NSString *countryStateName;
@property(readonly, copy, nonatomic) NSString *countryName;
@property(readonly, copy, nonatomic) NSString *cityName;
@property(readonly, nonatomic) _Bool hasLocation;
@property(readonly, copy, nonatomic) NSString *broadcasterTwitterUsername;
@property(readonly, copy, nonatomic) NSString *broadcasterTwitterUserID;
@property(readonly, copy, nonatomic) NSString *broadcasterProfileImageURL;
@property(readonly, copy, nonatomic) NSString *broadcasterDisplayName;
@property(readonly, copy, nonatomic) NSString *broadcasterUsername;
@property(readonly, copy, nonatomic) NSString *broadcasterUserID;
@property(readonly, copy, nonatomic) NSArray *heartThemes;
@property(readonly, nonatomic, getter=isHighLatency) _Bool highLatency;
@property(readonly, nonatomic, getter=isPrivateChat) _Bool privateChat;
@property(readonly, nonatomic) _Bool requiresFineGrainGeoblocking;
@property(readonly, nonatomic) double startTimecode;
@property(readonly, copy, nonatomic) NSString *tweetID;
@property(readonly, copy, nonatomic) NSString *broadcastSource;
@property(readonly, nonatomic, getter=isAvailableForReplay) _Bool availableForReplay;
@property(readonly, nonatomic) unsigned long long cameraRotation;
@property(readonly, nonatomic) unsigned long long height;
@property(readonly, nonatomic) unsigned long long width;
@property(readonly, copy, nonatomic) NSString *title;
@property(readonly, copy, nonatomic) NSString *imageURLSmall;
@property(readonly, copy, nonatomic) NSString *imageURL;
@property(readonly, copy, nonatomic) NSDate *timedoutDate;
@property(readonly, copy, nonatomic) NSDate *endDate;
@property(readonly, copy, nonatomic) NSDate *pingDate;
@property(readonly, copy, nonatomic) NSDate *startDate;
@property(readonly, nonatomic) unsigned long long state;
@property(readonly, copy, nonatomic) NSString *stateString;
@property(readonly, copy, nonatomic) NSString *totalWatched;
@property(readonly, copy, nonatomic) NSString *totalWatching;
@property(readonly, nonatomic) _Bool acceptsGifts;
@property(readonly, nonatomic, getter=isThreeSixty) _Bool threeSixty;
@property(readonly, copy, nonatomic) NSString *mediaID;
@property(readonly, copy, nonatomic) NSString *mediaKey;
@property(readonly, copy, nonatomic) NSString *broadcastID;
- (void)hydrateStreamStatus:(TFSTwitterLiveAuthorizedStreamStatus *)arg1;
@end

