//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary, TFNTwitterCumulativeHistogram, TFNTwitterViewDisplaySession;

@interface TFNTwitterVideoDisplaySession : NSObject
{
    TFNTwitterCumulativeHistogram *_cumulativePlaybackTimeWithAudioByVisibilityPercentage;
    TFNTwitterCumulativeHistogram *_maxContinuousPlaybackTimeWithAudioByVisibilityPercentage;
    TFNTwitterViewDisplaySession *_displaySession;
    TFNTwitterCumulativeHistogram *_currentContinuousPlaybackTimeWithAudioByVisibilityPercentage;
}

@property(retain, nonatomic) TFNTwitterCumulativeHistogram *currentContinuousPlaybackTimeWithAudioByVisibilityPercentage; // @synthesize currentContinuousPlaybackTimeWithAudioByVisibilityPercentage=_currentContinuousPlaybackTimeWithAudioByVisibilityPercentage;
@property(retain, nonatomic) TFNTwitterViewDisplaySession *displaySession; // @synthesize displaySession=_displaySession;
@property(retain, nonatomic) TFNTwitterCumulativeHistogram *maxContinuousPlaybackTimeWithAudioByVisibilityPercentage; // @synthesize maxContinuousPlaybackTimeWithAudioByVisibilityPercentage=_maxContinuousPlaybackTimeWithAudioByVisibilityPercentage;
@property(retain, nonatomic) TFNTwitterCumulativeHistogram *cumulativePlaybackTimeWithAudioByVisibilityPercentage; // @synthesize cumulativePlaybackTimeWithAudioByVisibilityPercentage=_cumulativePlaybackTimeWithAudioByVisibilityPercentage;
- (void).cxx_destruct;
- (void)_tfn_setupOrResetContinuousHistograms;
@property(readonly, nonatomic) NSDictionary *sizesInfoAtTheStart;
@property(readonly, nonatomic) TFNTwitterCumulativeHistogram *maxContinuousPlaybackTimeByVisibilityPercentage;
@property(readonly, nonatomic) TFNTwitterCumulativeHistogram *cumulativePlaybackTimeByViewportPercentage;
@property(readonly, nonatomic) TFNTwitterCumulativeHistogram *cumulativePlaybackTimeByVisibilityPercentage;
- (void)updateVideoSessionWithVisiblityPercentage:(double)arg1 continuousInterval:(double)arg2 videoMuted:(_Bool)arg3 videoViewSize:(struct CGSize)arg4 viewportSize:(struct CGSize)arg5;
- (id)initWithVideoSize:(struct CGSize)arg1 viewportSize:(struct CGSize)arg2 screenScale:(double)arg3;

@end

