//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFSUtilities/TFSDependentConcurrentOperation.h>

#import <T1Twitter/TFNTwitterCompositionUploadAttachmentsOperationDelegate-Protocol.h>
#import <T1Twitter/TFNTwitterCompositionUploadPollOperationDelegate-Protocol.h>
#import <T1Twitter/TFSOperationDependencyResult-Protocol.h>

@class NSError, NSHashTable, NSObject, NSOperationQueue, NSString, TFNTwitterAccount, TFNTwitterComposition, TFNTwitterCompositionUpdateStatusOperation, TFNTwitterCompositionUploadContext, TFNTwitterStatus;
@protocol OS_dispatch_queue, TFNTwitterCompositionUploadOperationDelegate;

@interface TFNTwitterCompositionUploadOperation : TFSDependentConcurrentOperation <TFNTwitterCompositionUploadAttachmentsOperationDelegate, TFNTwitterCompositionUploadPollOperationDelegate, TFSOperationDependencyResult>
{
    unsigned long long _resultState;
    NSError *_error;
    id <TFNTwitterCompositionUploadOperationDelegate> _delegate;
    TFNTwitterStatus *_resultStatus;
    TFNTwitterComposition *_composition;
    TFNTwitterAccount *_account;
    TFNTwitterCompositionUploadContext *_context;
    NSOperationQueue *_queue;
    NSHashTable *_weakOperationsToCancel;
    NSObject<OS_dispatch_queue> *_backgroundIdentifierQueue;
    unsigned long long _backgroundIdentifier;
    TFNTwitterCompositionUpdateStatusOperation *_updateStatusOperation;
}

@property(nonatomic) __weak TFNTwitterCompositionUpdateStatusOperation *updateStatusOperation; // @synthesize updateStatusOperation=_updateStatusOperation;
@property(nonatomic) unsigned long long backgroundIdentifier; // @synthesize backgroundIdentifier=_backgroundIdentifier;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *backgroundIdentifierQueue; // @synthesize backgroundIdentifierQueue=_backgroundIdentifierQueue;
@property(retain, nonatomic) NSHashTable *weakOperationsToCancel; // @synthesize weakOperationsToCancel=_weakOperationsToCancel;
@property(readonly, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) TFNTwitterCompositionUploadContext *context; // @synthesize context=_context;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(readonly, nonatomic) TFNTwitterComposition *composition; // @synthesize composition=_composition;
@property(retain) TFNTwitterStatus *resultStatus; // @synthesize resultStatus=_resultStatus;
@property(nonatomic) __weak id <TFNTwitterCompositionUploadOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain) NSError *resultError; // @synthesize resultError=_error;
@property unsigned long long resultState; // @synthesize resultState=_resultState;
- (void).cxx_destruct;
- (void)compositionUploadPollOperation:(id)arg1 didUploadPoll:(id)arg2;
- (void)compositionUploadAttachmentsOperation:(id)arg1 didUploadAttachment:(id)arg2;
- (id)_tfn_background_completeOperationOperation;
- (void)_tfn_background_updateResultState;
- (id)_tfn_background_updateResultStateOperation;
- (void)_tfn_main_enqueueOperations;
- (void)_tfn_main_initializeContext;
- (void)_tfn_main_run;
- (void)_tfn_background_endBackgroundTask;
- (void)_tfn_background_beginBackgroundTask;
- (void)completeOperation;
- (void)cancel;
- (void)run;
- (id)initWithComposition:(id)arg1 account:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

