//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNTwitterMediaAsset.h>

#import <T1Twitter/NSCoding-Protocol.h>

@class NSMutableArray, NSURL, TFNTwitterVideoSegmentManager, UIImage;

@interface TFNTwitterMediaAssetVideoCapture : TFNTwitterMediaAsset <NSCoding>
{
    TFNTwitterVideoSegmentManager *_segmentManager;
    double _duration;
    UIImage *_cachedPreview;
    NSMutableArray *_exportHandlers;
    long long _exportState;
    NSURL *_exportURL;
    NSMutableArray *_previewHandlers;
    long long _previewState;
    long long _saveState;
}

@property(nonatomic) long long saveState; // @synthesize saveState=_saveState;
@property(nonatomic) long long previewState; // @synthesize previewState=_previewState;
@property(readonly, nonatomic) NSMutableArray *previewHandlers; // @synthesize previewHandlers=_previewHandlers;
@property(retain, nonatomic) NSURL *exportURL; // @synthesize exportURL=_exportURL;
@property(nonatomic) long long exportState; // @synthesize exportState=_exportState;
@property(readonly, nonatomic) NSMutableArray *exportHandlers; // @synthesize exportHandlers=_exportHandlers;
@property(retain, nonatomic) UIImage *cachedPreview; // @synthesize cachedPreview=_cachedPreview;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(readonly, nonatomic) TFNTwitterVideoSegmentManager *segmentManager; // @synthesize segmentManager=_segmentManager;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)_saveToLibraryIfNecessary:(id)arg1;
- (void)_exportSegmentedCompositionWithCompletion:(CDUnknownBlockType)arg1;
- (void)renderAvAssetWithOptions:(id)arg1 progressHandler:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)renderFinalDataWithProgressHandler:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (id)deprecatedPreview;
- (void)_didUpdatePreview:(id)arg1;
- (void)_generatePreview:(CDUnknownBlockType)arg1;
- (void)renderPreviewWithProgressHandler:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (struct CGSize)estimatedPreviewSizeThatFits:(struct CGSize)arg1;
- (unsigned long long)attachmentType;
- (long long)mediaType;
- (struct CGSize)assetDimensions;
- (void)encodeWithCoder:(id)arg1;
- (void)_twitterMediaAssetVideoCaptureInitializer;
- (id)initWithCoder:(id)arg1;
- (id)initWithSegmentManager:(id)arg1;

@end

