//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSDictionary, TFNTwitterAccount, TFNTwitterStatus;

@interface TFNTwitterTweetDetailsActionView : UIView
{
    struct CGRect _previousButtonBounds;
    _Bool _disabled;
    _Bool _usesBirthdayAnimation;
    _Bool _hidesDisabledActions;
    _Bool _needsUpdateButtons;
    _Bool _haveSetInitialStates;
    long long _style;
    TFNTwitterStatus *_status;
    TFNTwitterAccount *_account;
    NSArray *_layoutOrder;
    NSDictionary *_actions;
}

+ (struct UIEdgeInsets)_touchInsetsForActionButtonFrame:(struct CGRect)arg1 bounds:(struct CGRect)arg2;
@property(nonatomic) _Bool haveSetInitialStates; // @synthesize haveSetInitialStates=_haveSetInitialStates;
@property(retain, nonatomic) NSDictionary *actions; // @synthesize actions=_actions;
@property(nonatomic) _Bool needsUpdateButtons; // @synthesize needsUpdateButtons=_needsUpdateButtons;
@property(copy, nonatomic) NSArray *layoutOrder; // @synthesize layoutOrder=_layoutOrder;
@property(nonatomic) _Bool hidesDisabledActions; // @synthesize hidesDisabledActions=_hidesDisabledActions;
@property(nonatomic) _Bool usesBirthdayAnimation; // @synthesize usesBirthdayAnimation=_usesBirthdayAnimation;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(retain, nonatomic) TFNTwitterStatus *status; // @synthesize status=_status;
@property(readonly, nonatomic) long long style; // @synthesize style=_style;
- (void).cxx_destruct;
- (id)_animationForButton:(id)arg1;
- (void)_updateAnimatorForButton:(id)arg1;
- (void)_updateButtonAnimators;
- (void)_buttonWasTapped:(id)arg1;
- (id)calculatedLayoutMetrics;
- (void)_momentsLayoutForBounds:(struct CGRect)arg1;
- (void)_equalSpaceLayoutForBounds:(struct CGRect)arg1;
- (void)_equalDistanceLayoutForBounds:(struct CGRect)arg1;
- (void)_centerSingleButtonLayoutForBounds:(struct CGRect)arg1;
- (void)_legacyLayoutForBounds:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)_updateAccessibilityForButton:(id)arg1 selected:(_Bool)arg2 selectedHint:(id)arg3 unselectedHint:(id)arg4;
- (void)_updateButton:(id)arg1 selected:(_Bool)arg2 count:(long long)arg3 unselectedHint:(id)arg4 selectedHint:(id)arg5;
- (void)_updateButtonStates;
- (void)updateButtonsIfNeeded;
- (void)setNeedsUpdateButtons;
- (id)buttonOfType:(unsigned long long)arg1;
- (id)_createButtonOfType:(unsigned long long)arg1;
@property(nonatomic, getter=isEnabled) _Bool enabled;
- (void)setReplyBlock:(CDUnknownBlockType)arg1 retweetBlock:(CDUnknownBlockType)arg2 favoriteBlock:(CDUnknownBlockType)arg3 dmTweetBlock:(CDUnknownBlockType)arg4 shareTweetBlock:(CDUnknownBlockType)arg5 moreBlock:(CDUnknownBlockType)arg6 forStatus:(id)arg7 account:(id)arg8;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

