//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

@class NSString, TFNTwitterUser, TFNTwitterUserDataSource;

@interface TFNTwitterBannerImageView : UIImageView
{
    NSString *_accountID;
    TFNTwitterUser *_user;
    TFNTwitterUserDataSource *_userDataSource;
}

@property(retain, nonatomic) TFNTwitterUserDataSource *userDataSource; // @synthesize userDataSource=_userDataSource;
@property(retain, nonatomic) TFNTwitterUser *user; // @synthesize user=_user;
@property(copy, nonatomic) NSString *accountID; // @synthesize accountID=_accountID;
- (void).cxx_destruct;
- (void)resetUsers;
- (void)_commonInitTFNTwitterBannerImageView;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

