//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSDictionary, TFNTwitterPushNotificationPayload;

@protocol TFNTwitterPushNotificationRoute <NSObject>
- (NSDictionary *)ephemeralStateForPushPayload:(TFNTwitterPushNotificationPayload *)arg1 context:(long long)arg2;
- (void)ambientNotificationForPayload:(TFNTwitterPushNotificationPayload *)arg1 completionBlock:(void (^)(TFNTwitterAmbientNotification *))arg2;
- (void)handlePushPayload:(TFNTwitterPushNotificationPayload *)arg1 context:(long long)arg2;
- (void)willRoutePushPayload:(TFNTwitterPushNotificationPayload *)arg1 context:(long long)arg2;
@end

