//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray;

@interface TFNTwitterAVPlayerControllerVideoScribeState : NSObject
{
    _Bool _loggedShow;
    NSMutableArray *_tentpoles;
}

@property(retain, nonatomic) NSMutableArray *tentpoles; // @synthesize tentpoles=_tentpoles;
@property(nonatomic) _Bool loggedShow; // @synthesize loggedShow=_loggedShow;
- (void).cxx_destruct;

@end

