//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, TFNTwitterUser;

@interface TFNTwitterAccountCreateResponse : NSObject
{
    TFNTwitterUser *_user;
    NSString *_OAuthToken;
    NSString *_OAuthTokenSecret;
    NSString *_knownDeviceToken;
}

@property(readonly, nonatomic) NSString *knownDeviceToken; // @synthesize knownDeviceToken=_knownDeviceToken;
@property(readonly, nonatomic) NSString *OAuthTokenSecret; // @synthesize OAuthTokenSecret=_OAuthTokenSecret;
@property(readonly, nonatomic) NSString *OAuthToken; // @synthesize OAuthToken=_OAuthToken;
@property(readonly, nonatomic) TFNTwitterUser *user; // @synthesize user=_user;
- (void).cxx_destruct;
- (id)initWithUser:(id)arg1 OAuthToken:(id)arg2 OAuthTokenSecret:(id)arg3 knownDeviceToken:(id)arg4;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

