//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <T1Twitter/TFSPlistSerialization-Protocol.h>
#import <T1Twitter/TFSTwitterScribableItem-Protocol.h>

@class NSDictionary, NSString, TFNTwitterMomentCapsule, TFNTwitterMomentLinkTitleCard, TFNTwitterMomentMedia, TFNTwitterMomentPageSocialProof, TFNTwitterMomentRender, TFNTwitterStatus, TFSTwitterTextRange;

@interface TFNTwitterMomentPage : NSObject <TFSTwitterScribableItem, TFSPlistSerialization>
{
    _Bool _isPromoted;
    _Bool _newsCameraModeEnabled;
    long long _type;
    NSString *_pageID;
    NSString *_statusID;
    TFNTwitterStatus *_status;
    TFNTwitterMomentRender *_render;
    TFNTwitterMomentMedia *_media;
    TFNTwitterMomentLinkTitleCard *_linkTitleCard;
    TFSTwitterTextRange *_truncationRange;
    TFNTwitterMomentCapsule *_attachedMomentCapsule;
    TFNTwitterMomentPageSocialProof *_socialProof;
}

+ (long long)_t1_pageTypeForString:(id)arg1;
+ (id)hydratedMomentPageFromDehydratedMomentPage:(id)arg1 statusDictionary:(id)arg2;
+ (id)momentPageWithJSONData:(id)arg1 statusDictionary:(id)arg2;
@property(nonatomic, getter=isNewsCameraModeEnabled) _Bool newsCameraModeEnabled; // @synthesize newsCameraModeEnabled=_newsCameraModeEnabled;
@property(readonly, nonatomic) _Bool isPromoted; // @synthesize isPromoted=_isPromoted;
@property(readonly, nonatomic) TFNTwitterMomentPageSocialProof *socialProof; // @synthesize socialProof=_socialProof;
@property(readonly, nonatomic) TFNTwitterMomentCapsule *attachedMomentCapsule; // @synthesize attachedMomentCapsule=_attachedMomentCapsule;
@property(readonly, nonatomic) TFSTwitterTextRange *truncationRange; // @synthesize truncationRange=_truncationRange;
@property(readonly, nonatomic) TFNTwitterMomentLinkTitleCard *linkTitleCard; // @synthesize linkTitleCard=_linkTitleCard;
@property(readonly, nonatomic) TFNTwitterMomentMedia *media; // @synthesize media=_media;
@property(readonly, nonatomic) TFNTwitterMomentRender *render; // @synthesize render=_render;
@property(readonly, nonatomic) TFNTwitterStatus *status; // @synthesize status=_status;
@property(readonly, nonatomic) NSString *statusID; // @synthesize statusID=_statusID;
@property(readonly, nonatomic) NSString *pageID; // @synthesize pageID=_pageID;
@property(readonly, nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
@property(readonly, copy) NSString *description;
- (id)plistDictionaryValue;
- (id)initWithPlistDictionary:(id)arg1;
@property(readonly, copy, nonatomic) NSDictionary *scribeItem;
@property(readonly, copy, nonatomic) NSString *scribeItemImpressionID;
@property(readonly, nonatomic) struct CGSize mediaDimensions;
@property(readonly, copy, nonatomic) NSString *mediaURLString;
- (id)associatedMediaInfo;
- (void)populateWithStatus:(id)arg1;
- (id)momentPageWithTextType;
- (_Bool)isVisibleByAccount:(id)arg1;
@property(readonly, nonatomic) _Bool isPlayableLiveVideoEvent;
@property(readonly, nonatomic) _Bool isEmpty;
@property(readonly, nonatomic) _Bool isPlayableMedia;
@property(readonly, nonatomic) _Bool isNonMediaType;
@property(readonly, nonatomic) _Bool needsStatusHydration;
- (id)initWithMediaJSONDictionary:(id)arg1;
- (id)initWithMediaURL:(id)arg1 size:(struct CGSize)arg2;
- (id)initWithJSONDictionary:(id)arg1 statusDictionary:(id)arg2;
- (id)initWithStatus:(id)arg1;
- (id)initWithType:(long long)arg1 pageID:(id)arg2 status:(id)arg3 render:(id)arg4 media:(id)arg5 linkTitleCard:(id)arg6 truncationRange:(id)arg7 attachedMomentCapsule:(id)arg8 socialProof:(id)arg9 isPromoted:(_Bool)arg10;
- (id)initWithType:(long long)arg1 pageID:(id)arg2 statusID:(id)arg3 status:(id)arg4 render:(id)arg5 media:(id)arg6 linkTitleCard:(id)arg7 truncationRange:(id)arg8 attachedMomentCapsule:(id)arg9 socialProof:(id)arg10 isPromoted:(_Bool)arg11;
- (id)init;
- (id)makerMediaDataDictionaryPlistValueWithRender:(id)arg1 mediaDimensions:(struct CGSize)arg2;
- (id)makerMetadataPlistDictionaryValueWithRender:(id)arg1 mediaDimensions:(struct CGSize)arg2;
- (id)makerMetadataPlistDictionaryValue;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, nonatomic) unsigned long long isCurrentlyFirstImpression;
@property(readonly, nonatomic) unsigned long long isDuplicateContentIDInstance;
@property(readonly) Class superclass;

@end

