//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNTwitterConcreteStatusesStream.h>

@class TFNTwitterList;

@interface TFNTwitterListStream : TFNTwitterConcreteStatusesStream
{
    TFNTwitterList *_list;
}

@property(retain, nonatomic) TFNTwitterList *list; // @synthesize list=_list;
- (void).cxx_destruct;
- (void)protected_loadOlderWithSource:(long long)arg1;
- (void)_loadBeforeGap:(id)arg1 source:(long long)arg2;
- (void)protected_loadNewerWithSource:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (id)_maxCount;

@end

