//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <T1Twitter/TFNTwitterCardAPIManager-Protocol.h>

@class NSMutableDictionary, TFSTimer;
@protocol OS_dispatch_queue;

@interface TFNTwitterCardAPIManager : NSObject <TFNTwitterCardAPIManager>
{
    NSMutableDictionary *_ongoingCommands;
    NSObject<OS_dispatch_queue> *_backgroundQueue;
    NSMutableDictionary *_refreshRequests;
    NSMutableDictionary *_refreshObserverCount;
    TFSTimer *_timer;
    unsigned long long _elapsedTicks;
}

+ (id)sharedManager;
@property(nonatomic) unsigned long long elapsedTicks; // @synthesize elapsedTicks=_elapsedTicks;
@property(retain, nonatomic) TFSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) NSMutableDictionary *refreshObserverCount; // @synthesize refreshObserverCount=_refreshObserverCount;
@property(retain, nonatomic) NSMutableDictionary *refreshRequests; // @synthesize refreshRequests=_refreshRequests;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *backgroundQueue; // @synthesize backgroundQueue=_backgroundQueue;
@property(retain, nonatomic) NSMutableDictionary *ongoingCommands; // @synthesize ongoingCommands=_ongoingCommands;
- (void).cxx_destruct;
- (void)private_appWillEnterForeground:(id)arg1;
- (void)private_appDidEnterBackground:(id)arg1;
- (void)private_activeAccountDidChange:(id)arg1;
- (void)private_createAndScheduleTimerIfNil;
- (void)private_didReceiveResponseWithCardData:(id)arg1 error:(id)arg2 forCardIdentifier:(id)arg3;
- (id)private_dispatchPeriodicRequest:(id)arg1;
- (void)cancelCommandForID:(id)arg1;
- (_Bool)isCommandOngoing:(id)arg1;
- (void)addCommand:(id)arg1 withID:(id)arg2;
- (void)private_refreshRegisteredCards:(id)arg1;
- (id)private_sendRequestToCapiURL:(id)arg1 method:(long long)arg2 requestData:(id)arg3 account:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (id)fire;
- (void)unregisterForPeriodicReadsForCardIdentifier:(id)arg1;
- (void)registerForPeriodicReadsFromCapiURL:(id)arg1 atInterval:(double)arg2 requestData:(id)arg3 account:(id)arg4 forCardIdentifier:(id)arg5 fireImmediately:(_Bool)arg6;
- (void)private_cancelAllCommands;
- (void)dealloc;
- (id)init;

@end

