//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class TFNTabbedViewController, UIViewController;

@protocol TFNTabbedViewControllerDataSource <NSObject>
- (UIViewController *)tabbedViewController:(TFNTabbedViewController *)arg1 viewControllerAtIndex:(long long)arg2;
- (long long)numberOfViewControllersInTabbedViewController:(TFNTabbedViewController *)arg1;
@end

