//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSNumber, NSString;

@interface TFNTwitterVideoMonetizationCategory : NSObject
{
    NSString *_name;
    NSNumber *_categoryID;
    NSNumber *_parentCategoryID;
}

@property(readonly, nonatomic) NSNumber *parentCategoryID; // @synthesize parentCategoryID=_parentCategoryID;
@property(readonly, nonatomic) NSNumber *categoryID; // @synthesize categoryID=_categoryID;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)initWithCategoryName:(id)arg1 categoryID:(id)arg2 parentCategoryID:(id)arg3;
@property(nonatomic, readonly) NSString *valueName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

