//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIView;

@interface TFNVerticalLayoutSubviewRecord : NSObject
{
    UIView *_arrangedSubview;
    double _top;
    double _height;
    struct UIEdgeInsets _horizontalEdgeInsets;
}

@property(readonly, nonatomic) struct UIEdgeInsets horizontalEdgeInsets; // @synthesize horizontalEdgeInsets=_horizontalEdgeInsets;
@property(readonly, nonatomic) double height; // @synthesize height=_height;
@property(readonly, nonatomic) double top; // @synthesize top=_top;
@property(readonly, nonatomic) UIView *arrangedSubview; // @synthesize arrangedSubview=_arrangedSubview;
- (void).cxx_destruct;
- (id)initWithArrangedSubview:(id)arg1 top:(double)arg2 height:(double)arg3 horizontalEdgeInsets:(struct UIEdgeInsets)arg4;

@end

