//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TFSModelIdentifier : NSObject
{
    // Error parsing type: , name: uid
    // Error parsing type: , name: modelType
}

+ (id)cacheDiagnosticTypeNameFromStringValue:(id)arg1;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (_Bool)isEqual:(id)arg1;
@property(nonatomic, readonly) long long hashValue;
- (id)copyWithZone:(void *)arg1;
@property(nonatomic, readonly) NSString *description;
- (id)stringValue;

@end

