//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFSTwitterAPICommand/TFSTwitterAPICommand.h>

@class NSNumber, NSString, TFNTwitterAccountModel;

@interface TFSTwitterAPIUsersShowCommand : TFSTwitterAPICommand
{
    _Bool _useGraphQL;
    _Bool _representingUserForAssociatedAccount;
    NSNumber *_userID;
    NSString *_screenName;
    TFNTwitterAccountModel *_accountModel;
}

@property(nonatomic) _Bool representingUserForAssociatedAccount; // @synthesize representingUserForAssociatedAccount=_representingUserForAssociatedAccount;
@property(nonatomic) _Bool useGraphQL; // @synthesize useGraphQL=_useGraphQL;
@property(retain, nonatomic) TFNTwitterAccountModel *accountModel; // @synthesize accountModel=_accountModel;
@property(retain, nonatomic) NSString *screenName; // @synthesize screenName=_screenName;
@property(retain, nonatomic) NSNumber *userID; // @synthesize userID=_userID;
- (void).cxx_destruct;
- (void)processResponse:(id)arg1;
- (id)request;
- (id)initWithService:(id)arg1 accountID:(id)arg2 screenName:(id)arg3 accountModel:(id)arg4 representingUserForAssociatedAccount:(_Bool)arg5 useGraphQL:(_Bool)arg6 source:(unsigned long long)arg7 completionBlock:(CDUnknownBlockType)arg8;
- (id)initWithService:(id)arg1 accountID:(id)arg2 screenName:(id)arg3 accountModel:(id)arg4 useGraphQL:(_Bool)arg5 source:(unsigned long long)arg6 completionBlock:(CDUnknownBlockType)arg7;
- (id)initWithService:(id)arg1 accountID:(id)arg2 userID:(id)arg3 accountModel:(id)arg4 representingUserForAssociatedAccount:(_Bool)arg5 useGraphQL:(_Bool)arg6 source:(unsigned long long)arg7 completionBlock:(CDUnknownBlockType)arg8;
- (id)initWithService:(id)arg1 accountID:(id)arg2 userID:(id)arg3 accountModel:(id)arg4 useGraphQL:(_Bool)arg5 source:(unsigned long long)arg6 completionBlock:(CDUnknownBlockType)arg7;
- (id)initWithService:(id)arg1 accountID:(id)arg2 authContext:(id)arg3 networkTransactionMetrics:(id)arg4 source:(unsigned long long)arg5 completionBlock:(CDUnknownBlockType)arg6;

@end

