//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFSTwitterAPICommand/TFSTwitterAPICommand.h>

@class NSString, TFNAuthorizationRecord;

@interface TFSTwitterAPIAuthorizationStateUpdateCommand : TFSTwitterAPICommand
{
    long long _userID;
    NSString *_applicationID;
    TFNAuthorizationRecord *_authorizationRecord;
}

+ (id)private_authorizationStateForUserID:(id)arg1 deviceID:(id)arg2 applicationID:(id)arg3 record:(id)arg4;
+ (id)private_permissionStateForStatusString:(id)arg1;
+ (id)private_inAppPermissionStateForStatus:(long long)arg1;
+ (id)private_systemPermissionStateForStatus:(long long)arg1;
+ (id)private_permissionNameForServiceType:(long long)arg1;
- (void).cxx_destruct;
- (id)request;
- (id)initWithService:(id)arg1 accountID:(id)arg2 source:(unsigned long long)arg3 userID:(long long)arg4 applicationID:(id)arg5 authorizationRecord:(id)arg6 completionBlock:(CDUnknownBlockType)arg7;

@end

