//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFSTwitterAPICommand/TFSTwitterAPICommand.h>

@class NSArray, NSString;

@interface TFSTwitterAPIAmplifyMarketplaceVideosPostCommand : TFSTwitterAPICommand
{
    _Bool _monetize;
    NSString *_mediaID;
    NSArray *_videoCategories;
    NSArray *_advertiserBlacklist;
    NSArray *_categoryBlacklist;
}

@property(retain, nonatomic) NSArray *categoryBlacklist; // @synthesize categoryBlacklist=_categoryBlacklist;
@property(retain, nonatomic) NSArray *advertiserBlacklist; // @synthesize advertiserBlacklist=_advertiserBlacklist;
@property(retain, nonatomic) NSArray *videoCategories; // @synthesize videoCategories=_videoCategories;
@property(nonatomic) _Bool monetize; // @synthesize monetize=_monetize;
@property(retain, nonatomic) NSString *mediaID; // @synthesize mediaID=_mediaID;
- (void).cxx_destruct;
- (id)request;
- (id)initWithService:(id)arg1 accountID:(id)arg2 mediaID:(id)arg3 monetize:(_Bool)arg4 videoCategories:(id)arg5 advertiserBlacklist:(id)arg6 categoryBlacklist:(id)arg7 source:(unsigned long long)arg8 completionBlock:(CDUnknownBlockType)arg9;

@end

