//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFSTwitterAPIFollowSearchCommand.h>

#import <T1Twitter/TFSTwitterAPICommandQueueable-Protocol.h>

@class NSString;

@interface TFSTwitterAPIFollowSearchDestroyCommand : TFSTwitterAPIFollowSearchCommand <TFSTwitterAPICommandQueueable>
{
    NSString *_query;
}

@property(readonly, copy, nonatomic) NSString *query; // @synthesize query=_query;
- (void).cxx_destruct;
- (_Bool)isCounterCommandToCommand:(id)arg1;
- (id)request;
- (id)initWithService:(id)arg1 accountID:(id)arg2 query:(id)arg3 source:(unsigned long long)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)initWithService:(id)arg1 accountID:(id)arg2 authContext:(id)arg3 networkTransactionMetrics:(id)arg4 source:(unsigned long long)arg5 completionBlock:(CDUnknownBlockType)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

