//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFSTwitterAPICommand/TFSTwitterAPICommand.h>

@class NSNumber, NSString, TFNTwitterAccountModel;

@interface TFSTwitterAPITimelineUserCommand : TFSTwitterAPICommand
{
    _Bool _allowPromotedContent;
    _Bool _includeTweetReplies;
    _Bool _includeRetweets;
    _Bool _includeBlockingInfo;
    TFNTwitterAccountModel *_accountModel;
    NSNumber *_userID;
    NSString *_upCursor;
    NSString *_downCursor;
    NSNumber *_count;
    NSString *_lang;
    NSString *_referralSource;
    NSString *_requestContext;
}

@property(nonatomic) _Bool includeBlockingInfo; // @synthesize includeBlockingInfo=_includeBlockingInfo;
@property(nonatomic) _Bool includeRetweets; // @synthesize includeRetweets=_includeRetweets;
@property(nonatomic) _Bool includeTweetReplies; // @synthesize includeTweetReplies=_includeTweetReplies;
@property(nonatomic) _Bool allowPromotedContent; // @synthesize allowPromotedContent=_allowPromotedContent;
@property(retain, nonatomic) NSString *requestContext; // @synthesize requestContext=_requestContext;
@property(retain, nonatomic) NSString *referralSource; // @synthesize referralSource=_referralSource;
@property(retain, nonatomic) NSString *lang; // @synthesize lang=_lang;
@property(retain, nonatomic) NSNumber *count; // @synthesize count=_count;
@property(retain, nonatomic) NSString *downCursor; // @synthesize downCursor=_downCursor;
@property(retain, nonatomic) NSString *upCursor; // @synthesize upCursor=_upCursor;
@property(retain, nonatomic) NSNumber *userID; // @synthesize userID=_userID;
@property(retain, nonatomic) TFNTwitterAccountModel *accountModel; // @synthesize accountModel=_accountModel;
- (void).cxx_destruct;
- (void)processResponse:(id)arg1;
- (id)request;
- (id)initWithService:(id)arg1 accountID:(id)arg2 accountModel:(id)arg3 userID:(id)arg4 upCursor:(id)arg5 downCursor:(id)arg6 count:(id)arg7 lang:(id)arg8 referralSource:(id)arg9 requestContext:(id)arg10 includeTweetReplies:(_Bool)arg11 includeRetweets:(_Bool)arg12 includeBlockingInfo:(_Bool)arg13 source:(unsigned long long)arg14 completionBlock:(CDUnknownBlockType)arg15;
- (id)initWithService:(id)arg1 accountID:(id)arg2 authContext:(id)arg3 networkTransactionMetrics:(id)arg4 source:(unsigned long long)arg5 completionBlock:(CDUnknownBlockType)arg6;

@end

