//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFSTwitterCore/TFSTwitterLocation.h>

@interface TFSTwitterLocation (T1Display)
- (id)coordinateTextWithPrecision:(unsigned long long)arg1;
@end

