//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFSTwitterAPICommand/TFSTwitterAPICommand.h>

@class NSString;

@interface TFSTwitterAPIDeviceRegisterCommand : TFSTwitterAPICommand
{
    _Bool _sendNumericPIN;
    _Bool _notificationsDisabled;
    _Bool _updatePhone;
    NSString *_rawPhoneNumber;
    NSString *_textMessage;
}

@property(nonatomic) _Bool updatePhone; // @synthesize updatePhone=_updatePhone;
@property(nonatomic) _Bool notificationsDisabled; // @synthesize notificationsDisabled=_notificationsDisabled;
@property(nonatomic) _Bool sendNumericPIN; // @synthesize sendNumericPIN=_sendNumericPIN;
@property(retain, nonatomic) NSString *textMessage; // @synthesize textMessage=_textMessage;
@property(retain, nonatomic) NSString *rawPhoneNumber; // @synthesize rawPhoneNumber=_rawPhoneNumber;
- (void).cxx_destruct;
- (id)request;
- (id)initWithService:(id)arg1 accountID:(id)arg2 rawPhoneNumber:(id)arg3 textMessage:(id)arg4 sendNumericPIN:(_Bool)arg5 notificationsDisabled:(_Bool)arg6 updatePhone:(_Bool)arg7 source:(unsigned long long)arg8 completionBlock:(CDUnknownBlockType)arg9;
- (id)initWithService:(id)arg1 accountID:(id)arg2 authContext:(id)arg3 networkTransactionMetrics:(id)arg4 source:(unsigned long long)arg5 completionBlock:(CDUnknownBlockType)arg6;

@end

