//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, TIFPVRTexture;

@interface TIFFilterLibrary : NSObject
{
    NSMutableArray *_filters;
    TIFPVRTexture *_grit;
    TIFPVRTexture *_pointNoise;
    TIFPVRTexture *_amorphousVignette;
}

+ (id)translateName:(id)arg1 identifier:(id)arg2;
+ (id)texturePath:(id)arg1;
+ (id)removePath:(id)arg1;
- (void).cxx_destruct;
- (id)availableFilters;
- (id)initWithContext:(id)arg1 library:(id)arg2;
- (id)initWithContext:(id)arg1;
- (id)filterIdForIndex:(long long)arg1;
- (long long)indexForFilterId:(id)arg1;

@end

