//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface TIFGLUtils : NSObject
{
}

+ (double)mainScreenNativeScale;
+ (double)mainScreenScale;
+ (id)pathForResource:(id)arg1 ofType:(id)arg2;
+ (id)pathForResource:(id)arg1;
+ (id)frameworkBundle;
+ (id)imageFromTexture:(unsigned int)arg1 dimensions:(struct CGSize)arg2 useFloatComponents:(_Bool)arg3;
+ (unsigned int)loadTextureFromResource:(id)arg1;
+ (unsigned int)loadTextureFromResource:(id)arg1 forceGreyscale:(_Bool)arg2;
+ (unsigned int)loadTextureFromImage:(id)arg1;
+ (unsigned int)loadTextureFromImage:(id)arg1 forceGreyscale:(_Bool)arg2;
+ (unsigned int)assembleProgramWithVS:(id)arg1 fs:(id)arg2;
+ (unsigned int)compileShader:(id)arg1 type:(unsigned int)arg2;

@end

