//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <TwitterImagePipeline/TIPImageCache-Protocol.h>
#import <TwitterImagePipeline/TIPInspectableCache-Protocol.h>
#import <TwitterImagePipeline/TIPLRUCacheDelegate-Protocol.h>

@class NSString, TIPGlobalConfiguration, TIPLRUCache;
@protocol OS_dispatch_queue;

@interface TIPImageDiskCache : NSObject <TIPLRUCacheDelegate, TIPImageCache, TIPInspectableCache>
{
    TIPGlobalConfiguration *_globalConfig;
    NSObject<OS_dispatch_queue> *_manifestQueue;
    unsigned long long _earlyRemovedBytesSize;
    TIPLRUCache *_manifest;
    struct _opaque_pthread_mutex_t {
        long long __sig;
        char __opaque[56];
    } _manifestMutex;
    struct {
        unsigned int manifestIsLoading:1;
    } _diskCache_flags;
    NSString *_cachePath;
    long long _atomicTotalSize;
}

@property long long atomicTotalSize; // @synthesize atomicTotalSize=_atomicTotalSize;
@property(readonly, copy, nonatomic) NSString *cachePath; // @synthesize cachePath=_cachePath;
- (void).cxx_destruct;
- (void)inspect:(CDUnknownBlockType)arg1;
- (void)tip_cache:(id)arg1 didEvictEntry:(id)arg2;
- (id)filePathForSafeIdentifier:(id)arg1;
- (void)clearTemporaryFilePath:(id)arg1;
- (void)finalizeTemporaryFile:(id)arg1 withContext:(id)arg2;
- (id)openTemporaryFileForImageIdentifier:(id)arg1;
- (void)touchImageWithIdentifier:(id)arg1 orSaveImageEntry:(id)arg2;
- (void)prune;
- (void)clearAllImages:(CDUnknownBlockType)arg1;
- (void)clearImageWithIdentifier:(id)arg1;
- (void)updateImageEntry:(id)arg1 forciblyReplaceExisting:(_Bool)arg2;
- (id)imageEntryForIdentifier:(id)arg1 options:(long long)arg2 decoderConfigMap:(id)arg3;
- (id)copyImageEntryFileForIdentifier:(id)arg1 error:(out id *)arg2;
- (_Bool)renameImageEntryWithIdentifier:(id)arg1 toIdentifier:(id)arg2 error:(id *)arg3;
- (void)dealloc;
- (id)initWithPath:(id)arg1;
@property(readonly, nonatomic) long long cacheType;
@property(readonly, nonatomic) unsigned long long totalCost;
@property(readonly, nonatomic) TIPLRUCache *manifest;
- (id)diskCache_syncAccessManifest;
- (_Bool)_tip_diskCache_renameImageEntryWithIdentifier:(id)arg1 toIdentifier:(id)arg2 error:(id *)arg3;
- (void)_tip_diskCache_inspect:(CDUnknownBlockType)arg1;
- (void)_tip_diskCache_finalizeTemporaryFile:(id)arg1 withContext:(id)arg2;
- (void)_tip_diskCache_clearAllImages;
- (void)_tip_diskCache_touchEntry:(id)arg1 forced:(_Bool)arg2 partial:(_Bool)arg3;
- (_Bool)_tip_diskCache_touchImageWithSafeIdentifier:(id)arg1 forced:(_Bool)arg2;
- (void)_tip_diskCache_updateImageEntry:(id)arg1 forciblyReplaceExisting:(_Bool)arg2 safeIdentifier:(id)arg3;
- (void)diskCache_updateImageEntry:(id)arg1 forciblyReplaceExisting:(_Bool)arg2;
- (void)_tip_diskCache_populateTemporaryFileForEntry:(id)arg1;
- (void)_tip_diskCache_populatePartialImageForEntry:(id)arg1 decoderConfigMap:(id)arg2;
- (void)_tip_diskCache_populateCompleteImageForEntry:(id)arg1 decoderConfigMap:(id)arg2;
- (id)_tip_diskCache_imageEntryFromManifestWithUnsafeIdentifier:(id)arg1 options:(long long)arg2 decoderConfigMap:(id)arg3;
- (id)_tip_diskCache_imageEntryDirectlyFromDiskWithUnsafeIdentifier:(id)arg1 options:(long long)arg2 decoderConfigMap:(id)arg3;
- (id)diskCache_imageEntryForIdentifier:(id)arg1 options:(long long)arg2 decoderConfigMap:(id)arg3;
- (id)_tip_diskCache_imageEntryForUnsafeIdentifier:(id)arg1 options:(long long)arg2 decoderConfigMap:(id)arg3;
- (id)diskCache_imageEntryFilePathForIdentifier:(id)arg1 hitShouldMoveEntryToHead:(_Bool)arg2 context:(out id *)arg3;
- (id)_tip_diskCache_copyImageEntryFileForUnsafeIdentifier:(id)arg1 error:(out id *)arg2;
- (void)_tip_diskCache_ensureCacheDirectoryExists;
- (void)_tip_diskCache_addByteCount:(unsigned long long)arg1 removeByteCount:(unsigned long long)arg2;
- (void)manifest_finalizePopulateManifest:(id)arg1 totalSize:(unsigned long long)arg2;
- (void)manifest_populateEntriesFromCachePath:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)manifest_populateManifest:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

