//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TwitterImagePipeline/NSObject-Protocol.h>

@class NSObject, NSURLRequest;
@protocol OS_dispatch_queue, TIPImageFetchDownloadClient;

@protocol TIPImageFetchDownloadContext <NSObject>
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *downloadQueue;
@property(readonly, nonatomic) id <TIPImageFetchDownloadClient> client;
@property(readonly, copy, nonatomic) NSURLRequest *hydratedRequest;
@property(readonly, copy, nonatomic) NSURLRequest *originalRequest;
@end

