//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface TMGColor : NSObject
{
    double _red;
    double _green;
    double _blue;
    double _alpha;
}

+ (id)pinkColor;
+ (id)blueColor;
+ (id)yellowColor;
+ (id)redColor;
+ (id)whiteColor;
+ (id)blackColor;
+ (id)clearColor;
+ (id)colorWithRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4;
+ (id)colorWithDeviceRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4;
@property double alpha; // @synthesize alpha=_alpha;
@property double blue; // @synthesize blue=_blue;
@property double green; // @synthesize green=_green;
@property double red; // @synthesize red=_red;
- (struct CGColor *)CGColor;
- (id)colorWithAlpha:(double)arg1;
- (id)init;
- (id)initWithRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4;

@end

