//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <TwitterNetworkLayer/NSSecureCoding-Protocol.h>

@class NSData, NSDictionary, NSString;

@interface TNLAttemptMetaData : NSObject <NSSecureCoding>
{
    NSDictionary *_metaDataDictionary;
    _Bool _final;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
- (void)finalizeMetaData;
- (id)metaDataDictionary;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)initWithMetaDataDictionary:(id)arg1;
- (_Bool)hasMD5Hash;
- (void)setMD5Hash:(id)arg1;
@property(readonly, nonatomic) NSData *MD5Hash;
- (_Bool)hasExpectedMD5Hash;
- (void)setExpectedMD5Hash:(id)arg1;
@property(readonly, nonatomic) NSData *expectedMD5Hash;
- (_Bool)hasLocalCacheHit;
- (void)setLocalCacheHit:(_Bool)arg1;
@property(readonly, nonatomic) _Bool localCacheHit;
- (_Bool)hasResponseContentDownloadDuration;
- (void)setResponseContentDownloadDuration:(double)arg1;
@property(readonly, nonatomic) double responseContentDownloadDuration;
- (_Bool)hasResponseContentLength;
- (void)setResponseContentLength:(long long)arg1;
@property(readonly, nonatomic) long long responseContentLength;
- (_Bool)hasRequestContentLength;
- (void)setRequestContentLength:(long long)arg1;
@property(readonly, nonatomic) long long requestContentLength;
- (_Bool)hasServerResponseTime;
- (void)setServerResponseTime:(long long)arg1;
@property(readonly, nonatomic) long long serverResponseTime;
- (_Bool)hasLayer8BodyBytesTransmitted;
- (void)setLayer8BodyBytesTransmitted:(long long)arg1;
@property(readonly, nonatomic) long long layer8BodyBytesTransmitted;
- (_Bool)hasLayer8BodyBytesReceived;
- (void)setLayer8BodyBytesReceived:(long long)arg1;
@property(readonly, nonatomic) long long layer8BodyBytesReceived;
- (_Bool)hasHTTPVersion;
- (void)setHTTPVersion:(id)arg1;
@property(readonly, copy, nonatomic) NSString *HTTPVersion;

@end

