//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <TwitterNetworkLayer/NSCopying-Protocol.h>
#import <TwitterNetworkLayer/NSSecureCoding-Protocol.h>

@class NSArray, NSError, NSHTTPURLResponse, NSString, NSURLRequest, NSURLSessionTaskTransactionMetrics, TNLAttemptMetaData;
@protocol TNLCarrierInfo;

@interface TNLAttemptMetrics : NSObject <NSSecureCoding, NSCopying>
{
    _Bool _final;
    unsigned int _reachabilityFlags;
    long long _attemptId;
    long long _attemptType;
    unsigned long long _startMachTime;
    unsigned long long _endMachTime;
    TNLAttemptMetaData *_metaData;
    long long _reachabilityStatus;
    NSString *_WWANRadioAccessTechnology;
    id <TNLCarrierInfo> _carrierInfo;
    NSURLRequest *_URLRequest;
    NSHTTPURLResponse *_URLResponse;
    NSError *_operationError;
    NSURLSessionTaskTransactionMetrics *_taskTransactionMetrics;
    NSArray *_APIErrors;
    NSError *_responseBodyParseError;
}

+ (_Bool)supportsSecureCoding;
@property(readonly, nonatomic) NSError *responseBodyParseError; // @synthesize responseBodyParseError=_responseBodyParseError;
@property(readonly, copy, nonatomic) NSArray *APIErrors; // @synthesize APIErrors=_APIErrors;
@property(readonly, nonatomic) NSURLSessionTaskTransactionMetrics *taskTransactionMetrics; // @synthesize taskTransactionMetrics=_taskTransactionMetrics;
@property(readonly, nonatomic) NSError *operationError; // @synthesize operationError=_operationError;
@property(readonly, nonatomic) NSHTTPURLResponse *URLResponse; // @synthesize URLResponse=_URLResponse;
@property(readonly, copy, nonatomic) NSURLRequest *URLRequest; // @synthesize URLRequest=_URLRequest;
@property(readonly, nonatomic) id <TNLCarrierInfo> carrierInfo; // @synthesize carrierInfo=_carrierInfo;
@property(readonly, copy, nonatomic) NSString *WWANRadioAccessTechnology; // @synthesize WWANRadioAccessTechnology=_WWANRadioAccessTechnology;
@property(readonly, nonatomic) unsigned int reachabilityFlags; // @synthesize reachabilityFlags=_reachabilityFlags;
@property(readonly, nonatomic) long long reachabilityStatus; // @synthesize reachabilityStatus=_reachabilityStatus;
@property(readonly, nonatomic) TNLAttemptMetaData *metaData; // @synthesize metaData=_metaData;
@property(readonly, nonatomic) unsigned long long endMachTime; // @synthesize endMachTime=_endMachTime;
@property(readonly, nonatomic) unsigned long long startMachTime; // @synthesize startMachTime=_startMachTime;
@property(readonly, nonatomic) long long attemptType; // @synthesize attemptType=_attemptType;
@property(readonly, nonatomic) long long attemptId; // @synthesize attemptId=_attemptId;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)updateRequest:(id)arg1;
- (void)setAPIErrors:(id)arg1;
- (void)setResponseBodyParseError:(id)arg1;
- (void)setTaskTransactionMetrics:(id)arg1;
- (void)setURLResponse:(id)arg1;
- (void)setOperationError:(id)arg1;
- (void)setEndMachTime:(unsigned long long)arg1;
- (void)setMetaData:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (double)duration;
- (id)description;
- (void)setCommunicationMetricsWithAgent:(id)arg1;
- (void)finalizeMetrics;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithAttemptId:(long long)arg1 type:(long long)arg2 startMachTime:(unsigned long long)arg3 endMachTime:(unsigned long long)arg4 metaData:(id)arg5 URLRequest:(id)arg6 URLResponse:(id)arg7 operationError:(id)arg8;
- (id)initWithType:(long long)arg1 startMachTime:(unsigned long long)arg2 endMachTime:(unsigned long long)arg3 metaData:(id)arg4 URLRequest:(id)arg5 URLResponse:(id)arg6 operationError:(id)arg7;
- (id)init;

@end

