//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TwitterNetworkUtilities/NSObject-Protocol.h>

@class NSHTTPURLResponse, NSURLRequest, TNLRequestOperation;
@protocol TNLRequest;

@protocol TNLRequestRedirecter <NSObject>

@optional
- (void)requestOperation:(TNLRequestOperation *)arg1 willRedirectFromRequest:(NSURLRequest<TNLRequest> *)arg2 withResponse:(NSHTTPURLResponse *)arg3 toRequest:(NSURLRequest<TNLRequest> *)arg4 completion:(void (^)(id <TNLRequest>))arg5;
@end

