//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@interface TNLTimeoutOperation : NSOperation
{
    // Error parsing type: AB, name: _executingFlag
    // Error parsing type: AB, name: _finishedFlag
    double _timeoutDuration;
}

@property(readonly, nonatomic) double timeoutDuration; // @synthesize timeoutDuration=_timeoutDuration;
- (void)_tnl_complete;
- (void)start;
- (_Bool)isAsynchronous;
- (_Bool)isConcurrent;
- (_Bool)isFinished;
- (_Bool)isExecuting;
- (id)initWithTimeoutDuration:(double)arg1;

@end

