//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TwitterNetworkUtilities/TNUHARObject.h>

@class NSDate, NSString;

@interface TNUHARPage : TNUHARObject
{
    NSString *_pageId;
    NSString *_title;
    NSDate *_startedDateTime;
}

@property(retain, nonatomic) NSDate *startedDateTime; // @synthesize startedDateTime=_startedDateTime;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *pageId; // @synthesize pageId=_pageId;
- (void).cxx_destruct;
- (id)mutableJSONDictionary;

@end

