//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TwitterText/TwitterText.h>

@interface TwitterText (TFNTwitterComposition)
+ (long long)tweetLengthWithDiscountedURLs:(id)arg1 httpsURLLength:(long long)arg2;
@end

