//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewController.h>

@interface UICollectionViewController (TFN_iOS9PreviewingWorkaround)
+ (void)load;
- (id)tfn_previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
@end

