//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

@interface UIScrollView (PTVAdditions)
@property(readonly, nonatomic) struct UIEdgeInsets ptv_adjustedContentInset;
- (void)ptv_setAutomaticContentInsetAdjustmentEnabled:(_Bool)arg1;
@end

