//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextField.h>

@interface UITextField (TFNAdditions)
- (id)uiTextRangeFromNSRange:(struct _NSRange)arg1;
- (struct _NSRange)nsRangeFromUITextRange:(id)arg1;
- (_Bool)fieldIsEmpty;
- (_Bool)isDictationRunning;
@end

